Repository RedisLabs/redislabs-docs, pull requests merged in 2019-07, with the labels that each got.

#440 fixing module upgrade notations
  content/rs/developing/modules/upgrading.md
Labels: bug

#398 Track search via GA events
  layouts/partials/flex/scripts.html
  static/js/search.js
Labels: infrastructure, ready to merge

#432 Change login command to project command
  content/platforms/openshift/_index.md
Labels: bug

#439 Add Quick Start and Developing page for TimeSeries
  content/rs/developing/modules/installing.md
  content/rs/developing/modules/redisgraph.md
  content/rs/developing/modules/redistimeseries.md
  content/rs/getting-started/creating-database/rebloom.md
  content/rs/getting-started/creating-database/redisearch.md
  content/rs/getting-started/creating-database/redisgraph-quick-start.md
  content/rs/getting-started/creating-database/redistimeseries.md
  content/rs/getting-started/creating-database/rejson-quick-start.md
  static/images/rs/TimeSeries-DataIngestion.png
  static/images/rs/TimeSeries-ReadQueries.png
  static/images/rs/TimeSeries-UsedMemory.png
  static/images/rs/TimeSeries-downsampling1.png
  static/images/rs/TimeSeries-downsampling2.png
  static/images/rs/TimeSeries-integrations.png
  static/images/rs/TimeSeries-modeling1.jpg
  static/images/rs/TimeSeries-modeling2.jpg
  static/images/rs/TimeSeries-modeling3.jpg
  static/images/rs/TimeSeries-modeling4.jpg
Labels: enhancement

#441 Add detail to mount point backup explanation
  content/rs/administering/database-operations/importing-data.md
Labels: enhancement

#438 Add notes to release notes and docs for CRDB with RoF on Redis 5
  content/rs/administering/database-operations/create-crdb.md
  content/rs/administering/intercluster-replication/crdbs.md
  content/rs/release-notes/rs-5-4-4-june-2019.md
Labels: bug

#423 RED-29925 Add instructions for adding features to docs
  content/contribution-guide.md
  content/editing-guide.md
Labels: infrastructure

#430 Change CRDB to Active-Active; Replica Of to Active-Passive
  content/platforms/openshift/getting-started-openshift-crdb.md
  content/rs/administering/active-active.md
  content/rs/administering/active-passive.md
  content/rs/administering/database-operations/create-crdb.md
  content/rs/administering/database-operations/creating-database.md
  content/rs/administering/database-operations/eviction-policy.md
  content/rs/administering/designing-production/security/tls-configuration.md
  content/rs/administering/designing-production/synchronizing-clocks.md
  content/rs/administering/intercluster-replication/_index.md
  content/rs/developing/crdbs/_index.md
  content/rs/developing/modules/redisearch.md
  content/rs/installing-upgrading/configuring/mdns.md
  content/rs/release-notes/rlec-4-2-october-2015.md
  content/rv/administration/setup_and_editing/creating-databases.md
  content/rv/concepts/data-eviction-policies.md
Labels: enhancement

#448 Revert "Track search via GA events" but leave site search parameter
  layouts/partials/flex/scripts.html
  static/js/search.js
Labels: bug, infrastructure

#455 minor grammar fixes and simplifications to maintenance-mode.md
  content/rs/administering/cluster-operations/maintenance-mode.md
Labels: typo

#462 Docker supported for development and testing only
  content/rs/_index.md
  content/rs/administering/database-operations/create-crdb.md
  content/rs/administering/designing-production/supported-platforms.md
  content/rs/getting-started/creating-database/redis-flash.md
  content/rs/getting-started/docker/_index.md
  content/rs/getting-started/docker/getting-started-docker.md
  content/rs/getting-started/quick-setup.md
  content/rs/installing-upgrading/downloading-installing.md
  content/rs/new-features-redis-enterprise.md
  content/rs/release-notes/redis-enterprise-5.md
Labels: bug

#452 PKS Getting Started staged and ready, k8s still WIP
  content/platforms/kubernetes/_index.md
  content/platforms/pks/_index.md
Labels: bug

#468 Release notes 5.4.6
  content/rs/release-notes/rs-5-4-4-june-2019.md
  content/rs/release-notes/rs-5-4-6-july-2019.md
Labels: next version

#454 fix maintenance_mode flag names.
  content/rs/administering/cluster-operations/maintenance-mode.md
Labels: enhancement, ready to merge

#431 Red 30054 crossslot error resolved
  content/rs/concepts/high-availability/clustering.md
Labels: enhancement, ready to merge

#429 Make shortcodes work in embedded files
  config.toml
  content/cheatsheet.md
  content/embeds/_index.md
  content/embeds/account-role-table.html
  content/embeds/backup-locations.md
  content/embeds/compatible-with-oss.md
  content/embeds/create-db.md
  content/embeds/how-many-databases-cloud.md
  content/embeds/how-many-databases-software.md
  content/embeds/sample.html
  content/embeds/sample.md
  content/embeds/what-is-redis-enterprise.md
  content/rc/faqs/_index.md
  content/rs/faqs/_index.md
  content/rv/faqs/_index.md
  layouts/index.json
  layouts/partials/embeds/sample.md
  layouts/partials/flex/head.html
  layouts/shortcodes/embed-html.html
  layouts/shortcodes/embed-md.html
Labels: infrastructure
