Repository RedisLabs/redislabs-docs, pull requests merged in 2019-02, with the labels that each got.

#218 RED-26670 Improve user experience for updating certificates
  content/rs/administering/cluster-operations/updating-certificates.md
Labels: bug, ready to merge

#214 Add examples and missing parameters to cluster recovery
  content/rs/administering/troubleshooting/cluster-recovery.md
Labels: bug

#206 Add ldap_bind_dn to example saslauthd.conf file
  content/rs/administering/security/ldap-integration.md
Labels: bug

#216 RED-25830 Specify new CRDB with same version
  content/rs/administering/database-operations/create-crdb.md
  content/rs/administering/designing-production/synchronizing-clocks.md
Labels: bug

#172 Improve explanation of moving socket files
  content/rs/installing-upgrading/configuring/change-location-socket-files.md
Labels: bug, ready to merge

#222 Rewrite Add Nodes
  content/rs/administering/cluster-operations/adding-node.md
  content/rs/getting-started/getting-started-crdbs.md
Labels: enhancement, ready to merge

#215 Page anchor position
  static/theme-flex/custom.js
  static/theme-flex/style.css
Labels: infrastructure, ready to merge

#219 Add port 9081 to list of required ports
  content/rs/administering/designing-production/networking/port-configurations.md
Labels: bug
