Repository RedisLabs/redislabs-docs, pull requests merged in 2019-09, with the labels that each got.

#494 remove old image
  content/rv/administration/setup_and_editing/viewing-editing-databases.md
Labels: bug

#498 Prevent content in embeds directory from being indexed
  layouts/index.json
  static/js/search.js
Labels: infrastructure

#490 DOC-85 Migrate howto articles
  content/rs/administering/cluster-operations/adding-node.md
  content/rs/administering/cluster-operations/new-cluster-setup.md
  content/rs/administering/cluster-operations/removing-node.md
  content/rs/administering/cluster-operations/updating-certificates.md
  content/rs/administering/designing-production/networking/multi-ip-ipv6.md
  content/rs/administering/monitoring-metrics/nagios-plugin.md
  content/rs/administering/troubleshooting/cluster-recovery.md
  content/rs/administering/troubleshooting/database-recovery.md
  content/rs/administering/troubleshooting/replicaof-repeatedly-fails.md
  content/rs/installing-upgrading/upgrading.md
  content/rs/references/cli-reference/memtier-benchmark.md
  content/rs/references/cli-reference/rladmin.md
  content/rs/references/cli-reference/rlcheck.md
  content/rs/references/client_references/_index.md
  content/rs/references/client_references/client_c.md
  content/rs/references/client_references/client_csharp.md
  content/rs/references/client_references/client_drupal.md
  content/rs/references/client_references/client_java.md
  content/rs/references/client_references/client_nodejs.md
  content/rs/references/client_references/client_php.md
  content/rs/references/client_references/client_python.md
  content/rs/references/client_references/client_ruby.md
  content/rs/references/clustering-redis.md
  content/rs/references/connecting-to-redis.md
  content/rs/references/memtier-benchmark.md
  content/rs/references/procedures-previous-releases.md
  content/rs/references/rladmin.md
  content/rs/references/rlcheck.md
  content/rs/release-notes/rlec-4-2-october-2015.md
  content/rs/release-notes/rlec-4-3-aug-2016.md
Labels: enhancement

#500 Add CLI reference aliases
  content/rs/references/_index.md
  content/rs/references/memtier-benchmark.md
  content/rs/references/rladmin.md
  content/rs/references/rlcheck.md
Labels: bug

#485 New cert update method through RLADMIN
  content/rs/administering/cluster-operations/updating-certificates.md
Labels: enhancement, security

#491 Turn into an index page
  content/platforms/pcf/_index.md
  content/platforms/pcf/installing-pcf.md
Labels: enhancement

#499 Add shortcode for displaying tables based on CSV files
  content/cheatsheet.md
  layouts/shortcodes/table-csv.html
  static/tables/test_table.csv
Labels: infrastructure

#493 GCP support
  content/rv/administration/setup_and_editing/view-edit-subscription.md
  content/rv/quick-setup.md
Labels: next version

#502 Updated FAQ with PSP info, cluster admin password
  content/platforms/faqs/_index.md
Labels: enhancement

#503 Add note about inability and warning abt password
  content/platforms/openshift/_index.md
Labels: enhancement

#506 Use gserviceaccount.com account for bucket instead of garantiadata.com
  content/rc/how-to/importing-dataset-redis-cloud.md
Labels: bug

#505 Update upgrading.md
  content/rs/developing/modules/upgrading.md
Labels: enhancement

#512 Added link to Platforms docs landing
  content/rs/administering/designing-production/supported-platforms.md
Labels: enhancement

#513 Update PCF to Pivotal Platform
  content/platforms/pcf/_index.md
  content/platforms/pcf/backup-restore-pcf.md
  content/platforms/pcf/using-pcf.md
  content/platforms/pks/_index.md
Labels: bug

#516 Minor update to reflect changes in RCP
  content/rv/concepts/data-persistence.md
Labels: bug

#497 Secure ports usage
  content/rs/administering/active-active.md
  content/rs/administering/database-operations/create-crdb.md
  content/rs/getting-started/getting-started-crdbs.md
Labels: enhancement, in progress

#515 Remove unnecessary reference
  content/rs/installing-upgrading/configuring/linux-swap.md
Labels: typo
