Repository RedisLabs/redislabs-docs, pull requests merged in 2019-10, with the labels that each got.

#523 Downtime during persistence restore
  content/rs/installing-upgrading/upgrading.md
Labels: bug

#507 Complete example for 3 nodes
  content/rs/installing-upgrading/configuring/cluster-name-dns-connection-management/_index.md
Labels: bug

#524 RED-27808 - add support permissions to RedislabsIAMUserRestrictedPoli…
  content/rv/how-to/creating-aws-user-redis-enterprise-vpc.md
Labels: enhancement

#520 Improve certificate procedures
  content/rs/administering/designing-production/security/client-connections.md
Labels: bug

#528 Updated docker output, removed CF link, removed duplicated docs
  config.toml
  content/ri/install/install-docker.md
  content/ri/using-redisinsight/how-rdbtools-works.md
  content/ri/using-redisinsight/memory-analysis.md
Labels: in progress

#525 RED-23186 add documentation for exporting logs via a sidecar
  content/platforms/kubernetes/kubernetes-logs.md
Labels: enhancement

#519 RED-32682 psync2
  content/rs/administering/active-active.md
Labels: enhancement

#532 RED-34020 Remove limitation of CRDB with ROF on redis 5
  content/rs/administering/active-active.md
  content/rs/administering/database-operations/create-crdb.md
Labels: next version

#495 RED-31976 cluster recovery on k8s
  content/platforms/kubernetes/cluster-recovery.md
Labels: next version

#533 Add 5.4.10 release notes
  content/rs/release-notes/rs-5-4-10-october-2019.md
Labels: next version

#514 Added note about cluster recovery checkbox
  content/platforms/pcf/_index.md
Labels: enhancement

#538 Reflect NET_RAW and priv. escalation change, persistence default behavior
  content/platforms/faqs/_index.md
  content/platforms/kubernetes/kubernetes-persistent-volumes.md
Labels: bug

#540 Https all the things
  content/contribution-guide.md
  content/rs/administering/designing-production/networking/port-configurations.md
  content/rs/administering/designing-production/security/account-management.md
Labels: enhancement, security

#545 New header and footer style
  config.toml
  layouts/partials/flex/body-aftercontent.html
  layouts/partials/flex/body-beforecontent.html
  layouts/partials/footer.html
  static/css/nucleus.css
  static/theme-flex/custom.js
  static/theme-flex/script.js
  static/theme-flex/style.css
Labels: infrastructure

#541 Add lfu eviction policies for RC Essentials
  content/rc/concepts/data-eviction-policies.md
Labels: enhancement

#535 Add lfu eviction policies for RC Pro
  content/rv/concepts/data-eviction-policies.md
Labels: enhancement
