Repository RedisLabs/redislabs-docs, pull requests merged in 2019-11, with the labels that each got.

#537 Add note to receive notifications on node join and remove (alerts)
  content/rs/administering/cluster-operations/settings/alerts.md
Labels: bug

#536 Remove note to receive notifications on node join and remove (alerting)
  content/rs/administering/database-operations/alerting.md
Labels: bug

#553 Update compatibility with OSS cluster
  content/rs/concepts/compatibility.md
Labels: bug

#556 Correct service type default for OpenShift
  content/platforms/openshift/_index.md
Labels: bug

#561 Added reference to K8s recovery
  content/rs/administering/troubleshooting/cluster-recovery.md
Labels: enhancement

#557 Update K8s to Kubernetes in title, body
  content/platforms/faqs/_index.md
  content/platforms/openshift/_index.md
  content/platforms/pks/_index.md
  content/ri/installing/install-k8s.md
Labels: typo

#548 remove `enterprise` from redisearch
  content/rs/concepts/high-availability/clustering.md
  content/rs/developing/modules/_index.md
  content/rs/developing/modules/installing.md
  content/rs/developing/modules/redisearch.md
  content/rs/developing/modules/upgrading.md
Labels: bug

#560 Improve accuracy of PCF instructions
  content/platforms/pcf/_index.md
Labels: typo

#566 wording fix
  content/platforms/kubernetes/kubernetes-logs.md
Labels: typo

#567 Clarify kubectl command usage with examples
  content/platforms/kubernetes/upgrading-kubernetes-with-operator.md
Labels: enhancement

#558 RedisInsight: Added docs for log files
  content/ri/using-redisinsight/troubleshooting.md
Labels: enhancement

#576 Update _index.md
  content/rv/_index.md
Labels: typo

#575 Added a bit of clarity to description in the beginning.
  content/rs/administering/troubleshooting/database-recovery.md
Labels: enhancement
