Repository RedisLabs/redislabs-docs, pull requests merged in 2019-05, with the labels that each got.

#344 Update _index.md
  content/rs/concepts/kubernetes-architecture/_index.md
Labels: typo

#332 RED-26382 Add instruction to specify database port number in docker
  content/rs/getting-started/docker/getting-started-docker.md
Labels: bug

#348 Fix version dropdown opening #335
  layouts/partials/flex/scripts.html
  static/theme-flex/style.css
Labels: infrastructure

#346 Add shortcode to keep code snippets in /static/code
  content/cheatsheet.md
  content/rs/administering/monitoring-metrics/prometheus-integration.md
  layouts/shortcodes/embed-code.html
  static/code/database.json
Labels: infrastructure, next version

#353 Typo in supported-clients-browsers.md
  content/rs/administering/designing-production/supported-clients-browsers.md
Labels: typo

#352 create CRDB | Participant URL HTTPS port change
  content/rs/administering/database-operations/create-crdb.md
Labels: bug

#350 Configure AWS instance with only needed ports
  content/rs/installing-upgrading/configuring-aws-instances.md
Labels: enhancement

#357 Fix mistake in client connections
  content/rs/administering/designing-production/security/client-connections.md
Labels: bug

#360 RV - infrastructure typo
  content/rv/_index.md
Labels: typo

#362 Separate json files, move to /rs
  content/rs/administering/monitoring-metrics/prometheus-integration.md
  static/code/database.json
  static/code/rs/cluster.json
  static/code/rs/database.json
  static/code/rs/node.json
Labels: bug

#231 Add table of RS hot topics
  content/rs/_index.md
  layouts/partials/flex/body-beforecontent.html
  layouts/partials/rs-hot-topics-table.html
  static/theme-flex/img/icons_Hot-topics-2.svg
  static/theme-flex/img/icons_Hot-topics.svg
  static/theme-flex/style.css
Labels: enhancement, ready to merge

#363 Add "expand/collapse all" to main menu
  layouts/partials/menu.html
  static/theme-flex/script.js
  static/theme-flex/style.css
Labels: infrastructure, ready to merge

#364 Increase minimum RAM for development environments
  content/rs/administering/designing-production/hardware-requirements.md
Labels: enhancement

#361 Remove installation flag for sockets location
  content/rs/installing-upgrading/downloading-installing.md
Labels: bug

#366 Tweak expand/collapse behavior
  static/theme-flex/script.js
  static/theme-flex/style.css
Labels: infrastructure

#354 Adding EOL for Modules
  content/rs/administering/product-lifecycle.md
Labels: enhancement

#345 TCP port 1968 missing from ports list
  content/rs/administering/designing-production/networking/port-configurations.md
Labels: bug

#334 First set of fixes for HTML errors shown by htmlproofer
  content/_footer.md
  content/cheatsheet.md
  content/rc/administration/setup-and-editing/viewing-editing-database.md
  content/rs/administering/database-operations/updating-configurations.md
  content/rs/administering/intercluster-replication/crdbs.md
  content/rs/concepts/kubernetes-architecture/k8s-operator-based-deployments.md
  content/rs/concepts/memory-architecture/redis-flash.md
  content/rs/developing/modules/bloom-filters.md
  content/rs/getting-started/k8s-openshift.md
  content/rs/getting-started/pcf.md
  content/rs/installing-upgrading/configuring/cluster-name-dns-connection-management/_index.md
  content/rs/release-notes/rs-5-4-2-april-2019.md
  content/rv/quick-setup.md
  layouts/partials/flex/body-aftercontent.html
  layouts/partials/footer.html
  static/images/rs/getting-started-kubernetes-openshift-image1.png
  static/images/rs/getting-started-kubernetes-openshift-image2.png
  static/images/rs/getting-started-kubernetes-openshift-image3.png
  static/images/rs/getting-started-kubernetes-openshift-image4.png
  static/images/rs/getting-started-kubernetes-openshift-image5.png
  static/images/rs/getting-started-kubernetes-openshift-image6.png
  static/rest-api/css/reset.css
  static/rest-api/css/screen.css
  static/rest-api/images/explorer_icons.png
  static/rest-api/images/logo_small.png
  static/rest-api/images/pet_store_api.png
  static/rest-api/images/throbber.gif
  static/rest-api/images/wordnik_api.png
  static/rest-api/index.html
  static/rest-api/lib/backbone-min.js
  static/rest-api/lib/handlebars-1.0.0.js
  static/rest-api/lib/highlight.7.3.pack.js
  static/rest-api/lib/jquery-1.8.0.min.js
  static/rest-api/lib/jquery.ba-bbq.min.js
  static/rest-api/lib/jquery.slideto.min.js
  static/rest-api/lib/jquery.wiggle.min.js
  static/rest-api/lib/shred.bundle.js
  static/rest-api/lib/shred/content.js
  static/rest-api/lib/swagger-oauth.js
  static/rest-api/lib/swagger.js
  static/rest-api/lib/underscore-min.js
  static/rest-api/o2c.html
  static/rest-api/resources.json
  static/rest-api/spec.json
  static/rest-api/swagger-ui.js
  static/rest-api/swagger-ui.min.js
Labels: infrastructure

#368 Prevent "Hot topics" from covering search results
  static/theme-flex/style.css
Labels: bug, infrastructure

#371 Remove Google + from footer
  layouts/partials/footer.html
Labels: enhancement

#373 Rewrite create databases
  content/rs/administering/database-operations/creating-database.md
  content/rs/getting-started/creating-database/_index.md
  content/rs/getting-started/creating-database/redis-flash.md
  content/rs/getting-started/docker/getting-started-docker.md
  layouts/partials/embeds/create-db.md
Labels: enhancement

#374 Fix anchors in the right TOC
  layouts/partials/mini-toc.html
Labels: infrastructure

#379 Phase 2 of HTMLproofer fixes
  content/rc/how-to/aws-zone-mapping.md
  content/rs/_index.md
  content/rs/administering/database-operations/creating-database.md
  content/rs/developing/crdbs/_index.md
  content/rs/developing/modules/bloom-filters.md
  content/rs/faqs/_index.md
  content/rs/getting-started/creating-database/redisearch.md
  content/rs/getting-started/k8s-openshift.md
  content/rs/release-notes/rs-5-4-2-april-2019.md
  content/rv/administration/setup_and_editing/creating-subscription.md
  layouts/partials/mini-toc.html
  static/code/rv/zone-mapping-user-policy.json
Labels: enhancement, infrastructure

#211 Separate platforms section
  content/platforms/_index.md
  content/platforms/kubernetes/_index.md
  content/platforms/kubernetes/kubernetes-architecture.md
  content/platforms/kubernetes/kubernetes-persistent-volumes.md
  content/platforms/kubernetes/kubernetes-with-operator.md
  content/platforms/kubernetes/sizing-kubernetes.md
  content/platforms/kubernetes/upgrading-kubernetes-with-operator.md
  content/platforms/openshift/_index.md
  content/platforms/openshift/getting-started-openshift-crdb.md
  content/platforms/pcf/_index.md
  content/rs/administering/kubernetes/_index.md
  content/rs/concepts/kubernetes-architecture/_index.md
  content/rs/faqs/_index.md
  i18n/en.toml
  layouts/partials/home/hero.html
  layouts/partials/home/options.html
  layouts/partials/menu.html
  static/images/icon_logo/platforms_icon.png
  static/theme-flex/img/icn-cloud-no-circle-2.svg
  static/theme-flex/img/icn-software-no-circle-2.svg
  static/theme-flex/img/icn-vpc-no-circle-2.svg
  static/theme-flex/img/ico-cloud-pro.svg
  static/theme-flex/img/ico-cloud.svg
  static/theme-flex/img/ico-modules.svg
  static/theme-flex/img/ico-multimodel-2.svg
  static/theme-flex/img/ico-platforms.svg
  static/theme-flex/img/ico-software.svg
  static/theme-flex/style.css
  themes/docdock/layouts/partials/header.html
Labels: enhancement

#349 Add parallel_shards_upgrade and preserve_roles to upgrade procedure
  content/rs/installing-upgrading/upgrading.md
Labels: enhancement

#376 Add key file for SFTP and backup rotation note for mount point
  layouts/partials/embeds/backup-locations.md
Labels: bug

#355 Fix line re: quorum loss check on maintenance mode
  content/rs/administering/cluster-operations/maintenance-mode.md
Labels: bug

#385 Fix few more anchor links in right TOC
  content/rc/_index.md
  content/rv/_index.md
Labels: infrastructure, ready to merge

#390 Update persistence.md
  content/rs/concepts/data-access/persistence.md
Labels: typo

#392 Landing page search tweaks
  layouts/partials/home/hero.html
  layouts/partials/home/options.html
  static/theme-flex/style.css
Labels: infrastructure, ready to merge

#336 5.4.4- AOF improvements
  content/rs/administering/intercluster-replication/crdbs.md
Labels: next version

#375 RED-26762 Add instructions for multiple modules
  content/rs/administering/database-operations/creating-database.md
  layouts/shortcodes/video.html
Labels: next version

#381 RED-13161 Add support for CRDB with RoF
  content/rs/administering/database-operations/create-crdb.md
  content/rs/administering/database-operations/creating-database.md
Labels: next version

#395 Landing page icon tweaks
  layouts/partials/home/options.html
  static/theme-flex/style.css
Labels: infrastructure, ready to merge

#394 Remove superfluous colon from URL
  content/rs/administering/database-operations/importing-data.md
Labels: bug

#397 Add link to account management
  content/rs/administering/designing-production/security/account-management.md
  content/rs/administering/designing-production/security/ldap-integration.md
Labels: bug
