Repository RedisLabs/redislabs-docs, pull requests merged in 2019-08, with the labels that each got.

#470 RED-31457 Improve intro text and specify 24-hour frequency
  content/rc/administration/configure/backups.md
  content/rv/administration/configuration/backups.md
Labels: enhancement

#456 RED-26867 Clearly mark internal ports
  content/rs/administering/designing-production/networking/port-configurations.md
Labels: enhancement

#466 PKS Getting Started
  content/platforms/kubernetes/_index.md
  content/platforms/pks/_index.md
Labels: enhancement

#472 Delete excess files (embeds, categories) in circleci
  .circleci/config.yml
  config.toml
  content/embeds/_index.md
  layouts/index.json
  layouts/partials/flex/head.html
Labels: infrastructure

#476 SSL/TLS support on Redis Cloud Essentials
  content/rc/securing-redis-cloud-connections.md
Labels: bug

#480 Add margin between code snippet and note panel
  static/theme-flex/style.css
Labels: infrastructure

#465 Page Feedback
  layouts/_default/baseof.html
  layouts/partials/flex/scripts.html
  layouts/partials/page-feedback.html
  layouts/partials/post-bottom.html
  static/theme-flex/script.js
  static/theme-flex/style.css
Labels: infrastructure

#477 Typos in persistence topic
  content/rs/concepts/data-access/persistence.md
Labels: typo

#483 Adding Cipher Info
  content/rs/administering/cluster-operations/updating-certificates.md
Labels: enhancement

#459 Updating to fix LDAP API call Bug
  content/rs/administering/designing-production/security/ldap-integration.md
Labels: bug

#484 Fix scrollbar on code snippets [Fix #427]
  static/theme-flex/style.css
Labels: infrastructure

#475 DOC-70 Copy pivnet content to docs site
  content/platforms/pcf/backup-restore-pcf.md
  content/platforms/pcf/installing-pcf.md
  content/platforms/pcf/using-pcf.md
  static/images/platforms/pcf-new-redis-db.png
  static/images/platforms/pcf-new-redis-db2.png
  static/images/platforms/pcf_add-to-dash_tile.png
  static/images/platforms/pcf_add_license.png
  static/images/platforms/pcf_apps_config_create.png
  static/images/platforms/pcf_apps_marketplace.png
  static/images/platforms/pcf_apps_service_plan.png
  static/images/platforms/pcf_apps_service_plans.png
  static/images/platforms/pcf_config-success_tile.png
  static/images/platforms/pcf_import-product_tile.png
  static/images/platforms/pcf_import_plus.png
  static/images/platforms/pcf_ops_service_plan.png
  static/images/platforms/pcf_ops_service_plan_created.png
  static/images/platforms/pcf_post-config-click.png
  static/images/platforms/pcf_pre-install_tile.png
  static/images/platforms/pcf_rc_loggregator.png
  static/images/platforms/pcf_resource_config.png
  static/images/platforms/pcf_rp_config_full_screen.png
  static/images/platforms/pcf_rp_config_full_screen2.png
  static/images/platforms/pcf_view_ops_manger.png
  static/images/platforms/post-install-dashboard.png
Labels: enhancement

#409 Update module names (RedisBloom and RedisJSON)
  content/rs/developing/modules/_index.md
  content/rs/developing/modules/bloom-filters.md
  content/rs/developing/modules/installing.md
  content/rs/developing/modules/redisjson.md
  content/rs/developing/modules/upgrading.md
  content/rs/getting-started/creating-database/RedisBloom.md
  content/rs/getting-started/creating-database/redisjson-quick-start.md
  content/rs/getting-started/creating-database/redistimeseries.md
  content/rs/new-features-redis-enterprise.md
  content/rs/release-notes/redis-enterprise-5.md
  content/rs/release-notes/release-notes-redis-enterprise-software-v5-0-2.md
  layouts/partials/rs-hot-topics-table.html
Labels: bug

#488 RED-28644 Update RAM status
  content/rs/administering/monitoring-metrics/definitions.md
  content/rs/concepts/memory-architecture/memory-management.md
Labels: enhancement

#487 RED-32344 Add Viewing Cluster Key and style changes
  content/rs/administering/cluster-operations/settings/license-keys.md
Labels: enhancement

#471 RED-30157 Add differences in dbsize and expires for crdb
  content/rs/developing/crdbs/_index.md
Labels: enhancement

#482 RED-30849 Sign-in throttling
  content/rs/administering/designing-production/security/login-lockout.md
Labels: enhancement
