Repository RedisLabs/redislabs-docs, pull requests merged in 2019-06, with the labels that each got.

#400 Add missing quotes in curl command for certificates
  content/rs/administering/cluster-operations/updating-certificates.md
Labels: bug

#399 Add release notes 5.4.4
  content/rs/release-notes/rs-5-4-4-june-2019.md
Labels: next version

#407 Update kubernetes-persistent-volumes.md
  content/platforms/kubernetes/kubernetes-persistent-volumes.md
Labels: typo

#408 Update sizing-kubernetes.md
  content/platforms/kubernetes/sizing-kubernetes.md
Labels: typo

#410 Update add modules for all quick start pages
  content/rs/administering/database-operations/creating-database.md
  content/rs/developing/modules/installing.md
  content/rs/getting-started/creating-database/rebloom.md
  content/rs/getting-started/creating-database/redisearch.md
  content/rs/getting-started/creating-database/redisgraph-quick-start.md
  content/rs/getting-started/creating-database/rejson-quick-start.md
Labels: bug

#412 Hugo upgrade fixes
  .circleci/config.yml
  layouts/partials/breadcrumb.html
  layouts/partials/flex/head.html
  layouts/partials/flex/selectnavigation.html
  layouts/partials/language-selector.html
  layouts/partials/menu.html
  layouts/partials/next-prev-page.html
  layouts/partials/original/body-beforecontent.html
  layouts/partials/post-bottom.html
  layouts/shortcodes/allchildren.html
  layouts/shortcodes/children.html
  layouts/shortcodes/relref.html
Labels: infrastructure, ready to merge

#413 Change OpenShift cli installation link to openshift site
  content/platforms/openshift/_index.md
Labels: bug

#393 Add specific IDs to remaining non-working anchors
  content/cheatsheet.md
  content/platforms/kubernetes/kubernetes-architecture.md
  content/platforms/pcf/_index.md
  content/rc/_index.md
  content/rc/concepts/clustering-redis-cloud.md
  content/rc/quick-setup-redis-cloud.md
  content/rc/securing-redis-cloud-connections.md
  content/rs/_index.md
  content/rs/administering/database-operations/create-crdb.md
  content/rs/administering/database-operations/creating-database.md
  content/rs/administering/designing-production/security/tls-configuration.md
  content/rs/administering/intercluster-replication/crdbs.md
  content/rs/administering/intercluster-replication/replica-of.md
  content/rs/administering/product-lifecycle.md
  content/rs/concepts/high-availability/clustering.md
  content/rs/concepts/high-availability/rack-zone-awareness.md
  content/rs/developing/crdbs/_index.md
  content/rs/getting-started/creating-database/redis-flash.md
  content/rs/getting-started/docker/getting-started-docker.md
  content/rs/getting-started/getting-started-crdbs.md
  content/rs/getting-started/quick-setup.md
  content/rs/installing-upgrading/configuring/cluster-name-dns-connection-management/_index.md
  content/rs/new-features-redis-enterprise.md
  content/rs/references/cli-reference/memtier-benchmark.md
  content/rs/release-notes/redis-enterprise-5.md
  content/rs/release-notes/rs-5-2-june-2018.md
  content/rs/release-notes/rs-5-4-2-april-2019.md
  content/rs/release-notes/rs-5-4-4-june-2019.md
  content/rs/release-notes/rs-5-4-december-2018.md
  content/rv/_index.md
  content/rv/concepts/clustering.md
  content/rv/quick-setup.md
  layouts/partials/flex/body-aftercontent.html
Labels: infrastructure, ready to merge

#417 Move K8s FAQs to Platforms, make K8s gettings started "draft"
  content/platforms/faqs/_index.md
  content/platforms/kubernetes/_index.md
  content/rs/faqs/_index.md
Labels: bug

#420 Fix expand shortcode after upgrade
  .circleci/config.yml
  content/rs/administering/designing-production/security/account-management.md
  content/rs/installing-upgrading/downloading-installing.md
  layouts/partials/breadcrumb.html
  layouts/partials/flex/head.html
  layouts/partials/flex/selectnavigation.html
  layouts/partials/language-selector.html
  layouts/partials/menu.html
  layouts/partials/next-prev-page.html
  layouts/partials/original/body-beforecontent.html
  layouts/partials/post-bottom.html
  layouts/shortcodes/allchildren.html
  layouts/shortcodes/children.html
  layouts/shortcodes/expand.html
  layouts/shortcodes/relref.html
Labels: infrastructure, ready to merge

#384 RED-26361 CRDB Recovery with AOF
  content/rs/administering/database-operations/create-crdb.md
  content/rs/administering/troubleshooting/cluster-recovery.md
  content/rs/administering/troubleshooting/creating-support-package.md
  content/rs/administering/troubleshooting/database-metrics-blank-during-resharding.md
  content/rs/administering/troubleshooting/database-recovery.md
  content/rs/administering/troubleshooting/network-configuration.md
  content/rs/administering/troubleshooting/testing-client-connectivity.md
Labels: next version

#419 kubectl get deployment command highlighted
  content/platforms/openshift/_index.md
Labels: bug

#426 Add limitation re: subscription during CRDB AOF recovery on 5.4.4
  content/rs/release-notes/rs-5-4-4-june-2019.md
Labels: enhancement

#436 ADD RedisTimeSeries and update RedisBloom EOL
  content/rs/administering/product-lifecycle.md
Labels: enhancement
