Repository RedisLabs/redislabs-docs, pull requests merged in 2019-12, with the labels that each got.

#568 Changed the title of the IOPS panel
  static/code/rs/database.json
Labels: bug

#554 Add reference to REST API docs
  content/rs/administering/_index.md
Labels: enhancement

#562 Update link to SIP limits
  content/rc/administration/configure/security.md
Labels: enhancement

#585 Writing style changes from Toby Ferguson
  content/rs/concepts/high-availability/clustering.md
  content/rs/concepts/high-availability/rack-zone-awareness.md
  content/rs/concepts/memory-architecture/memory-management.md
  content/rs/getting-started/docker/_index.md
  content/rs/installing-upgrading/configuring-aws-instances.md
  content/rs/installing-upgrading/configuring/cluster-name-dns-connection-management/_index.md
Labels: typo

#555 Update multi-key limitation for OSS cluster API
  content/rs/administering/designing-production/networking/using-oss-cluster-api.md
Labels: bug

#569 Update installing RedisInsight desktop for Linux
  content/ri/installing/install-redis-desktop.md
Labels: bug

#551 improve description of accumulated latency
  content/rs/administering/monitoring-metrics/prometheus-integration.md
Labels: enhancement

#589 Update rs-5-4-10-november-2019.md
  content/rs/release-notes/rs-5-4-10-november-2019.md
Labels: bug

#595 Fixing typos
  content/ri/memory-optimizations/combine-smaller-strings-to-hash.md
Labels: typo

#592 Update options to match web UI for create CRDB
  content/rs/administering/database-operations/create-crdb.md
Labels: enhancement

#573 RED-35188 Add caveat for non-identical ccs files
  content/rs/administering/troubleshooting/cluster-recovery.md
Labels: bug

#547 RED-33986 Improve edit CRDB
  content/rs/administering/database-operations/updating-configurations.md
Labels: enhancement

#534 Update for 5.4.10 changes
  content/embeds/reset-password.md
  content/rs/administering/active-active.md
  content/rs/administering/cluster-operations/settings/license-keys.md
  content/rs/administering/database-operations/create-crdb.md
  content/rs/administering/designing-production/security/account-management.md
  content/rs/administering/designing-production/security/login-lockout.md
  content/rs/administering/designing-production/supported-platforms.md
  content/rs/administering/monitoring-metrics/definitions.md
  content/rs/concepts/memory-architecture/memory-management.md
  content/rs/developing/crdbs/_index.md
  content/rs/installing-upgrading/configuring/centos-rhel-7-firewall.md
  content/rs/release-notes/rs-5-4-10-november-2019.md
Labels: next version

#597 add relative link
  content/ri/memory-optimizations/convert-to-list-instead-of-hash.md
Labels: enhancement

#599 Clarify rack-zone awareness. Fix some redunant language.
  content/rs/concepts/high-availability/rack-zone-awareness.md
Labels: enhancement

#521 RED-32998 Add Modules section with all related content
  content/cheatsheet.md
  content/embeds/modules.html
  content/embeds/tryout-redisbloom.md
  content/embeds/tryout-redisearch.md
  content/embeds/tryout-redisgraph.md
  content/embeds/tryout-redistimeseries.md
  content/modules/_index.md
  content/modules/create-database-rs.md
  content/modules/modules-lifecycle.md
  content/modules/packaging-modules.md
  content/modules/redisbloom/_index.md
  content/modules/redisbloom/redisbloom-quickstart.md
  content/modules/redisbloom/release-notes/_index.md
  content/modules/redisbloom/release-notes/v1.0/_index.md
  content/modules/redisbloom/release-notes/v1.1/_index.md
  content/modules/redisbloom/release-notes/v2.0/_index.md
  content/modules/redisbloom/release-notes/v2.2/_index.md
  content/modules/redisearch/_index.md
  content/modules/redisearch/redisearch-quickstart.md
  content/modules/redisearch/release-notes/_index.md
  content/modules/redisearch/release-notes/index.md
  content/modules/redisearch/release-notes/v1.0/_index.md
  content/modules/redisearch/release-notes/v1.1/_index.md
  content/modules/redisearch/release-notes/v1.2/_index.md
  content/modules/redisearch/release-notes/v1.4/_index.md
  content/modules/redisgraph/_index.md
  content/modules/redisgraph/redisgraph-quickstart.md
  content/modules/redisgraph/release-notes/_index.md
  content/modules/redisgraph/release-notes/v1.0/_index.md
  content/modules/redisgraph/release-notes/v1.2/_index.md
  content/modules/redisjson/_index.md
  content/modules/redisjson/redisjson-quickstart.md
  content/modules/redisjson/release-notes/_index.md
  content/modules/redisjson/release-notes/v1.0/_index.md
  content/modules/redistimeseries/_index.md
  content/modules/redistimeseries/redistimeseries-quickstart.md
  content/modules/redistimeseries/release-notes/_index.md
  content/modules/redistimeseries/release-notes/v1.0/_index.md
  content/modules/upgrading-rs.md
  content/rs/administering/product-lifecycle.md
  content/rs/developing/modules/_index.md
  content/rs/developing/modules/installing.md
  content/rs/developing/modules/upgrading.md
  content/rs/new-features-redis-enterprise.md
  content/rs/release-notes/redis-enterprise-5.md
  content/rs/release-notes/rs-5-4-10-december-2019.md
  content/rs/release-notes/rs-5-4-2-april-2019.md
  content/rs/release-notes/rs-5-4-6-july-2019.md
  content/rs/release-notes/rs-5-4-december-2018.md
  layouts/partials/home/options.html
  layouts/partials/menu.html
  static/theme-flex/img/ico-redisbloom.svg
  static/theme-flex/img/ico-redisearch.svg
  static/theme-flex/img/ico-redisgraph.svg
  static/theme-flex/img/ico-redisjson.svg
  static/theme-flex/img/ico-redistimeseries.svg
Labels: enhancement

#609 Modules section tweaks - RN order and quick start prerequisites
  content/modules/redisbloom/redisbloom-quickstart.md
  content/modules/redisbloom/release-notes/v1.0/_index.md
  content/modules/redisbloom/release-notes/v1.1/_index.md
  content/modules/redisbloom/release-notes/v2.0/_index.md
  content/modules/redisbloom/release-notes/v2.2/_index.md
  content/modules/redisearch/redisearch-quickstart.md
  content/modules/redisearch/release-notes/v1.0/_index.md
  content/modules/redisearch/release-notes/v1.1/_index.md
  content/modules/redisearch/release-notes/v1.2/_index.md
  content/modules/redisearch/release-notes/v1.4/_index.md
  content/modules/redisgraph/redisgraph-quickstart.md
  content/modules/redisgraph/release-notes/v1.0/_index.md
  content/modules/redisgraph/release-notes/v1.2/_index.md
  content/modules/redisjson/redisjson-quickstart.md
  content/modules/redisjson/release-notes/v1.0/_index.md
  content/modules/redistimeseries/redistimeseries-quickstart.md
  content/modules/redistimeseries/release-notes/v1.0/_index.md
Labels: enhancement

#598 Clarify that replication applies to shards
  content/rs/concepts/high-availability/replication.md
Labels: enhancement

#603 rename cert-type to cert-name
  content/rs/administering/cluster-operations/updating-certificates.md
Labels: bug

#588 Amazon Linux 2 is not supported
  content/rs/administering/designing-production/supported-platforms.md
Labels: bug

#614 RED-33481 Resharding policy
  content/embeds/shard-placement-intro.md
  content/rs/administering/designing-production/networking/multiple-active-proxy.md
  content/rs/administering/designing-production/performance/shard-placement.md
  content/rs/concepts/rebalancing-shard-placement.md
  content/rs/concepts/shard-placement-policy.md
  static/images/rs/shard_placement_info_cluster.png
  static/images/rs/shard_placement_rladmin_status.png
Labels: enhancement

#604 DOC-99 Specify data locations
  content/rs/installing-upgrading/file-locations.md
Labels: enhancement

#621 Add discovery service note to rs-5-4-10-december-2019
  content/rs/release-notes/rs-5-4-10-december-2019.md
Labels: enhancement

#612 RedisInsight: Added new section on configuring RedisInsight using environment variables.
  content/ri/installing/configurations.md
Labels: enhancement

#559 Warn not to do global operations before upgrading all CRDBs
  content/rs/installing-upgrading/upgrading.md
Labels: enhancement

#613 RedisInsight: Updated docs on connecting to ElastiCache.
  content/ri/using-redisinsight/add-instance.md
Labels: enhancement

#611 RedisInsight: Added documentation on supported desktop OS.
  content/ri/installing/install-redis-desktop.md
Labels: enhancement

#620 RED-36193 Fix the kubectl example commands
  content/platforms/kubernetes/kubernetes-logs.md
Labels: bug

#628 Re-organize platforms articles
  content/platforms/kubernetes/_index.md
  content/platforms/kubernetes/cluster-recovery.md
  content/platforms/kubernetes/kubernetes-architecture.md
  content/platforms/kubernetes/kubernetes-logs.md
  content/platforms/kubernetes/kubernetes-with-operator.md
  content/platforms/kubernetes/sizing-kubernetes.md
  content/platforms/kubernetes/upgrading-kubernetes-with-operator.md
  content/platforms/openshift/_index.md
  content/platforms/pcf/_index.md
Labels: enhancement

#629 Improve description of shard policy impact
  content/rs/concepts/shard-placement-policy.md
Labels: bug
