Repository RedisLabs/redislabs-docs, pull requests merged in 2019-03, with the labels that each got.

#205 Add style for images that should not be clickable
  content/rv/administration/setup_and_editing/creating-databases.md
  content/rv/administration/setup_and_editing/view-edit-subscription.md
  static/theme-flex/style.css
Labels: bug, infrastructure, ready to merge

#233 Update network ports list
  content/rs/administering/designing-production/networking/port-configurations.md
Labels: bug

#293 Update hamburger menu, footer and favicon
  layouts/partials/flex/body-aftercontent.html
  layouts/partials/flex/body-beforecontent.html
  layouts/partials/footer.html
  layouts/partials/navigation.html
  static/images/icon_logo/favicon-32x32.png
  static/theme-flex/style.css
Labels: infrastructure

#204 Add context text for search results
  static/theme-flex/style.css
  themes/docdock/static/js/search.js
Labels: enhancement, infrastructure

#232 Add intro and links for more information in cheatsheet
  content/cheatsheet.md
  layouts/shortcodes/video.html
  static/images/rs/crdb_service_account.mp4
Labels: enhancement, infrastructure

#243 lets use account number rather then account name to authenticate S3 b…
  content/rc/how-to/importing-dataset-redis-cloud.md
Labels: bug

#296 Add font smoothing for burger menu text
  static/theme-flex/style.css
Labels: infrastructure

#228 RED-23379 Maintenance Mode 5.4.2
  content/rs/administering/cluster-operations/maintenance-mode.md
Labels: next version, ready to merge

#235 Embed Shortcode
  content/cheatsheet.md
  layouts/partials/embeds/sample.html
  layouts/partials/embeds/sample.md
  layouts/shortcodes/embed-html.html
  layouts/shortcodes/embed-md.html
Labels: infrastructure, ready to merge

#294 Map port 9443 in Docker getting started
  content/rs/getting-started/docker/getting-started-docker.md
Labels: bug

#301 Post-release RC/RV unification fixes
  content/rc/administration/setup-and-editing/create-subscription.md
  content/rc/administration/setup-and-editing/creating-databases.md
  content/rc/quick-setup-redis-cloud.md
  content/rv/administration/setup_and_editing/creating-subscription.md
  content/rv/administration/setup_and_editing/view-edit-subscription.md
  content/rv/quick-setup.md
Labels: bug
