Repository RedisLabs/redislabs-docs, pull requests merged in 2020-01, with the labels that each got.

#625 RED-35288 Simplified cloud signup changes
  content/embeds/create-subscription-next-steps.md
  content/rc/administration/setup/create-subscription.md
  content/rc/administration/setup/customize-pro.md
  content/rc/quick-setup.md
Labels: next version

#634 RediSearch 1.4.20
  content/modules/redisearch/release-notes/v1.4/_index.md
Labels: enhancement

#627 Added release notes for v1.1.0
  content/ri/release-notes/v1.1.0.md
Labels: enhancement

#615 RED-36146 Support for Oracle Linux 7.6
  content/rs/administering/designing-production/supported-platforms.md
Labels: enhancement

#637 Update active-passive syncer process
  content/rs/administering/active-active.md
Labels: enhancement

#638 expand on Storage Class
  content/platforms/kubernetes/kubernetes-persistent-volumes.md
Labels: enhancement

#641 RED-36886 Clean up How To's for RC
  content/contribution-guide.md
  content/rc/how-to/aws-zone-mapping.md
  content/rc/how-to/flush-db.md
  content/rc/how-to/importing-data.md
  content/rc/how-to/importing-dataset-redis-cloud.md
  content/rc/how-to/multiple-accounts.md
Labels: bug

#647 updated to reflect correct RS version
  content/platforms/release-notes/k8s-5-4-10-8-january-2020.md
Labels: enhancement

#649 Update private-public-endpoints.md
  content/rs/administering/designing-production/networking/private-public-endpoints.md
Labels: bug
