Repository RedisLabs/redislabs-docs, pull requests merged in 2020-10, with the labels that each got.

#1065 Remove "lease recently used" from volatile-ttl eviction
  content/rs/administering/database-operations/eviction-policy.md
Labels: bug

#988 Formatting changes to change K8s RN subheadings to bullets
  content/platforms/release-notes/k8s-5-4-10-8-january-2020.md
  content/platforms/release-notes/k8s-6-0-6-11-2020-07.md
  content/platforms/release-notes/k8s-6-0-6-23-2020-08.md
  content/platforms/release-notes/k8s-6-0-6-6-2020-06.md
  content/ri/release-notes/v1.2.0.md
Labels: enhancement

#1071 Remove the - *url:*
  content/rc/administration/configuration/backups.md
Labels: typos/format

#1078 change wording "rladmin" to Active-active
  content/rs/administering/designing-production/networking/using-oss-cluster-api.md
Labels: bug

#1070 DOC-355 Module dependency installation not required
  content/modules/redisgears/installing-redisgears.md
Labels: feature

#1053 DOC-239 Add ports for internode encryption
  content/rs/administering/designing-production/networking/port-configurations.md
Labels: feature

#1073 DOC-379 Add note that RediSearch 1 and 2 not supported on the same da…
  content/modules/add-module-to-database.md
Labels: bug

#1064 join nodes concurrently to a cluster
  content/rs/administering/adding-node.md
Labels: typos/format

#1082 Add RedisGraph 2.0.20 and 2.0.21
  content/modules/redisgraph/release-notes/redisgraph-2.0-release-notes.md
Labels: enhancement
