Repository RedisLabs/redislabs-docs, pull requests merged in 2020-02, with the labels that each got.

#662 Add syntax for s3 backup file
  content/ri/using-redisinsight/memory-analysis.md
Labels: enhancement

#655 Adding all latest ga module release notes
  content/embeds/modules.html
  content/modules/modules-lifecycle.md
  content/modules/redisbloom/release-notes/v2.2/_index.md
  content/modules/redisearch/release-notes/v1.4/_index.md
  content/modules/redisearch/release-notes/v1.6/_index.md
  content/modules/redisgraph/release-notes/v1.2/_index.md
  content/modules/redisgraph/release-notes/v2.0/_index.md
  content/modules/redistimeseries/release-notes/v1.0/_index.md
  content/modules/redistimeseries/release-notes/v1.2/_index.md
  layouts/shortcodes/table-csv.html
  static/tables/redisbloom-lifecycle.csv
  static/tables/redisearch-lifecycle.csv
  static/tables/redisgraph-lifecycle.csv
  static/tables/redisjson-lifecycle.csv
  static/tables/redistimeseries-lifecycle.csv
Labels: enhancement

#652 Add k8s cluster recovery workaround to cluster recovery article
  content/embeds/force-delete-pods.md
  content/platforms/kubernetes/kubernetes-cluster-recovery.md
  content/platforms/release-notes/k8s-5-4-10-8-january-2020.md
  content/rs/administering/troubleshooting/cluster-recovery.md
Labels: enhancement

#653 Updated with typo (19->2020), CRD limitation
  content/platforms/release-notes/k8s-5-4-10-8-january-2020.md
Labels: bug

#646 Add feedback email for RedisInsight customers with questions
  content/ri/using-redisinsight/troubleshooting.md
Labels: enhancement

#658 Added release notes for RedisInsight 1.2.0
  content/ri/release-notes/v1.0.0.md
  content/ri/release-notes/v1.1.0.md
  content/ri/release-notes/v1.2.0.md
Labels: enhancement

#665 Cleanup remnants of RC VPC
  content/rs/concepts/memory-architecture/redis-flash.md
Labels: typo

#664 Add a link to the full installation
  content/rs/getting-started/quick-setup.md
Labels: enhancement

#669 Fix module formatting
  content/modules/redisbloom/release-notes/v2.2/_index.md
  content/modules/redisearch/release-notes/v1.4/_index.md
  content/modules/redisearch/release-notes/v1.6/_index.md
  content/modules/redisgraph/release-notes/v1.0/_index.md
  content/modules/redisgraph/release-notes/v2.0/_index.md
  content/modules/redistimeseries/release-notes/v1.2/_index.md
Labels: bug

#670 Typo
  content/rc/_index.md
Labels: typo

#678 georeadiusbymember changed to georadiusbymember
  content/rc/concepts/clustering.md
Labels: typo

#672 Added release notes for RedisInsight 1.2.1
  content/ri/release-notes/v1.2.0.md
Labels: enhancement

#666 RS quick setup with embed and links to full install
  content/embeds/cluster-setup.md
  content/rs/getting-started/docker/getting-started-docker.md
  content/rs/getting-started/quick-setup.md
Labels: enhancement

#650 RED-34934 RoF supports modules (also update module screenshots and versions)
  content/modules/upgrading-rs.md
  content/rs/administering/database-operations/creating-database.md
  static/images/rs/add-user-email-alerts.mp4
  static/images/rs/add_module.png
  static/images/rs/multiple-modules.mp4
  static/images/rs/rebloom_database.png
  static/images/rs/redisearch_partitions.png
  static/images/rs/select_module.png
  static/images/rs/update_available-1.png
  static/images/rs/upgrade_module-1.png
  static/images/rs/upload_module.png
  static/images/rs/useradd-300x101.png
Labels: feature, next version

#692 RedisInsight docs: Updated instructions to add db.
  content/ri/using-redisinsight/add-instance.md
  static/images/ri/add-database-button-screen.png
  static/images/ri/add-db-added-screen.png
  static/images/ri/add-db-cluster-seed-nodes-screen.png
  static/images/ri/add-db-form-screen.png
  static/images/ri/add-db-menu-screen.png
  static/images/ri/add-db-sentinel-form-screen.png
  static/images/ri/add-db-tls-client-auth-screen.png
  static/images/ri/add-db-tls-screen.png
Labels: enhancement

#690 RED-38010 Long running actions
  content/rs/administering/cluster-operations/settings/alerts.md
  content/rs/administering/database-operations/alerting.md
  static/images/rs/icon_warning.png
  static/images/rs/newredisflashdb.png
Labels: feature, next version, ready to merge

#684 Design updates to the Docs site
  static/theme-flex/style.css
Labels: enhancement, infrastructure
