Repository RedisLabs/redislabs-docs, pull requests merged in 2020-03, with the labels that each got.

#697 Update combine-smaller-strings-to-hash.md
  content/ri/memory-optimizations/combine-smaller-strings-to-hash.md
Labels: typo

#688 Add parsed REST API doc
  content/rs/references/http_rest_api.md
  static/images/rs/graphviz-1afaf34d7ea281023cccf5e0e3a6c61da5f3a013.png
  static/images/rs/graphviz-670bbb07fd7e9618b3ed315d2ab0c99b16e3e0fb.png
  static/images/rs/graphviz-da1250127777c2330823f1348260152a0eaa9bad.png
  static/images/rs/graphviz-f62c695810a6a3b8a94c77db07ac9f5643f0ff0f.png
Labels: enhancement

#699 Formatting fixes
  content/rc/administration/setup/create-subscription.md
  content/rc/administration/setup/customize-pro.md
  content/rc/quick-setup.md
  content/rs/administering/cluster-operations/updating-certificates.md
Labels: typos/format

#673 RED-37763 Revise hardware requirements to refer to each node
  content/rs/administering/designing-production/hardware-requirements.md
Labels: enhancement

#686 Standardize Module and Platform RN titles
  content/modules/redisbloom/release-notes/redisbloom-1.0-release-notes.md
  content/modules/redisbloom/release-notes/redisbloom-1.1-release-notes.md
  content/modules/redisbloom/release-notes/redisbloom-2.0-release-notes.md
  content/modules/redisbloom/release-notes/redisbloom-2.2-release-notes.md
  content/modules/redisbloom/release-notes/v1.1/_index.md
  content/modules/redisearch/release-notes/redisearch-1.0-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.1-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.2-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.4-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.6-release-notes.md
  content/modules/redisgraph/release-notes/redisearch-1.2-release-notes.md
  content/modules/redisgraph/release-notes/redisearch-2.0-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-1.0-release-notes.md
  content/modules/redisjson/release-notes/redisjson-1.0-release-notes.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.0-release-notes.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.2-release-notes.md
Labels: enhancement

#702 RED-25846 Added MFA & MFA enforcement
  content/rc/administration/account-team-settings.md
Labels: feature, next version

#705 Fix link
  content/rc/administration/configuration/security.md
Labels: typos/format

#706 Fix bold
  content/rc/administration/configuration/backups.md
Labels: typos/format

#704 Specify in terminology that there is only one endpoint
  content/rs/concepts/terminology.md
Labels: enhancement

#713 Update backup-locations.md
  content/embeds/backup-locations.md
Labels: bug

#712 Rewrite RS installation; Reorganize installation and supported platforms
  content/rs/administering/cluster-operations/adding-node.md
  content/rs/administering/cluster-operations/new-cluster-setup.md
  content/rs/administering/cluster-operations/removing-node.md
  content/rs/administering/cluster-operations/replacing-node.md
  content/rs/administering/troubleshooting/cluster-recovery.md
  content/rs/concepts/memory-architecture/redis-flash.md
  content/rs/getting-started/creating-database/redis-flash.md
  content/rs/getting-started/quick-setup.md
  content/rs/installing-upgrading/_index.md
  content/rs/installing-upgrading/configuring-aws-instances.md
  content/rs/installing-upgrading/configuring/_index.md
  content/rs/installing-upgrading/configuring/change-location-socket-files.md
  content/rs/installing-upgrading/configuring/cluster-dns.md
  content/rs/installing-upgrading/configuring/configuring-aws-route53-dns-redis-enterprise.md
  content/rs/installing-upgrading/configuring/linux-swap.md
  content/rs/installing-upgrading/configuring/mdns.md
  content/rs/installing-upgrading/downloading-installing.md
  content/rs/installing-upgrading/file-locations.md
  content/rs/installing-upgrading/offline-installation.md
  content/rs/installing-upgrading/supported-platforms.md
  content/rs/installing-upgrading/upgrading.md
  content/rs/references/memtier-benchmark.md
  content/rs/release-notes/rlec-4-2-october-2015.md
Labels: enhancement

#716 Update rs-5-4-14-february-2020.md
  content/rs/release-notes/rs-5-4-14-february-2020.md
Labels: bug

#720 Update rs-5-4-14-february-2020.md
  content/rs/release-notes/rs-5-4-14-february-2020.md
Labels: bug

#715 Added release notes for RedisInsight 1.3.0.
  content/ri/release-notes/v1.3.0.md
Labels: enhancement

#719 Spelling Typo
  content/ri/installing/configurations.md
Labels: typos/format

#709 Update module release notes links
  content/rs/release-notes/rs-5-4-14-february-2020.md
Labels: bug
