Repository RedisLabs/redislabs-docs, pull requests merged in 2020-08, with the labels that each got.

#966 Spelling and grammar check
  content/platforms/release-notes/k8s-6-0-6-6-2020-06.md
  content/ri/installing/install-k8s.md
  content/ri/memory-optimizations.md
  content/rs/administering/access-control/_index.md
  content/rs/administering/cluster-operations/updating-certificates.md
  content/rs/administering/database-operations/creating-database.md
  content/rs/administering/database-operations/importing-data.md
  content/rs/administering/designing-production/networking/multi-ip-ipv6.md
  content/rs/administering/designing-production/networking/port-configurations.md
  content/rs/administering/designing-production/networking/private-public-endpoints.md
  content/rs/administering/designing-production/security/ldap-integration.md
  content/rs/administering/monitoring-metrics/_index.md
  content/rs/administering/monitoring-metrics/prometheus-integration.md
  content/rs/administering/troubleshooting/creating-support-package.md
  content/rs/concepts/compatibility.md
  content/rs/concepts/intercluster-replication.md
  content/rs/concepts/memory-architecture/redis-flash.md
  content/rs/developing/crdbs/strings.md
  content/rs/installing-upgrading/_index.md
  content/rs/installing-upgrading/configuring/configuring-aws-route53-dns-redis-enterprise.md
  content/rs/installing-upgrading/upgrading.md
  content/rs/references/client_references/client_c.md
  content/rs/references/client_references/client_csharp.md
  content/rs/references/client_references/client_java.md
  content/rs/technology-behind-redis-enterprise.md
Labels: infrastructure

#970 End of support ubuntu 14.04 and rhel6
  content/rs/installing-upgrading/supported-platforms.md
Labels: enhancement

#964 Add dropdown for Platforms
  layouts/partials/flex/body-beforecontent.html
  layouts/partials/flex/scripts.html
Labels: infrastructure

#974 Remove quotes for keep_args
  content/modules/add-module-to-cluster.md
Labels: enhancement

#975 Tweak platforms version selector
  layouts/partials/flex/body-beforecontent.html
  layouts/partials/flex/scripts.html
Labels: infrastructure

#976 Update module release notes
  content/modules/redisai/release-notes/redisai-1.0-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.4-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.6-release-notes.md
  content/modules/redisgears/release-notes/redisgraph-1.0-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-2.0-release-notes.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.2-release-notes.md
Labels: enhancement

#982 Fix RedisGraph links
  content/modules/redisgraph/release-notes/redisgraph-2.0-release-notes.md
Labels: bug

#984 Updates to latest 6.0.6-23 release notes
  content/platforms/release-notes/k8s-6-0-6-23-2020-08.md
Labels: enhancement

#971 Updating with new commands from Redis 6
  content/rs/concepts/compatibility.md
Labels: enhancement, security

#985 Updated proxy section
  content/rs/concepts/terminology.md
Labels: bug

#989 DOC-347 Fix links to DNS naming
  content/rs/administering/active-active.md
  content/rs/administering/cluster-operations/adding-node.md
  content/rs/administering/cluster-operations/new-cluster-setup.md
  content/rs/administering/cluster-operations/removing-node.md
  content/rs/administering/cluster-operations/replacing-node.md
  content/rs/administering/troubleshooting/cluster-recovery.md
  content/rs/administering/troubleshooting/testing-client-connectivity.md
  content/rs/installing-upgrading/configuring-aws-instances.md
  content/rs/installing-upgrading/configuring/mdns.md
  content/rs/release-notes/legacy-release-notes/rlec-4-0-june-2015.md
Labels: bug

#940 DOC-302 Add upgrade latest_with_module
  content/modules/add-module-to-cluster.md
  content/rs/installing-upgrading/upgrading.md
Labels: feature, next version

#821 Add ports for encrypted communication
  content/rs/administering/designing-production/networking/port-configurations.md
Labels: enhancement, next version

#959 Add user requirement for CRDB-CLI
  content/rs/references/crdb-cli-reference.md
Labels: enhancement

#994 Revert "Add ports for encrypted communication"
  content/rs/administering/designing-production/networking/port-configurations.md
Labels: bug

#990 Fix inconsistent builds
  layouts/partials/flex/selectnavigation.html
  layouts/partials/menu.html
  layouts/shortcodes/allchildren.html
Labels: infrastructure

#986 DOC-343 Specify on landing page that AI and Gears are RS only
  content/embeds/modules.html
Labels: enhancement
