Repository RedisLabs/redislabs-docs, pull requests merged in 2020-05, with the labels that each got.

#789 6.0 life cycle
  content/rs/administering/product-lifecycle.md
Labels: enhancement

#791 DOC-204 Developing with Active-Active streams
  content/rs/developing/crdbs/_index.md
  content/rs/developing/crdbs/developing-streams-crdb.md
Labels: feature

#803 Fix typo of Shard metric of memory
  content/rs/administering/monitoring-metrics/prometheus-integration.md
Labels: bug

#799 Import page with s3-compatible
  content/rs/administering/database-operations/importing-data.md
Labels: enhancement

#796 Slave HA prerequisites
  content/rs/administering/database-operations/slave-ha.md
Labels: enhancement

#785 PKS: Add output format and improve formatting
  content/platforms/pks/_index.md
Labels: enhancement

#764 Non-existing page for persistence
  content/rs/concepts/data-access/persistence.md
Labels: bug

#751 Emphasize replication for active-active
  content/rs/administering/database-operations/create-active-active.md
Labels: enhancement

#798 DOC-227 Add commands to change inactivity duration
  content/rs/administering/access-control/_index.md
Labels: feature

#797 DOC-183 ACLs for RC
  content/rc/administration/account-team-settings.md
  content/rc/administration/security/_index.md
  content/rc/administration/security/data-access-control.md
  content/rc/administration/security/securing-redis-cloud-connections.md
  content/rc/administration/setup/create-database.md
  content/rc/api/concepts/metrics.md
  content/rc/api/how-to/create-api-keys-for-your-team.md
  content/rc/api/how-to/enable-your-account-to-use-api.md
  content/rc/api/how-to/manage-api-keys.md
  content/rc/api/how-to/view-auditing-using-system-log.md
  content/rc/quick-setup.md
  static/images/rc/icon_add.png
  static/images/rc/icon_save.png
  static/images/rc/icon_view.png
Labels: feature

#806 Add RS 6.0 Release Notes
  content/modules/upgrading-rs.md
  content/rc/administration/account-team-settings.md
  content/rc/how-to/importing-data.md
  content/rs/installing-upgrading/upgrading.md
  content/rs/release-notes/rs-5-4-10-december-2019.md
  content/rs/release-notes/rs-5-4-14-february-2020.md
  content/rs/release-notes/rs-5-6-0-april-2020.md
  content/rs/release-notes/rs-6-0-0-may-2020.md
Labels: feature

#492 Add dynamic tabs shortcode
  content/cheatsheet.md
  content/rs/_index.md
  layouts/partials/flex/scripts.html
  layouts/shortcodes/tab.html
  layouts/shortcodes/tabs.html
  static/css/bootstrap.min.css
  static/js/bootstrap.min.js
  static/theme-flex/script.js
  static/theme-flex/style.css
Labels: infrastructure

#763 Merge with style guide
  content/contribution-guide.md
Labels: infrastructure

#773 Add frontmatter keywords field to search
  content/platforms/kubernetes/kubernetes-logs.md
  layouts/index.json
  static/js/search.js
Labels: infrastructure

#812 Add release note for RedisInsight v1.5
  content/ri/release-notes/v1.5.0.md
Labels: feature

#780 Remove Services Rigger from Kubernetes upgrade
  content/platforms/kubernetes/upgrading-kubernetes-with-operator.md
Labels: bug

#817 Add import icon and update style of procedure
  content/rc/how-to/importing-data.md
  static/images/rc/icon_import.png
Labels: bug

#654 Correct operator release tag
  content/platforms/kubernetes/upgrading-kubernetes-with-operator.md
Labels: bug

#656 Fix kubectl rollout command
  content/platforms/kubernetes/upgrading-kubernetes-with-operator.md
Labels: bug

#757 mDNS Formatting and update link
  content/rs/installing-upgrading/configuring/mdns.md
Labels: bug

#782 Added section on controlling node selection
  content/platforms/kubernetes/pod-scheduling.md
Labels: enhancement

#783 Added a section on pod stability
  content/platforms/kubernetes/stability.md
Labels: enhancement

#805 Style and format for OpenShift
  content/platforms/kubernetes/cluster-options.md
  content/platforms/openshift/getting-started-cli.md
  content/platforms/openshift/getting-started-operatorhub.md
  content/platforms/openshift/quick-start.md
Labels: typos/format

#801 LDAP update
  content/rs/administering/access-control/_index.md
  content/rs/administering/designing-production/security/ldap-integration.md
Labels: enhancement, security

#830 Clarify RedisInsight security recommendation
  content/ri/faqs.md
Labels: bug

#804 RED-41401 Add steps to change support package location
  content/rs/administering/troubleshooting/creating-support-package.md
Labels: enhancement

#820 Fix url for adding database programmatically
  content/ri/using-redisinsight/api.md
Labels: bug

#814 RED-40153 Add new prometheus metrics
  content/rs/administering/monitoring-metrics/prometheus-integration.md
Labels: bug

#832 Add RHEL 7.8 as a supported OS in the supported platforms
  content/rs/installing-upgrading/supported-platforms.md
Labels: enhancement

#829 Improve node shutdown note
  content/rs/administering/cluster-operations/shutting-down-node.md
Labels: enhancement

#849 Upgrade to Hugo 71.1
  .circleci/config.yml
Labels: infrastructure
