Repository RedisLabs/redislabs-docs, pull requests merged in 2020-04, with the labels that each got.

#722 Update links to modules release notes
  content/modules/redisbloom/release-notes/redisbloom-1.1-release-notes.md
  content/modules/redisbloom/release-notes/redisbloom-2.0-release-notes.md
  content/modules/redisbloom/release-notes/redisbloom-2.2-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-1.2-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-2.0-release-notes.md
  content/rs/release-notes/rs-5-4-14-february-2020.md
Labels: bug

#710 Proposing to reference location for socket files in "File Locations"
  content/rs/installing-upgrading/file-locations.md
Labels: enhancement

#718 Add a link to the configuration page
  content/ri/using-redisinsight/troubleshooting.md
Labels: enhancement

#693 RedisInsight docs: Updated instructions to add db
  content/ri/using-redisinsight/add-instance.md
  content/ri/using-redisinsight/api.md
  static/images/ri/add-database-button-screen.png
  static/images/ri/add-db-added-screen.png
  static/images/ri/add-db-cluster-seed-nodes-screen.png
  static/images/ri/add-db-form-screen.png
  static/images/ri/add-db-menu-screen.png
  static/images/ri/add-db-sentinel-form-screen.png
  static/images/ri/add-db-tls-client-auth-screen.png
  static/images/ri/add-db-tls-screen.png
Labels: enhancement, next version

#687 RED-34932 Support for RHEL7.7
  content/rs/installing-upgrading/supported-platforms.md
Labels: feature, next version, ready to merge

#630 RED-34404 Update for OSS cluster in the UI and CRDB
  content/embeds/oss-cluster-api-intro.md
  content/rs/administering/active-active.md
  content/rs/administering/designing-production/networking/using-oss-cluster-api.md
  content/rs/concepts/data-access/oss-cluster-api.md
Labels: feature, next version, ready to merge

#721 Upgrade to 5.6
  content/rs/installing-upgrading/upgrading.md
Labels: feature, next version, ready to merge

#708 RED-38248 Slave HA changes for 5.6
  content/rs/administering/database-operations/slave-ha.md
Labels: feature, next version

#717 RED-37183 Custom user and directories
  content/rs/administering/troubleshooting/cluster-recovery.md
  content/rs/installing-upgrading/_index.md
  content/rs/installing-upgrading/uninstalling.md
Labels: feature, next version

#728 CRDB-CLI for AA with OSS cluster
  content/rs/administering/designing-production/networking/using-oss-cluster-api.md
Labels: enhancement

#422 RED-29897 Add HyperLogLog for CRDB
  content/rs/developing/crdbs/_index.md
  content/rs/developing/crdbs/developing-hashes-crdb.md
  content/rs/developing/crdbs/developing-hll-crdb.md
Labels: enhancement, next version, ready to merge

#730 Slave HA prerequisites
  content/rs/administering/database-operations/slave-ha.md
Labels: feature, next version

#723 Add 5.6 to version menu
  layouts/partials/flex/body-beforecontent.html
  layouts/partials/flex/scripts.html
Labels: infrastructure

#725 5.6 Updates
  content/cheatsheet.md
  content/embeds/backup-locations.md
  content/embeds/oss-cluster-api-intro.md
  content/embeds/tls-configuration-procedure.md
  content/modules/upgrading-rs.md
  content/rs/administering/active-active.md
  content/rs/administering/active-passive.md
  content/rs/administering/database-operations/create-active-active.md
  content/rs/administering/database-operations/create-active-passive.md
  content/rs/administering/database-operations/creating-database.md
  content/rs/administering/database-operations/database-backup.md
  content/rs/administering/database-operations/exporting-data.md
  content/rs/administering/database-operations/slave-ha.md
  content/rs/administering/designing-production/networking/using-oss-cluster-api.md
  content/rs/administering/designing-production/security/tls-configuration.md
  content/rs/administering/troubleshooting/cluster-recovery.md
  content/rs/concepts/data-access/oss-cluster-api.md
  content/rs/developing/crdbs/_index.md
  content/rs/developing/crdbs/developing-hashes-crdb.md
  content/rs/developing/crdbs/developing-hll-crdb.md
  content/rs/getting-started/getting-started-crdbs.md
  content/rs/installing-upgrading/_index.md
  content/rs/installing-upgrading/supported-platforms.md
  content/rs/installing-upgrading/uninstalling.md
  content/rs/installing-upgrading/upgrading.md
  content/rs/release-notes/legacy-release-notes/_index.md
  content/rs/release-notes/legacy-release-notes/redis-enterprise-5.md
  content/rs/release-notes/legacy-release-notes/redis-pack-4-5-0-may-2017.md
  content/rs/release-notes/legacy-release-notes/release-notes-redis-enterprise-software-v5-0-2.md
  content/rs/release-notes/legacy-release-notes/rlec-0-99-5-11-january-2015.md
  content/rs/release-notes/legacy-release-notes/rlec-0-99-february-2015.md
  content/rs/release-notes/legacy-release-notes/rlec-4-0-june-2015.md
  content/rs/release-notes/legacy-release-notes/rlec-4-2-october-2015.md
  content/rs/release-notes/legacy-release-notes/rlec-4-3-aug-2016.md
  content/rs/release-notes/legacy-release-notes/rlec-4-4-dec-2016.md
  content/rs/release-notes/legacy-release-notes/rs-5-2-2-august-2018.md
  content/rs/release-notes/legacy-release-notes/rs-5-2-june-2018.md
  content/rs/release-notes/legacy-release-notes/rs-5-3-beta-july-2018.md
  content/rs/release-notes/rs-5-4-december-2018.md
  content/rs/release-notes/rs-5-6-0-april-2020.md
  static/images/rs/icon_unlocked.png
  static/images/rs/replicaof-certificate.png
  static/images/rs/replicaof-source-url.png
  static/images/rs/replicaof-unencrypted.png
Labels: next version

#739 spelling
  content/rs/administering/designing-production/networking/port-configurations.md
Labels: typos/format

#740 5.6 Release date and EOL
  content/rs/administering/product-lifecycle.md
Labels: enhancement

#741 New module versions
  content/modules/redisbloom/release-notes/redisbloom-2.2-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.4-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.6-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-2.0-release-notes.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.2-release-notes.md
Labels: enhancement, ready to merge

#703 Add expand/collapse all shortcode for FAQ pages
  content/platforms/faqs/_index.md
  content/rc/faqs/_index.md
  content/ri/faqs.md
  content/rs/faqs/_index.md
  layouts/shortcodes/expand-control.html
  layouts/shortcodes/expand.html
  static/theme-flex/script.js
  static/theme-flex/style.css
Labels: infrastructure

#635 Add Connection Source column
  content/rs/administering/designing-production/networking/port-configurations.md
Labels: enhancement

#735 Expand on instructions on persistent storage in RS
  content/rs/administering/designing-production/persistent-ephemeral-storage.md
Labels: enhancement

#738 Redisinsight 1.3.1 release notes
  content/ri/release-notes/v1.3.0.md
Labels: enhancement

#758 Rewrite for feature set version
  content/rs/installing-upgrading/upgrading.md
Labels: feature

#771 Fix broken link to OpenSSL docs
  content/rs/administering/cluster-operations/updating-certificates.md
Labels: bug

#701 Add MEMORY family commands
  content/embeds/compatible-with-oss.md
Labels: enhancement

#756 Extended Apple installation instructions
  content/ri/installing/install-redis-desktop.md
Labels: enhancement

#776 Added release notes for RedisInsight 1.4.0
  content/ri/release-notes/v1.3.0.md
  content/ri/release-notes/v1.4.0.md
Labels: enhancement

#766 RED-35577 Demote master node during maintenance
  content/rs/administering/cluster-operations/maintenance-mode.md
Labels: feature

#778 Add 6.0 version in dropdown
  layouts/partials/flex/body-beforecontent.html
  layouts/partials/flex/scripts.html
Labels: enhancement

#767 DOC-203 Update for S3-compatible storage
  content/embeds/backup-locations.md
Labels: feature

#769 DOC-88 Add ACL configuration options for databases
  content/rs/administering/access-control/_index.md
  content/rs/administering/access-control/user-roles.md
  content/rs/administering/cluster-operations/settings/alerts.md
  content/rs/administering/database-operations/alerting.md
  content/rs/administering/database-operations/create-active-active.md
  content/rs/administering/database-operations/creating-database.md
  content/rs/administering/designing-production/security/ldap-integration.md
  content/rs/release-notes/rs-5-4-2-april-2019.md
Labels: feature

#777 Set What's New for 6.x to draft
  content/rs/new-features-redis-enterprise.md
Labels: enhancement

#779 Updates for RS 6.0
  content/embeds/backup-locations.md
  content/rs/administering/access-control/_index.md
  content/rs/administering/access-control/user-roles.md
  content/rs/administering/cluster-operations/settings/alerts.md
  content/rs/administering/database-operations/alerting.md
  content/rs/administering/database-operations/create-active-active.md
  content/rs/administering/database-operations/creating-database.md
  content/rs/administering/designing-production/security/ldap-integration.md
  content/rs/developing/crdbs/_index.md
  content/rs/developing/crdbs/developing-streams-crdb.md
  content/rs/new-features-redis-enterprise.md
  content/rs/release-notes/rs-5-4-2-april-2019.md
Labels: next version
