Repository RedisLabs/redislabs-docs, pull requests merged in 2020-12, with the labels that each got.

#1122 Fix ioredis and node_redis code fences
  content/rs/references/client_references/client_ioredis.md
  content/rs/references/client_references/client_nodejs.md
Labels: bug

#1128 Verify bdb_egress description
  content/rs/administering/monitoring-metrics/prometheus-metrics-definitions.md
Labels: bug, p_Software

#919 Redis Cloud Security
  content/rc/administration/account-team-settings.md
  content/rc/administration/security/_index.md
  content/rc/administration/setup/create-database.md
  content/rc/api/concepts/authentication-and-authorization.md
  content/rc/api/how-to/create-api-keys-for-your-team.md
  content/rc/api/how-to/enable-your-account-to-use-api.md
  content/rc/api/how-to/manage-api-keys.md
  content/rc/api/how-to/using-curl.md
  content/rc/security/_index.md
  content/rc/security/admin-console-security/_index.md
  content/rc/security/admin-console-security/multi-factor-authentication.md
  content/rc/security/admin-console-security/user-team-management.md
  content/rc/security/database-security/_index.md
  content/rc/security/database-security/encryption-at-rest.md
  content/rc/security/database-security/network-security.md
  content/rc/security/database-security/passwords-users-roles.md
  content/rc/security/database-security/tls-ssl.md
  content/rc/security/shared-responsibility-model.md
  static/images/rc/access-control-security.png
  static/images/rc/build-a-plan.png
  static/images/rc/cancel-update.png
  static/images/rc/cidr-whitelist.png
  static/images/rc/create-custom-subscription.png
  static/images/rc/data-access-control.png
  static/images/rc/default-user-password-reveal.png
  static/images/rc/default-user-password.png
  static/images/rc/edit-db.png
  static/images/rc/edit-password.png
  static/images/rc/enforce-client-auth.png
  static/images/rc/existing-vpc-networking.png
  static/images/rc/icon_delete.png
  static/images/rc/ip-subnet-restrictions.png
  static/images/rc/new-subscription.png
  static/images/rc/persistent-storage-encryption.png
  static/images/rc/pro-ca.png
  static/images/rc/redis-acls.png
  static/images/rc/redis-version-compliance.png
  static/images/rc/source-ip-subnet.png
  static/images/rc/ssl-client-auth.png
  static/images/rc/view-database-extended.png
  static/images/rc/view-db.png
  static/images/rc/view-edit.png
  static/images/rc/vpc-aws.png
  static/images/rc/vpc-gcloud-command.png
  static/images/rc/vpc-gpc.png
Labels: enhancement, p_Cloud

#1116 Update K8s URLs
  content/platforms/kubernetes/cluster-options.md
Labels: bug, p_Platforms

#1125 RED-50124 - Update RCP Cloud Account IAM policy to allow snapshot creation for recovery
  content/rc/how-to/creating-aws-user-redis-enterprise-vpc.md
Labels: enhancement, p_Cloud

#1130 Standardize support link; remove please
  content/contribution-guide.md
  content/modules/redisai/redisai-quickstart.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.0-release-notes.md
  content/platforms/faqs/_index.md
  content/platforms/kubernetes/sizing-kubernetes.md
  content/platforms/release-notes/k8s-5-4-10-8-january-2020.md
  content/platforms/release-notes/k8s-6-0-6-23-2020-08.md
  content/platforms/release-notes/k8s-6-0-6-6-2020-06.md
  content/rc/administration/billing-history.md
  content/rc/how-to/all-memcached-cloud.md
  content/rc/security/admin-console-security/multi-factor-authentication.md
  content/rc/security/database-security/network-security.md
  content/rs/administering/creating-databases/_index.md
  content/rs/administering/troubleshooting/creating-support-package.md
  content/rs/concepts/data-access/consistency-durability.md
  content/rs/installing-upgrading/supported-platforms.md
  content/rs/references/developing-for-active-active/developing-lists-active-active.md
  content/rs/references/developing-for-active-active/developing-sorted-sets-active-active.md
  content/rs/references/rlcheck.md
  content/rs/release-notes/legacy-release-notes/rlec-4-3-aug-2016.md
  content/rs/release-notes/rs-5-4-10-december-2019.md
  content/rs/release-notes/rs-5-4-14-february-2020.md
  content/rs/release-notes/rs-5-4-2-april-2019.md
  content/rs/release-notes/rs-5-4-4-june-2019.md
  content/rs/release-notes/rs-5-4-6-july-2019.md
  content/rs/release-notes/rs-5-4-december-2018.md
  content/rs/release-notes/rs-5-6-0-april-2020.md
Labels: enhancement

#1006 running same OS all nodes
  content/rs/installing-upgrading/supported-platforms.md
Labels: enhancement, in progress, p_Software

#1129 Update RediSearch 2.0, RedisTimeSeries 1.4 and RedisGraph 2.2 release notes
  content/modules/redisearch/release-notes/redisearch-2.0-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-2.2-release-notes.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.4-release-notes.md
Labels: enhancement, p_Modules

#1126 Restructure recovery options to clarify A-A and config recovery
  content/rs/administering/troubleshooting/database-recovery.md
Labels: enhancement, p_Software

#1137 Add load balancer image
  content/rs/installing-upgrading/configuring/cluster-lba-setup.md
  static/images/rs/cluster-behind-load-balancer-top-down.png
Labels: bug, p_Software

#1141 Internet Explorer is EOL
  content/rs/administering/designing-production/supported-clients-browsers.md
Labels: bug, p_Software

#1148 Update to fix sample glitch in 'Using the API'
  content/rc/api/how-to/using-curl.md
  layouts/shortcodes/embed-code2.html
Labels: invalid

#1152 Remove security topics from RC administration
  content/rc/administration/security/data-access-control.md
  content/rc/administration/security/securing-redis-cloud-connections.md
Labels: bug, p_Cloud

#1145 Added release notes for RedisInsight v1.8.2.
  content/ri/release-notes/v1.8.0.md
Labels: enhancement, p_Insight

#1153 DOC-421 Add aliases for removed security topics
  content/rc/security/database-security/passwords-users-roles.md
  content/rc/security/database-security/tls-ssl.md
Labels: bug, p_Cloud

#1157 Fix bad formatting of code snippets
  content/rc/api/how-to/create-and-manage-cloud-accounts.md
  content/rc/api/how-to/create-and-manage-databases.md
  content/rc/api/how-to/using-curl.md
Labels: bug, typos/format

#1154 Reorganization of K8s
  content/platforms/faqs/_index.md
  content/platforms/kubernetes/_index.md
  content/platforms/kubernetes/concepts/_index.md
  content/platforms/kubernetes/concepts/architecture.md
  content/platforms/kubernetes/concepts/db-controller.md
  content/platforms/kubernetes/concepts/logs.md
  content/platforms/kubernetes/concepts/managing-images.md
  content/platforms/kubernetes/concepts/node-selection.md
  content/platforms/kubernetes/concepts/operator.md
  content/platforms/kubernetes/concepts/persistent-volumes.md
  content/platforms/kubernetes/concepts/sizing-on-kubernetes.md
  content/platforms/kubernetes/concepts/stability.md
  content/platforms/kubernetes/getting-started/_index.md
  content/platforms/kubernetes/getting-started/openshift/_index.md
  content/platforms/kubernetes/getting-started/openshift/getting-started-openshift-crdb.md
  content/platforms/kubernetes/getting-started/openshift/openshift-cli.md
  content/platforms/kubernetes/getting-started/openshift/openshift-operatorhub.md
  content/platforms/kubernetes/getting-started/openshift/quick-start.md
  content/platforms/kubernetes/getting-started/tanzu/_index.md
  content/platforms/kubernetes/reference/_index.md
  content/platforms/kubernetes/reference/cluster-options.md
  content/platforms/kubernetes/reference/db-options.md
  content/platforms/kubernetes/tasks/_index.md
  content/platforms/kubernetes/tasks/cluster-recovery.md
  content/platforms/kubernetes/tasks/upgrading-with-operator.md
  content/platforms/pcf/_index.md
  content/platforms/release-notes/k8s-5-4-10-8-january-2020.md
  content/platforms/release-notes/k8s-6-0-6-11-2020-07.md
  content/platforms/release-notes/k8s-6-0-6-23-2020-08.md
  content/platforms/release-notes/k8s-6-0-6-24-2020-08.md
  content/platforms/release-notes/k8s-6-0-6-6-2020-06.md
  content/platforms/release-notes/k8s-6-0-8-1-2020-10.md
  content/platforms/release-notes/k8s-6-0-8-20-2020-12.md
  content/rs/administering/troubleshooting/cluster-recovery.md
Labels: enhancement, p_Platforms

#1151 DOC-425 Update RediSearch release notes 2.0.4 and 2.0.5
  content/modules/redisearch/release-notes/redisearch-2.0-release-notes.md
Labels: enhancement, p_Modules

#1140 Add Redisinsight helmchart
  content/ri/installing/install-k8s.md
  static/pkgs/redisinsight-chart-0.1.0.tgz
Labels: enhancement, p_Insight

#1139 [RedisInsight] Add description about CLI keybindings
  content/ri/using-redisinsight/cli.md
  static/images/ri/cli-keybindings.png
Labels: enhancement, p_Insight

#1161 Add database name in active-passive
  content/rs/administering/creating-databases/create-active-passive.md
Labels: bug, p_Software

#1136 Proper directory for uninstall script
  content/rs/installing-upgrading/uninstalling.md
Labels: enhancement, p_Software

#1132 Replace sharding term in clustering article
  content/rc/concepts/clustering.md
  content/rs/_index.md
  content/rs/concepts/high-availability/clustering.md
  content/rs/concepts/terminology.md
  content/rs/references/crdb-cli-reference.md
Labels: enhancement, p_Software

#1124 Note OS's that are no longer supported
  content/rs/installing-upgrading/supported-platforms.md
Labels: bug, p_Software

#1119 Update example for supported cipher
  content/rs/administering/cluster-operations/updating-certificates.md
Labels: bug, p_Software

#1165 Add RedisGraph 2.2.10 and 2.2.11
  content/modules/redisgraph/release-notes/redisgraph-2.2-release-notes.md
Labels: enhancement, p_Modules

#1162 Added release notes for RedisInsight 1.8.3.
  content/ri/release-notes/v1.8.0.md
Labels: enhancement, p_Insight

#1164 Add procedure for adding module with REST API
  content/modules/add-module-to-cluster.md
Labels: enhancement, p_Software

#1134 Writing style review on clustering
  content/rc/concepts/clustering.md
Labels: enhancement, p_Software
