Repository RedisLabs/redislabs-docs, pull requests merged in 2020-07, with the labels that each got.

#905 Fixed Typo
  content/rs/installing-upgrading/upgrading.md
Labels: typos/format

#904 Update RI docker command
  config.toml
Labels: enhancement

#878 Performance optimisation
  layouts/partials/flex/head.html
  layouts/partials/flex/scripts.html
  layouts/partials/footer.html
  static/images/glassdoor.svg
  static/images/instagram.svg
  static/js/search.js
  static/theme-flex/script.js
Labels: infrastructure

#906 Fix typo in try it out output
  content/rs/administering/database-operations/create-active-active.md
  content/rs/getting-started/creating-database/redis-flash.md
  content/rs/getting-started/docker/getting-started-docker.md
  content/rs/getting-started/getting-started-crdbs.md
  content/rs/getting-started/quick-setup.md
Labels: typos/format

#907 Fix "get" response
  content/rs/administering/database-operations/create-active-active.md
  content/rs/getting-started/creating-database/redis-flash.md
  content/rs/getting-started/docker/getting-started-docker.md
  content/rs/getting-started/getting-started-crdbs.md
  content/rs/getting-started/quick-setup.md
Labels: typos/format

#908 Remove unnecessary comment from RedisInsight
  content/ri/using-redisinsight/java-serialized-objects.md
Labels: typos/format

#877 Consolidate getting started articles
  content/platforms/kubernetes/_index.md
  content/platforms/kubernetes/redis-enterprise.yaml
  content/rs/getting-started/_index.md
  content/rs/getting-started/creating-database/_index.md
  content/rs/getting-started/docker/_index.md
  content/rs/getting-started/getting-started-active-active.md
  content/rs/getting-started/getting-started-docker.md
  content/rs/getting-started/getting-started-redis-flash.md
  content/rs/getting-started/memtier-benchmark.md
  content/rs/getting-started/quick-setup.md
  content/rs/installing-upgrading/_index.md
  content/rs/installing-upgrading/supported-platforms.md
  content/rs/references/memtier-benchmark.md
  content/rs/release-notes/rs-5-5-preview-april-2019.md
  layouts/partials/rs-hot-topics-table.html
Labels: enhancement

#913 Copy edit
  content/embeds/modules.html
  content/ri/using-redisinsight/memory-analysis.md
  content/rs/_index.md
  content/rs/developing/crdbs/_index.md
Labels: enhancement

#916 Fix note rendering for several notes
  content/embeds/tryout-redisai.md
  content/modules/redisai/_index.md
  content/modules/redisgears/release-notes/redisgraph-1.0-release-notes.md
  content/platforms/release-notes/k8s-6-0-6-6-2020-06.md
  content/rs/developing/crdbs/developing-streams-crdb.md
  content/rs/getting-started/getting-started-docker.md
Labels: infrastructure

#910 Tweak goldmark renderer config to render linebreaks in tables
  config.toml
Labels: infrastructure

#914 Update references to future storage services
  content/rs/_index.md
  content/rs/administering/database-operations/database-backup.md
Labels: bug

#900 Issue-889 Reorg Redis optimizations in RI
  content/ri/faqs.md
  content/ri/memory-optimizations.md
  content/ri/memory-optimizations/_index.md
  content/ri/memory-optimizations/avoid-dynamic-lua-script.md
  content/ri/memory-optimizations/combine-smaller-strings-to-hash.md
  content/ri/memory-optimizations/compress-field-names.md
  content/ri/memory-optimizations/compress-values.md
  content/ri/memory-optimizations/convert-hash-to-ziplist.md
  content/ri/memory-optimizations/convert-to-list-instead-of-hash.md
  content/ri/memory-optimizations/enable-compression-for-list.md
  content/ri/memory-optimizations/reclaim-expired-keys-memory-faster.md
  content/ri/memory-optimizations/shard-big-hash-to-small-hash.md
  content/ri/memory-optimizations/switch-set-to-intset.md
  content/ri/memory-optimizations/switch-to-32-bits.md
  content/ri/memory-optimizations/switch-to-bloom-filters.md
  content/ri/memory-optimizations/upgrade-redis-version.md
  content/ri/memory-optimizations/use-better-serializer.md
  content/ri/memory-optimizations/use-smaller-keys.md
  content/ri/release-notes/_index.md
Labels: enhancement

#896 DOC-174 Update modules essentials
  content/cheatsheet.md
  content/embeds/tryout-redisbloom.md
  content/embeds/tryout-redisearch.md
  content/modules/_index.md
  content/modules/modules-quickstart.md
  content/modules/redisbloom/redisbloom-quickstart.md
  content/modules/redisearch/redisearch-quickstart.md
  content/modules/redisgraph/redisgraph-quickstart.md
  content/modules/redisjson/redisjson-quickstart.md
  content/modules/redistimeseries/redistimeseries-quickstart.md
  content/rc/administration/setup/create-database.md
  content/rc/rc-quickstart.md
  static/images/rc/new-cloud-database-modules.png
  static/images/rc/new-free-cloud-subscription.png
Labels: feature

#915 Revise technical overview
  content/rs/technology-behind-redis-enterprise.md
Labels: enhancement

#924 Fix k8s broken image
  content/platforms/kubernetes/upgrading-kubernetes-with-operator.md
  static/images/rs/kubernetes-rolling-updates-done.png
Labels: bug

#917 Fix command to turn off swap
  content/rs/installing-upgrading/configuring/linux-swap.md
Labels: bug

#925 Fix python output for connection test
  content/rs/getting-started/_index.md
  content/rs/getting-started/getting-started-docker.md
  content/rs/getting-started/getting-started-redis-flash.md
Labels: bug

#926 Only first reference to RS has full term
  content/rs/administering/_index.md
  content/rs/administering/access-control/_index.md
  content/rs/administering/access-control/user-roles.md
  content/rs/administering/active-active.md
  content/rs/administering/active-passive.md
  content/rs/administering/cluster-operations/adding-node.md
  content/rs/administering/cluster-operations/cluster-metrics.md
  content/rs/administering/cluster-operations/maintenance-mode.md
  content/rs/administering/cluster-operations/settings/license-keys.md
  content/rs/administering/database-operations/create-active-active.md
  content/rs/administering/database-operations/create-active-passive.md
  content/rs/administering/database-operations/creating-database.md
  content/rs/administering/database-operations/importing-data.md
  content/rs/administering/database-operations/updating-configurations.md
  content/rs/administering/designing-production/networking/port-configurations.md
  content/rs/administering/designing-production/networking/private-public-endpoints.md
  content/rs/administering/designing-production/networking/using-oss-cluster-api.md
  content/rs/administering/designing-production/security/tls-configuration.md
  content/rs/administering/monitoring-metrics/nagios-plugin.md
  content/rs/administering/product-lifecycle.md
  content/rs/administering/troubleshooting/cluster-recovery.md
  content/rs/concepts/compatibility.md
  content/rs/concepts/data-access/oss-cluster-api.md
  content/rs/concepts/high-availability/rack-zone-awareness.md
  content/rs/concepts/memory-architecture/memory-management.md
  content/rs/concepts/terminology.md
  content/rs/developing/crdbs/_index.md
  content/rs/developing/crdbs/strings.md
  content/rs/faqs/_index.md
  content/rs/getting-started/_index.md
  content/rs/getting-started/getting-started-active-active.md
  content/rs/getting-started/getting-started-docker.md
  content/rs/installing-upgrading/configuring/change-location-socket-files.md
  content/rs/new-features-redis-enterprise.md
Labels: typos/format

#923 Cloud api update database
  content/rc/api/how-to/update-databases.md
  static/code/rv/api/create-subscription-basic.json
Labels: enhancement

#932 Fix typo in syntax
  content/rs/installing-upgrading/_index.md
Labels: typos/format

#938 Fix links to instructions for TLS on Replica Of
  content/embeds/tls-configuration-procedure.md
  content/rs/administering/designing-production/security/tls-configuration.md
Labels: typos/format

#928 Replace CRDB with Active-Active terminology
  content/platforms/openshift/getting-started-openshift-crdb.md
  content/rc/api/how-to/update-databases.md
  content/ri/using-redisinsight/auto-discover-databases.md
  content/rs/administering/active-active.md
  content/rs/administering/active-passive.md
  content/rs/administering/cluster-operations/replacing-node.md
  content/rs/administering/cluster-operations/updating-certificates.md
  content/rs/administering/database-operations/administering-database-operations-importing-data.md
  content/rs/administering/database-operations/causal-consistency-crdb.md
  content/rs/administering/database-operations/create-active-active.md
  content/rs/administering/database-operations/create-active-passive.md
  content/rs/administering/database-operations/creating-database.md
  content/rs/administering/database-operations/database-backup.md
  content/rs/administering/database-operations/delete-crdb.md
  content/rs/administering/database-operations/deleting-database.md
  content/rs/administering/database-operations/eviction-policy.md
  content/rs/administering/database-operations/exporting-data.md
  content/rs/administering/database-operations/flush-db-crdb.md
  content/rs/administering/database-operations/slave-ha.md
  content/rs/administering/database-operations/updating-configurations.md
  content/rs/administering/designing-production/networking/using-oss-cluster-api.md
  content/rs/administering/designing-production/performance/shard-placement.md
  content/rs/administering/designing-production/security/tls-configuration.md
  content/rs/administering/designing-production/synchronizing-clocks.md
  content/rs/administering/logging/rsyslog-logging.md
  content/rs/administering/monitoring-metrics/definitions.md
  content/rs/administering/monitoring-metrics/prometheus-integration.md
  content/rs/administering/troubleshooting/_index.md
  content/rs/administering/troubleshooting/database-recovery.md
  content/rs/administering/troubleshooting/replicaof-repeatedly-fails.md
  content/rs/concepts/data-access/oss-cluster-api.md
  content/rs/concepts/intercluster-replication.md
  content/rs/developing/crdbs/_index.md
  content/rs/developing/crdbs/developing-hashes-crdb.md
  content/rs/developing/crdbs/developing-hll-crdb.md
  content/rs/developing/crdbs/developing-lists-crdb.md
  content/rs/developing/crdbs/developing-sets-crdb.md
  content/rs/developing/crdbs/developing-sorted-sets-crdb.md
  content/rs/developing/crdbs/strings.md
  content/rs/getting-started/getting-started-active-active.md
  content/rs/installing-upgrading/configuring/mdns.md
  content/rs/installing-upgrading/file-locations.md
  content/rs/installing-upgrading/upgrading.md
  content/rs/new-features-redis-enterprise.md
  content/rs/release-notes/legacy-release-notes/redis-enterprise-5.md
  content/rs/release-notes/legacy-release-notes/release-notes-redis-enterprise-software-v5-0-2.md
  content/rs/release-notes/legacy-release-notes/rs-5-2-2-august-2018.md
Labels: enhancement

#944 Add release notes for 1.6.2 and 1.6.3
  content/ri/release-notes/v1.6.0.md
Labels: enhancement

#950 Update v1.6.0.md from typo
  content/ri/release-notes/v1.6.0.md
Labels: typos/format

#953 Fix anchor links when relref shortcode is used
  content/cheatsheet.md
  content/embeds/create-subscription-next-steps.md
  content/embeds/tls-configuration-procedure.md
  content/platforms/faqs/_index.md
  content/rc/administration/setup/create-database.md
  content/rc/api/concepts/tasks-management.md
  content/rc/api/how-to/backup-and-import-databases.md
  content/rc/api/how-to/create-and-manage-databases.md
  content/rc/api/how-to/update-databases.md
  content/rc/rc-quickstart.md
  content/ri/using-redisinsight/auto-discover-databases.md
  content/rs/administering/database-operations/create-active-active.md
  content/rs/administering/database-operations/create-active-passive.md
  content/rs/administering/database-operations/creating-database.md
  content/rs/administering/database-operations/updating-configurations.md
  content/rs/administering/designing-production/networking/using-oss-cluster-api.md
  content/rs/administering/designing-production/security/ldap-integration.md
  content/rs/administering/designing-production/security/tls-configuration.md
  content/rs/administering/designing-production/synchronizing-clocks.md
  content/rs/concepts/memory-architecture/redis-flash.md
  content/rs/developing/crdbs/_index.md
  content/rs/installing-upgrading/configuring/cluster-dns.md
  content/rs/installing-upgrading/upgrading.md
  content/rs/references/client_references/client_drupal.md
  content/rs/release-notes/rs-5-4-10-december-2019.md
  content/rs/release-notes/rs-5-4-14-february-2020.md
  content/rs/release-notes/rs-5-4-2-april-2019.md
  content/rs/release-notes/rs-5-4-6-july-2019.md
  content/rs/release-notes/rs-5-6-0-april-2020.md
  content/rs/release-notes/rs-6-0-may-2020.md
Labels: infrastructure

#939 Fix RedisInsight license link
  content/ri/faqs.md
Labels: bug

#858 Merge metrics into single section
  content/rs/administering/cluster-operations/cluster-metrics.md
  content/rs/administering/cluster-operations/node-metrics.md
  content/rs/administering/cluster-operations/removing-node.md
  content/rs/administering/cluster-operations/settings/alerts.md
  content/rs/administering/database-operations/alerting.md
  content/rs/administering/database-operations/creating-database.md
  content/rs/administering/database-operations/metrics/_index.md
  content/rs/administering/database-operations/metrics/database-metrics.md
  content/rs/administering/database-operations/metrics/shard-metrics.md
  content/rs/administering/monitoring-metrics/_index.md
  content/rs/administering/monitoring-metrics/console-metrics-definitions.md
  content/rs/administering/monitoring-metrics/nagios-plugin.md
  content/rs/administering/monitoring-metrics/prometheus-integration.md
  content/rs/administering/monitoring-metrics/prometheus-metrics-definitions.md
  content/rs/concepts/memory-architecture/redis-flash.md
  static/images/rs/icon_warning.png
Labels: enhancement

#948 Added cluster role and binding for rack awareness
  content/platforms/kubernetes/pod-scheduling.md
Labels: enhancement

#957 Add CRDB-CLI Commands
  content/rs/references/_index.md
  content/rs/references/crdb-cli-reference.md
Labels: enhancement
