Repository RedisLabs/redislabs-docs, pull requests merged in 2020-11, with the labels that each got.

#1051 DOC-353 Add article for password rotation
  content/rs/administering/access-control/password-rotation.md
Labels: feature

#1074 DOC-354 Disable services to save resources
  content/rs/administering/troubleshooting/disabling-services.md
Labels: feature

#1085 Remove "IP address" from Participating Clusters section
  content/rs/administering/creating-databases/create-active-active.md
Labels: enhancement

#1077 Fix FT.CREATE example and add example for document scoring
  content/embeds/tryout-redisearch-2.md
Labels: bug

#1047 Broken link pointed to K8s examples folder
  content/platforms/openshift/getting-started-cli.md
Labels: bug

#1095 tiny formattting
  content/rs/administering/cluster-operations/replacing-node.md
Labels: typos/format

#1103 Update AWS terminology
  content/rs/installing-upgrading/_index.md
  content/rs/installing-upgrading/configuring-aws-instances.md
  content/rs/references/memtier-benchmark.md
Labels: p_Software, typos/format

#1091 Improve enable and disable OSS Cluster API
  content/rs/administering/designing-production/networking/using-oss-cluster-api.md
Labels: enhancement, p_Software

#1104 Custom installation with same user/group IDs
  content/rs/installing-upgrading/_index.md
Labels: enhancement, p_Software

#1093 Specify VPC peering not for Essentials
  content/rc/administration/setup/edit-subscription.md
Labels: enhancement, p_Cloud

#1090 DOC-383 multi-key commands in CRDB
  content/rs/concepts/high-availability/clustering.md
Labels: enhancement, p_Software

#1052 DOC-352 Replace NGINX with Envoy
  content/embeds/cluster-setup.md
  content/ri/using-redisinsight/troubleshooting.md
  content/rs/administering/designing-production/networking/port-configurations.md
  content/rs/release-notes/legacy-release-notes/redis-pack-4-5-0-may-2017.md
  content/rs/release-notes/rs-5-4-10-december-2019.md
  content/rs/release-notes/rs-5-4-4-june-2019.md
Labels: blocked, feature, p_Software

#1040 Clarify need for default password
  content/rs/administering/creating-databases/_index.md
Labels: enhancement, p_Software

#1069 Add RedisInsight logging level
  content/ri/installing/configurations.md
Labels: next version, p_Insight

#1075 Adds a client page for Node.js with ioredis
  content/rs/references/client_references/client_ioredis.md
Labels: enhancement, p_Software

#1099 Update module release notes (RediSearch and RedisTimeSeries)
  content/modules/redisearch/release-notes/redisearch-2.0-release-notes.md
  content/modules/redisgears/release-notes/redisgraph-1.0-release-notes.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.4-release-notes.md
Labels: enhancement, p_Modules

#1096 Improve Active-Active docker
  content/embeds/docker-memory-limitation.md
  content/rs/getting-started/getting-started-active-active.md
  content/rs/getting-started/getting-started-docker.md
  static/images/rs/crdb-activate.png
Labels: enhancement, p_Software

#1092 Update notes to markdown style
  content/cheatsheet.md
  content/embeds/cluster-setup.md
  content/modules/redisgraph/release-notes/redisgraph-2.0-release-notes.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.2-release-notes.md
  content/platforms/kubernetes/_index.md
  content/platforms/kubernetes/kubernetes-persistent-volumes.md
  content/platforms/openshift/getting-started-openshift-crdb.md
  content/rc/administration/configuration/monitoring-performance.md
  content/rc/concepts/clustering.md
  content/rc/concepts/data-persistence.md
  content/ri/release-notes/archive/v0.9.39.md
  content/ri/using-redisinsight/profiler.md
  content/rs/administering/cluster-operations/removing-node.md
  content/rs/administering/cluster-operations/replacing-node.md
  content/rs/administering/creating-databases/create-active-active.md
  content/rs/administering/database-operations/memory-limit.md
  content/rs/administering/designing-production/networking/multi-ip-ipv6.md
  content/rs/administering/designing-production/networking/multiple-active-proxy.md
  content/rs/administering/designing-production/security/client-connections.md
  content/rs/administering/designing-production/security/tls-configuration.md
  content/rs/administering/monitoring-metrics/console-metrics-definitions.md
  content/rs/administering/new-cluster-setup.md
  content/rs/administering/troubleshooting/testing-client-connectivity.md
  content/rs/concepts/data-access/persistence.md
  content/rs/concepts/high-availability/clustering.md
  content/rs/concepts/high-availability/rack-zone-awareness.md
  content/rs/concepts/high-availability/replication.md
  content/rs/getting-started/_index.md
  content/rs/getting-started/getting-started-active-active.md
  content/rs/getting-started/getting-started-docker.md
  content/rs/getting-started/getting-started-redis-flash.md
  content/rs/installing-upgrading/configuring-aws-instances.md
  content/rs/installing-upgrading/configuring/cluster-dns.md
  content/rs/references/developing-for-active-active/developing-strings-active-active.md
  content/rs/release-notes/legacy-release-notes/release-notes-redis-enterprise-software-v5-0-2.md
Labels: typos/format

#1089 Added clarification for GCP Marketplace customers.
  content/rc/api/how-to/create-and-manage-subscriptions.md
Labels: enhancement, p_Cloud

#1106 [RI-568] Restrict visualization of keys when size exceed a certain limit.
  content/ri/using-redisinsight/browser.md
  static/images/ri/browser.png
Labels: p_Insight

#1102 Add RedisInsight v1.8 release notes
  content/ri/release-notes/v1.8.0.md
Labels: feature, p_Insight

#1098 [RI-616][RI-617] Add description about new CA certificate feature and RI's ability to auto fill database form when connection string is pasted
  content/ri/using-redisinsight/add-instance.md
  static/images/ri/add-db-form-screen.png
  static/images/ri/add-db-tls-ca-cert-screen.png
  static/images/ri/add-db-tls-client-auth-screen.png
  static/images/ri/add-db-tls-screen.png
Labels: p_Insight

#1037 [RI-212] Document new environment variables and their deprecation status.
  content/ri/installing/configurations.md
Labels: blocked, feature, p_Insight

#1105 Added "Managing Container Images" section (DockerHub rate limiting)
  content/platforms/kubernetes/managing-images.md
Labels: enhancement, p_Platforms

#1044 Remove note to add index name as tag in RCE
  content/embeds/tryout-redisearch-2.md
Labels: enhancement, p_Cloud

#1062 Refreshes the node_redis client page.
  content/rs/references/client_references/client_nodejs.md
Labels: enhancement, p_Software

#1079 Setting Up a Cluster Behind a Load Balancer
  content/rs/installing-upgrading/configuring/cluster-lba-setup.md
Labels: enhancement, p_Software

#1113 Add `--network host` option for Docker container
  content/rs/getting-started/getting-started-docker.md
Labels: enhancement, p_Software

#1112 Improve warning that Docker is not for production
  content/rs/getting-started/getting-started-docker.md
Labels: enhancement, p_Software

#1114 Remove region limitation for modules in RC
  content/modules/modules-quickstart.md
Labels: feature, p_Cloud, p_Modules

#1118 Improve TLS description
  content/rs/administering/creating-databases/create-active-active.md
Labels: enhancement
