Repository RedisLabs/redislabs-docs, pull requests merged in 2020-09, with the labels that each got.

#1000 DOC-324 Update Grafana JSON templates
  static/code/rs/cluster.json
  static/code/rs/database.json
  static/code/rs/node.json
Labels: bug

#993 Update design of header and footer
  content/_header.md
  layouts/partials/flex/body-beforecontent.html
  layouts/partials/footer.html
  layouts/partials/home/options.html
  layouts/partials/navigation.html
  static/css/nucleus.css
  static/fonts/graphik/Graphik-Light-Web.woff
  static/fonts/graphik/Graphik-Light-Web.woff2
  static/fonts/graphik/Graphik-Medium-Web.woff
  static/fonts/graphik/Graphik-Medium-Web.woff2
  static/fonts/graphik/Graphik-Regular-Web.woff
  static/fonts/graphik/Graphik-Regular-Web.woff2
  static/fonts/graphik/Graphik-Semibold-Web.woff
  static/fonts/graphik/Graphik-Semibold-Web.woff2
  static/images/fb.png
  static/images/gd.png
  static/images/icon-redis.svg
  static/images/icon_logo/logo-redis-2.svg
  static/images/ig.png
  static/images/in.png
  static/images/yt.png
  static/theme-flex/img/RedisLabs_Homepage_Getstarted_Cloud.svg
  static/theme-flex/img/RedisLabs_Homepage_Getstarted_Software.svg
  static/theme-flex/img/ico-cloud-pro.svg
  static/theme-flex/img/ico-cloud.svg
  static/theme-flex/img/ico-modules.svg
  static/theme-flex/img/ico-platforms.svg
  static/theme-flex/img/ico-redisai.svg
  static/theme-flex/img/ico-redisbloom.svg
  static/theme-flex/img/ico-redisearch.svg
  static/theme-flex/img/ico-redisgears.svg
  static/theme-flex/img/ico-redisgraph.svg
  static/theme-flex/img/ico-redisinsight.svg
  static/theme-flex/img/ico-redisjson.svg
  static/theme-flex/img/ico-redistimeseries.svg
  static/theme-flex/img/ico-software.svg
  static/theme-flex/script.js
  static/theme-flex/style.css
Labels: infrastructure

#963 Improve tagging in RediSearch Quick Start
  content/embeds/tryout-redisearch.md
Labels: invalid

#1013 DOC-334 Add new shard metrics
  content/rs/administering/monitoring-metrics/prometheus-metrics-definitions.md
Labels: enhancement

#1020 Add RediSearch 1.6.14 release notes
  content/modules/redisearch/release-notes/redisearch-1.6-release-notes.md
Labels: enhancement

#1004 Update client_c.md
  content/rs/references/client_references/client_c.md
Labels: bug

#1019 Search experiment
  layouts/partials/home/hero.html
  redislabs-docs.iml
  static/css/autocomplete.css
  static/js/autocomplete.js
  static/js/search.js
Labels: enhancement, infrastructure

#1015 Add procedure for upgrading to RediSearch 2.x
  content/modules/redisearch/redisearch-2-upgrade.md
Labels: enhancement, next version

#1016 DOC-345 Update RediSearch overview, Quick Start, and add Active-Active
  content/embeds/tryout-redisearch-2.md
  content/embeds/tryout-redisearch.md
  content/modules/redisearch/_index.md
  content/modules/redisearch/redisearch-active-active.md
  content/modules/redisearch/redisearch-quickstart.md
Labels: enhancement, next version

#1002 Update backup instructions for GCP
  content/embeds/backup-locations.md
Labels: bug

#1042 Add GDPR modal
  layouts/partials/flex/scripts.html
  layouts/partials/footer.html
Labels: infrastructure

#1036 [RI-508] Add RedisInsight k8s deployment with service example.
  content/ri/installing/install-k8s.md
Labels: enhancement

#1022 Update healthcheck information in the docs
  content/ri/installing/install-docker.md
  content/ri/installing/install-k8s.md
Labels: enhancement

#1021 Add Active-Active create step to verify participating clusters
  content/rs/administering/creating-databases/create-active-active.md
Labels: enhancement

#1045 Update icons on modules landing page
  content/embeds/modules.html
  layouts/partials/home/options.html
  static/theme-flex/img/ico-redisai.svg
  static/theme-flex/img/ico-redisbloom.svg
  static/theme-flex/img/ico-redisearch.svg
  static/theme-flex/img/ico-redisgears.svg
  static/theme-flex/img/ico-redisgraph.svg
  static/theme-flex/img/ico-redisjson.svg
  static/theme-flex/img/ico-redistimeseries.svg
  static/theme-flex/img/icon-redis-ai.svg
  static/theme-flex/img/icon-redis-bloom.svg
  static/theme-flex/img/icon-redis-gears.svg
  static/theme-flex/img/icon-redis-graph.svg
  static/theme-flex/img/icon-redis-json.svg
  static/theme-flex/img/icon-redis-timeseries.svg
  static/theme-flex/img/icon-redisearch.svg
Labels: enhancement

#991 Added note to release notes about rolling update
  content/platforms/release-notes/k8s-6-0-6-23-2020-08.md
Labels: enhancement

#1046 RedisJSON 1.0.5 release notes
  content/modules/redisjson/release-notes/redisjson-1.0-release-notes.md
Labels: enhancement

#1050 Fix CRDB-GUID syntax
  content/rs/administering/designing-production/networking/using-oss-cluster-api.md
  content/rs/administering/import-export/flush-db-crdb.md
  content/rs/installing-upgrading/upgrading.md
  content/rs/references/crdb-cli-reference.md
Labels: bug
