Repository RedisLabs/redislabs-docs, pull requests merged in 2020-06, with the labels that each got.

#848 DOC-258 Rewrite, merge create and edit, update with IAM role
  content/rc/how-to/creating-aws-user-redis-enterprise-vpc.md
  content/rc/how-to/creating-cloud-account.md
  content/rc/how-to/view-edit-cloud-account.md
  layouts/shortcodes/video.html
  static/images/rc/add_user.png
  static/images/rc/attach_policies.png
  static/images/rc/create-cluster-node-role.mp4
  static/images/rc/create-console-access-role.mp4
  static/images/rc/create-instance-role-policy.mp4
  static/images/rc/create-instance-user-policy.mp4
  static/images/rc/create-programmatic-user.mp4
  static/images/rc/create_policy-1.png
  static/images/rc/create_role.png
  static/images/rc/review_role_policy.png
  static/images/rc/review_user_policy.png
  static/images/rc/select_access_type.png
  static/images/rc/select_service.png
  static/images/rc/set_permissions.png
Labels: feature

#826 Add dates for module releases
  content/modules/redisbloom/release-notes/redisbloom-1.0-release-notes.md
  content/modules/redisbloom/release-notes/redisbloom-1.1-release-notes.md
  content/modules/redisbloom/release-notes/redisbloom-2.0-release-notes.md
  content/modules/redisbloom/release-notes/redisbloom-2.2-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.0-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.1-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.2-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.4-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.6-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-1.0-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-1.2-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-2.0-release-notes.md
  content/modules/redisjson/release-notes/redisjson-1.0-release-notes.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.0-release-notes.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.2-release-notes.md
Labels: enhancement

#856 DOC-269 Update header and footer of docs site to match redislabs.com
  layouts/partials/flex/body-beforecontent.html
  layouts/partials/footer.html
Labels: infrastructure

#859 Update RI FAQ
  content/ri/faqs.md
Labels: bug

#870 Put keywords field in lunr search index again
  static/js/search.js
Labels: bug

#794 DOC-175 Add RedisAI
  content/embeds/modules.html
  content/embeds/tryout-redisai.md
  content/modules/redisai/_index.md
  content/modules/redisai/redisai-quickstart.md
  content/modules/redisai/release-notes/_index.md
  content/modules/redisai/release-notes/redisai-1.0-release-notes.md
  static/images/modules/graph.pb.png
  static/images/modules/tensor-A-2-3.png
  static/images/modules/tensor-B-3-5.png
  static/images/modules/tensor-model.png
  static/theme-flex/img/ico-redisai.svg
Labels: feature

#813 WIP: Active-Active streams edits
  content/rs/developing/crdbs/developing-streams-crdb.md
  static/css/nucleus.css
Labels: feature

#876 Update Create S3
  content/rc/administration/configuration/backups.md
Labels: in progress

#885 RedisInsight strong admin password
  content/ri/faqs.md
Labels: enhancement, ready to merge

#884 DOC-282 Change microseconds to seconds for latency metrics
  content/rs/administering/monitoring-metrics/prometheus-integration.md
Labels: bug, ready to merge

#881 DOC-256 RedisGears installation instructions
  content/embeds/modules.html
  content/modules/_index.md
  content/modules/add-module-to-cluster.md
  content/modules/add-module-to-database.md
  content/modules/packaging-modules.md
  content/modules/redisai/redisai-quickstart.md
  content/modules/redisbloom/redisbloom-quickstart.md
  content/modules/redisearch/redisearch-quickstart.md
  content/modules/redisgears/_index.md
  content/modules/redisgears/installing-redisgears.md
  content/modules/redisgears/redisgears-quickstart.md
  content/modules/redisgears/write-behind.md
  content/modules/redisgraph/redisgraph-quickstart.md
  content/modules/redisjson/redisjson-quickstart.md
  content/modules/redistimeseries/redistimeseries-quickstart.md
  content/rs/release-notes/rs-5-4-10-december-2019.md
  content/rs/release-notes/rs-5-4-14-february-2020.md
  content/rs/release-notes/rs-5-4-2-april-2019.md
  content/rs/release-notes/rs-5-4-6-july-2019.md
  content/rs/release-notes/rs-5-4-december-2018.md
  content/rs/release-notes/rs-5-6-0-april-2020.md
  content/rs/release-notes/rs-6-0-may-2020.md
Labels: feature, ready to merge

#879 Add links to RC documentation on how to get Account/Secret Key
  content/ri/using-redisinsight/auto-discover-databases.md
Labels: enhancement, ready to merge

#873 Fix link in create-and-manage-databases.md
  content/rc/api/how-to/create-and-manage-databases.md
Labels: ready to merge, typos/format

#882 Update Create S3
  content/rc/administration/configuration/backups.md
  static/images/rc/add_s3_user.png
  static/images/rc/add_user_existing.png
  static/images/rc/new-bucket.png
Labels: enhancement

#867 RI 1.6 - Release note
  content/ri/release-notes/archive/_index.md
  content/ri/release-notes/v1.0.0.md
  content/ri/release-notes/v1.1.0.md
  content/ri/release-notes/v1.2.0.md
  content/ri/release-notes/v1.3.0.md
  content/ri/release-notes/v1.4.0.md
  content/ri/release-notes/v1.5.0.md
  content/ri/release-notes/v1.6.0.md
Labels: ready to merge

#890 making installation version agnostic
  content/modules/redisgears/installing-redisgears.md
Labels: enhancement

#871 Fix formatting in creating-database.md
  content/rs/administering/database-operations/creating-database.md
Labels: typos/format

#880 FT.ADDHASH is not supported in Redis Enterprise
  content/modules/redisearch/_index.md
Labels: bug

#895 Prevent OS from using Redis ports
  content/rs/installing-upgrading/_index.md
Labels: enhancement
