Repository RedisLabs/redislabs-docs, pull requests merged in 2021-05, with the labels that each got.

#1336 update 6.0.20 cipher example
  content/rs/administering/cluster-operations/updating-certificates.md
Labels: p_Software

#1356 Jira-DOC-700: RC: "Manage subscriptions" page: "Delete subscription" link doesn't work.
  content/rc/subscriptions/_index.md
Labels: p_Cloud

#1355 Update password-rotation.md
  content/rs/administering/access-control/password-rotation.md
Labels: p_Software

#1360 Added a note about the /v2/module endpoint for RS
  content/modules/add-module-to-cluster.md
Labels: p_Modules

#1381 DOC-684 add cluster config services to disabling services
  content/rs/administering/troubleshooting/disabling-services.md
  content/rs/references/rladmin.md
Labels: p_Software
