Repository RedisLabs/redislabs-docs, pull requests merged in 2021-11, with the labels that each got.

#1639 Update upgrade-redis-cluster.md
  content/kubernetes/re-clusters/upgrade-redis-cluster.md
Labels: K8s

#1640 Update cluster-recovery.md
  content/kubernetes/re-clusters/cluster-recovery.md
Labels: K8s

#1638 Changes for October 2021
  changelog.md
Labels: infrastructure

#1642 Update abbreviation TKGIE to TKGI
  content/kubernetes/deployment/tanzu/_index.md
  content/kubernetes/release-notes/k8s-6-0-20-12-2021-07.md
  content/kubernetes/release-notes/k8s-6-2-4-1-2021-09.md
Labels: K8s

#1643 DOC-965 correct image name in release notes
  content/kubernetes/release-notes/k8s-6-2-4-1-2021-09.md
Labels: K8s

#1647 Edited RS maintenance mode article
  content/rs/administering/cluster-operations/maintenance-mode.md
  content/rs/references/rest-api/requests/nodes/actions.md
Labels: p_Software

#1631 Edited rsyslog logging, events, and alerts
  content/rs/administering/logging/_index.md
  content/rs/administering/logging/rsyslog-logging.md
  content/rs/administering/logging/rsyslog-logging/_index.md
  content/rs/administering/logging/rsyslog-logging/bdb-events.md
  content/rs/administering/logging/rsyslog-logging/cluster-events.md
  content/rs/administering/logging/rsyslog-logging/node-events.md
  content/rs/administering/logging/rsyslog-logging/user-events.md
Labels: p_Software

#1646 Doc-896 clarify databaseSecretName in REDB options
  content/kubernetes/reference/db-options.md
  content/kubernetes/security/manage_certificates.md
Labels: K8s

#1645 Doc-935 add redisUpgradePolicy to REC options
  content/kubernetes/reference/cluster-options.md
  content/kubernetes/reference/db-options.md
Labels: next version, K8s

#1644 Doc-919 add databasePort to database options
  content/kubernetes/reference/db-options.md
Labels: next version, K8s

#1648 Doc-900 K8s Heart of gold release updates
  changelog.md
  content/kubernetes/deployment/tanzu/_index.md
  content/kubernetes/deployment/using-kustomize.md
  content/kubernetes/re-clusters/cluster-recovery.md
  content/kubernetes/re-clusters/upgrade-redis-cluster.md
  content/kubernetes/reference/cluster-options.md
  content/kubernetes/reference/db-options.md
  content/kubernetes/reference/supported_k8s_distributions.md
  content/kubernetes/release-notes/k8s-6-0-20-12-2021-07.md
  content/kubernetes/release-notes/k8s-6-0-6-11-2020-07.md
  content/kubernetes/release-notes/k8s-6-2-4-1-2021-09.md
  content/kubernetes/release-notes/k8s-6-2-8-tbd-2021-11.md
Labels: next version, K8s

#1614 K8s Heart of Gold release branch
  content/kubernetes/deployment/using-kustomize.md
  content/kubernetes/re-clusters/cluster-recovery.md
  content/kubernetes/reference/cluster-options.md
  content/kubernetes/reference/db-options.md
  content/kubernetes/reference/supported_k8s_distributions.md
  content/kubernetes/release-notes/k8s-6-0-6-11-2020-07.md
  content/kubernetes/release-notes/k8s-6-2-8-tbd-2021-11.md
Labels: next version, K8s

#1649 K8S: Updating RN index page and removing TBD from filename.
  content/kubernetes/release-notes/_index.md
  content/kubernetes/release-notes/k8s-6-2-8-2-2021-11.md
Labels: p_Platforms, K8s

#1651 Update db-options.md
  content/kubernetes/reference/db-options.md
Labels: K8s

#1653 Added redirects for PDF 404 status codes
  utilities/redirect_pdfs/pdf_redirects.json
  website.json
Labels: infrastructure

#1654 K8s release notes image name clarification
  content/kubernetes/release-notes/k8s-6-2-8-2-2021-11.md
Labels: K8s

#1555 Doc-838 Create AA database on K8s
  content/kubernetes/deployment/openshift/openshift-cli.md
  content/kubernetes/re-clusters/create-aa-database.md
  content/kubernetes/re-databases/set-up-ingress-controller.md
Labels: K8s

#1660 Allow custom front matter fields in table-children shortcode
  content/rs/release-notes/_index.md
  content/rs/release-notes/legacy-release-notes/_index.md
  content/rs/release-notes/rs-5-6-0-april-2020.md
  content/rs/release-notes/rs-6-0-12-january-2021.md
  content/rs/release-notes/rs-6-0-20-april-2021.md
  content/rs/release-notes/rs-6-0-8-september-2020.md
  content/rs/release-notes/rs-6-0-may-2020.md
  content/rs/release-notes/rs-6-2-4-august-2021.md
  content/rs/release-notes/rs-6-2-8-october-2021.md
  layouts/shortcodes/table-children.html
Labels: enhancement

#1656 Jira DOC-983: Predis client connection SSL statement is out-of-date
  content/rs/references/client_references/client_php.md
Labels: p_Software

#1662 Added article last updated date
  config.toml
  layouts/partials/pdf-prep-recursive.html
  layouts/partials/pdf-prep-single.html
  layouts/partials/post-bottom.html
  layouts/partials/recursive-children.html
  static/theme-flex/style.css
Labels: infrastructure

#1668 Update module release notes
  content/modules/redisai/redisai-quickstart.md
  content/modules/redisai/release-notes/_index.md
  content/modules/redisai/release-notes/redisai-1.0-release-notes.md
  content/modules/redisai/release-notes/redisai-1.2-release-notes.md
  content/modules/redisbloom/release-notes/_index.md
  content/modules/redisbloom/release-notes/redisbloom-1.0-release-notes.md
  content/modules/redisbloom/release-notes/redisbloom-1.1-release-notes.md
  content/modules/redisbloom/release-notes/redisbloom-2.0-release-notes.md
  content/modules/redisbloom/release-notes/redisbloom-2.2-release-notes.md
  content/modules/redisearch/release-notes/_index.md
  content/modules/redisearch/release-notes/redisearch-1.0-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.1-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.2-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.4-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.6-release-notes.md
  content/modules/redisearch/release-notes/redisearch-2.0-release-notes.md
  content/modules/redisearch/release-notes/redisearch-2.2-release-notes.md
  content/modules/redisgears/release-notes/_index.md
  content/modules/redisgears/release-notes/redisgears-1.0-release-notes.md
  content/modules/redisgraph/release-notes/_index.md
  content/modules/redisgraph/release-notes/redisgraph-1.0-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-1.2-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-2.0-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-2.2-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-2.4-release-notes.md
  content/modules/redisjson/release-notes/_index.md
  content/modules/redisjson/release-notes/redisjson-1.0-release-notes.md
  content/modules/redisjson/release-notes/redisjson-2.0-release-notes.md
  content/modules/redistimeseries/release-notes/_index.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.0-release-notes.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.2-release-notes.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.4-release-notes.md
Labels: p_Modules

#1676 Update v2.0.2.md
  content/ri/release-notes/v2.0.2.md
Labels: p_Insight

#1682 Added RedisGears v1.0.8 release notes
  content/modules/redisgears/release-notes/redisgears-1.0-release-notes.md
Labels: p_Modules
