Repository RedisLabs/redislabs-docs, pull requests merged in 2021-08, with the labels that each got.

#1484 Jira DOC-852: RC - Import Data is missing a redirect
  content/rc/databases/import-data.md
Labels: p_Cloud

#1486 Doc 851 log-collector script instructions
  content/platforms/kubernetes/tasks/run-log-collector-script.md
Labels: K8s

#1476 Doc-734 k8s ingress
  content/platforms/kubernetes/tasks/set-up-ingress-controller.md
Labels: K8s

#1500 Jira DOC-864: Use of "region" and "zone" is confusing.
  content/rc/databases/configuration/high-availability.md
Labels: p_Cloud

#1511 RS: Release 6.2.4 docs: Incorporating latest feedback ahead of release.
  content/rs/installing-upgrading/upgrading.md
  content/rs/references/rladmin.md
  content/rs/security/internode-encryption.md
  static/images/rs/internode-encryption.png
Labels: p_Software

#1416 update mDNS for rhel8
  content/rs/installing-upgrading/configuring/mdns.md
Labels: p_Software, RS6.2.8

#1517 DOC-871 fix broken links
  content/platforms/kubernetes/concepts/node-selection.md
  content/platforms/kubernetes/concepts/sizing-on-kubernetes.md
  content/platforms/kubernetes/getting-started/openshift/openshift-operatorhub.md
  content/platforms/kubernetes/getting-started/openshift/quick-start.md
  content/platforms/kubernetes/getting-started/quick-start.md
  content/platforms/kubernetes/getting-started/tanzu/_index.md
  content/platforms/kubernetes/reference/cluster-options.md
  content/platforms/kubernetes/tasks/replica-of-k8s.md
Labels: K8s
