Repository RedisLabs/redislabs-docs, pull requests merged in 2021-12, with the labels that each got.

#1694 Jira DOC-1039: Clarify RC support for modules
  content/modules/_index.md
  content/modules/enterprise-capabilities.md
  content/rc/databases/create-database.md
Labels: p_Modules

#1693 Example for using a persistent volume claim
  content/ri/installing/install-k8s.md
Labels: p_Insight, K8s

#1698 Removed duplicate RedisGraph quick start example
  content/modules/redisgraph/redisgraph-quickstart.md
Labels: p_Modules

#1700 Jira DOC-1029: Modules - Broken image link in RediSearch 2.0 release notes
  content/modules/redisearch/release-notes/redisearch-2.0-release-notes.md
  static/images/modules/redisearch-2-0-architecture.png
Labels: p_Modules

#1699 RS REST API: Remove references to Swift in batch operation objects.
  content/rs/references/rest-api/objects/bdb/backup_location.md
  content/rs/references/rest-api/objects/bdb/dataset_import_sources.md
Labels: p_Software

#1692 Jira DOC-1013: Add DB and cluster version minimums to release notes for each module.
  content/modules/redisai/release-notes/_index.md
  content/modules/redisai/release-notes/redisai-1.0-release-notes.md
  content/modules/redisai/release-notes/redisai-1.2-release-notes.md
  content/modules/redisbloom/release-notes/_index.md
  content/modules/redisbloom/release-notes/redisbloom-1.0-release-notes.md
  content/modules/redisbloom/release-notes/redisbloom-1.1-release-notes.md
  content/modules/redisbloom/release-notes/redisbloom-2.0-release-notes.md
  content/modules/redisbloom/release-notes/redisbloom-2.2-release-notes.md
  content/modules/redisearch/release-notes/_index.md
  content/modules/redisearch/release-notes/redisearch-1.0-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.1-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.2-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.4-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.6-release-notes.md
  content/modules/redisearch/release-notes/redisearch-2.0-release-notes.md
  content/modules/redisearch/release-notes/redisearch-2.2-release-notes.md
  content/modules/redisgears/release-notes/_index.md
  content/modules/redisgears/release-notes/redisgears-1.0-release-notes.md
  content/modules/redisgraph/release-notes/_index.md
  content/modules/redisgraph/release-notes/redisgraph-1.0-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-1.2-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-2.0-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-2.2-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-2.4-release-notes.md
  content/modules/redisjson/release-notes/_index.md
  content/modules/redisjson/release-notes/redisjson-1.0-release-notes.md
  content/modules/redisjson/release-notes/redisjson-2.0-release-notes.md
  content/modules/redistimeseries/release-notes/_index.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.0-release-notes.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.2-release-notes.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.4-release-notes.md
Labels: p_Modules

#1675 K8s: revise openshift cli getting started
  content/kubernetes/deployment/openshift/openshift-cli.md
Labels: K8s

#1709 The prefix for the ssl-passthrough annotation in the case of HAProxy …
  content/kubernetes/re-databases/set-up-ingress-controller.md
Labels: bug, K8s

#1710 Updated the annotations as the prefix in the case of HAProxy Ingress …
  content/kubernetes/re-clusters/create-aa-database.md
Labels: bug, K8s

#1708 Removed the HAproxy Ingress installation link
  content/kubernetes/re-databases/set-up-ingress-controller.md
Labels: bug, K8s

#1706 DOC-1075 updates to SCC scope
  content/kubernetes/deployment/openshift/openshift-cli.md
  content/kubernetes/deployment/quick-start.md
Labels: K8s

#1712 Added RedisJSON v2.0.6 release notes
  content/modules/redisjson/release-notes/redisjson-2.0-release-notes.md
Labels: p_Modules

#1711 Revised RediSearch quick start
  content/modules/modules-quickstart.md
  content/modules/redisearch/redisearch-quickstart.md
Labels: p_Modules

#1714 K8s broken links
  content/kubernetes/deployment/quick-start.md
Labels: K8s

#1717 DOC-1044: RC - Add shard descriptions to Create Flexible topic
  content/rc/subscriptions/create-flexible-subscription.md
  static/theme-flex/style.css
Labels: p_Cloud

#1715 Added article about using modules with RedisInsight
  content/ri/using-redisinsight/modules.md
  static/images/ri/command-helper-details.png
  static/images/ri/command-helper-search.png
  static/images/ri/command-helper.png
  static/images/ri/enabled-modules.png
  static/images/ri/icon-command-helper.png
  static/images/ri/icon-more-info.png
  static/images/ri/icon-redisai.png
  static/images/ri/icon-redisbloom.png
  static/images/ri/icon-redisearch.png
  static/images/ri/icon-redisgears.png
  static/images/ri/icon-redisgraph.png
  static/images/ri/icon-redisjson.png
  static/images/ri/icon-redistimeseries.png
  static/images/ri/icon-run-command.png
  static/images/ri/icon-workbench.png
  static/images/ri/output-redisearch-info.png
  static/images/ri/quick-guide-index-json.png
Labels: p_Insight

#1721 Jira DOC-1010: Update eviction policy descriptions
  content/rc/databases/configuration/data-eviction-policies.md
  content/rs/administering/database-operations/eviction-policy.md
Labels: p_Software, p_Cloud

#1722 Jira DOC-889: RS - Redirect older link to Remove a faulty node
  content/rs/administering/cluster-operations/replacing-node.md
Labels: p_Software
