Repository RedisLabs/redislabs-docs, pull requests merged in 2021-03, with the labels that each got.

#1171 DOC-390 Add data eviction to Active-Active database creation procedure
  content/rs/administering/creating-databases/_index.md
  content/rs/administering/creating-databases/create-active-active.md
  content/rs/administering/database-operations/eviction-policy.md
Labels: feature, p_Software

#1123 DOC-405 Revamp getting started and installation
  content/embeds/adding-node-embed.md
  content/embeds/cluster-dns-embed.md
  content/embeds/hardware-requirements-embed.md
  content/embeds/new-cluster-embed.md
  content/embeds/port-configurations-embed.md
  content/embeds/supported-platforms-embed.md
  content/rs/administering/adding-node.md
  content/rs/administering/designing-production/hardware-requirements.md
  content/rs/administering/designing-production/networking/port-configurations.md
  content/rs/administering/new-cluster-setup.md
  content/rs/getting-started/_index.md
  content/rs/installing-upgrading/_index.md
  content/rs/installing-upgrading/configuring/cluster-dns.md
  content/rs/installing-upgrading/supported-platforms.md
Labels: enhancement, in progress, p_Software

#1255 Update hardware-requirements-embed.md
  content/embeds/hardware-requirements-embed.md
Labels: bug, p_Software

#1208 DOC-525 Migrate to Active-Active with Replica Of
  content/rs/administering/creating-databases/create-active-passive.md
  content/rs/administering/database-operations/migrate-to-active-active.md
  static/images/rs/A-A_migration.png
  static/images/rs/Migration_using_Replica_Of_complete.png
  static/images/rs/icon_sync_green.png
Labels: feature, p_Software

#1034 Active-Active Region Application Failover
  content/rs/references/developing-for-active-active/region-application-failover-active-active.md
  static/images/rs/slot_to_keys.py
Labels: enhancement, p_Software
