Repository RedisLabs/redislabs-docs, pull requests merged in 2021-10, with the labels that each got.

#1564 DOC-930 update aliases to correct 404
  content/platforms/kubernetes/deployment/openshift/_index.md
  content/platforms/kubernetes/deployment/openshift/openshift-cli.md
  content/platforms/kubernetes/deployment/openshift/openshift-operatorhub.md
Labels: K8s

#1628 Jira DOC-857: RS - v6.2.8 Release notes
  .circleci/config.yml
  content/modules/enterprise-capabilities.md
  content/rs/administering/designing-production/networking/private-public-endpoints.md
  content/rs/release-notes/_index.md
  content/rs/release-notes/legacy-release-notes/_index.md
  content/rs/release-notes/rs-5-5-preview-april-2019.md
  content/rs/release-notes/rs-5-6-0-april-2020.md
  content/rs/release-notes/rs-6-0-12-january-2021.md
  content/rs/release-notes/rs-6-0-20-april-2021.md
  content/rs/release-notes/rs-6-0-8-september-2020.md
  content/rs/release-notes/rs-6-0-may-2020.md
  content/rs/release-notes/rs-6-2-4-august-2021.md
  content/rs/release-notes/rs-6-2-8-october-2021.md
  layouts/shortcodes/table-children.html
Labels: p_Software

#1615 Jira DOC-881: RC - Update REST API docs to reflect new UX
  content/rc/api/get-started/_index.md
  content/rc/api/get-started/enable-the-api.md
  content/rc/api/get-started/manage-api-keys.md
  static/images/rc/access-management-api-keys-tab.png
  static/images/rc/access-management-api-user-key-delete.png
  static/images/rc/access-management-create-user-key.png
  static/images/rc/access-management-delete-api-secret-key.png
  static/images/rc/access-management-team-tab.png
  static/images/rc/access-management-user-key-add.png
  static/images/rc/access-management-user-key-manage-cidr.png
  static/images/rc/button-access-management-add.png
  static/images/rc/button-access-management-api-key-copy.png
  static/images/rc/button-access-management-api-user-key-delete.png
  static/images/rc/button-access-management-api-user-key-finish.png
  static/images/rc/button-access-management-cidr-rule-add.png
  static/images/rc/button-access-management-cidr-rule-delete.png
  static/images/rc/button-access-management-cidr-rule-edit.png
  static/images/rc/button-access-management-cidr-rule-save.png
  static/images/rc/button-access-management-enable-api.png
  static/images/rc/button-access-management-hide-key.png
  static/images/rc/button-access-management-show-key.png
  static/images/rc/button-access-management-user-key-cancel.png
  static/images/rc/button-access-management-user-key-create.png
Labels: p_Cloud
