Repository RedisLabs/redislabs-docs, pull requests merged in 2021-07, with the labels that each got.

#1426 Jira DOC-792: RedisGears missing release notes for 1.0.6 & 1.0.5
  content/modules/add-module-to-cluster.md
  content/modules/add-module-to-database.md
  content/modules/modules-lifecycle.md
  content/modules/packaging-modules.md
  content/modules/redisai/_index.md
  content/modules/redisai/redisai-quickstart.md
  content/modules/redisai/release-notes/_index.md
  content/modules/redisai/release-notes/redisai-1.0-release-notes.md
  content/modules/redisbloom/_index.md
  content/modules/redisbloom/redisbloom-quickstart.md
  content/modules/redisbloom/release-notes/_index.md
  content/modules/redisbloom/release-notes/redisbloom-1.0-release-notes.md
  content/modules/redisbloom/release-notes/redisbloom-1.1-release-notes.md
  content/modules/redisbloom/release-notes/redisbloom-2.0-release-notes.md
  content/modules/redisbloom/release-notes/redisbloom-2.2-release-notes.md
  content/modules/redisearch/_index.md
  content/modules/redisearch/redisearch-2-upgrade.md
  content/modules/redisearch/redisearch-active-active.md
  content/modules/redisearch/redisearch-quickstart.md
  content/modules/redisearch/release-notes/_index.md
  content/modules/redisearch/release-notes/redisearch-1.0-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.1-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.2-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.4-release-notes.md
  content/modules/redisearch/release-notes/redisearch-1.6-release-notes.md
  content/modules/redisearch/release-notes/redisearch-2.0-release-notes.md
  content/modules/redisgears/_index.md
  content/modules/redisgears/installing-redisgears.md
  content/modules/redisgears/redisgears-quickstart.md
  content/modules/redisgears/release-notes/_index.md
  content/modules/redisgears/release-notes/redisgears-1.0-release-notes.md
  content/modules/redisgears/write-behind.md
  content/modules/redisgraph/redisgraph-quickstart.md
  content/modules/redisgraph/release-notes/_index.md
  content/modules/redisgraph/release-notes/redisgraph-1.0-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-1.2-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-2.0-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-2.2-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-2.4-release-notes.md
  content/modules/redisjson/_index.md
  content/modules/redisjson/redisjson-quickstart.md
  content/modules/redisjson/release-notes/_index.md
  content/modules/redisjson/release-notes/redisjson-1.0-release-notes.md
  content/modules/redistimeseries/_index.md
  content/modules/redistimeseries/redistimeseries-quickstart.md
  content/modules/redistimeseries/release-notes/_index.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.0-release-notes.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.2-release-notes.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.4-release-notes.md
Labels: p_Modules

#1429 Jira DOC-793: RS: Link in Active-active entry page points to wrong article.
  content/rs/references/developing-for-active-active/_index.md
  content/rs/references/developing-for-active-active/developing-hashes-active-active.md
  content/rs/references/developing-for-active-active/developing-hll-active-active.md
  content/rs/references/developing-for-active-active/developing-lists-active-active.md
  content/rs/references/developing-for-active-active/developing-sets-active-active.md
  content/rs/references/developing-for-active-active/developing-sorted-sets-active-active.md
  content/rs/references/developing-for-active-active/developing-streams-active-active.md
  content/rs/references/developing-for-active-active/developing-strings-active-active.md
  content/rs/references/developing-for-active-active/region-application-failover-active-active.md
  content/rs/references/memtier-benchmark.md
Labels: p_Software

#1430 Jira DOC-791: RS: The LDAP section of "Authentication & authorization" is out-of-date
  content/rs/security/admin-console-security/user-security.md
Labels: p_Software

#1438 DOC-776 k8s glossary terms
  content/glossary/_index.md
Labels: K8s

#1444 K8s release notes edits
  content/platforms/release-notes/_index.md
  content/platforms/release-notes/k8s-5-4-10-8-january-2020.md
  content/platforms/release-notes/k8s-5-4-14-2-2020-03.md
Labels: K8s

#1445 Jira DOC-807: RC - Update references to out-of-date plan names.
  content/rc/how-to/view-edit-cloud-account.md
  content/rc/security/database-security/network-security.md
Labels: p_Cloud

#1449 added warning for persistent volume size
  content/platforms/kubernetes/concepts/persistent-volumes.md
Labels: K8s

#1451 DOC-775 K8s support matrix, new article
  content/platforms/kubernetes/reference/supported_k8s_distributions.md
Labels: K8s

#1459 Jira DOC-784: Remove {{expand}} from K8s FAQs
  content/platforms/faqs/_index.md
Labels: p_Platforms

#1460 Jira DOC-826: RS - Assorted typos/glitches in (and near) "Install and setup"
  content/rs/administering/import-export/exporting-data.md
  content/rs/concepts/_index.md
  content/rs/installing-upgrading/_index.md
  content/rs/installing-upgrading/configuring/_index.md
  content/rs/installing-upgrading/configuring/centos-rhel-7-firewall.md
  content/rs/installing-upgrading/configuring/configuring-aws-route53-dns-redis-enterprise.md
  content/rs/installing-upgrading/file-locations.md
  content/rs/installing-upgrading/supported-platforms.md
  content/rs/installing-upgrading/uninstalling.md
  content/rs/installing-upgrading/upgrading.md
  content/rs/technology-behind-redis-enterprise.md
Labels: p_Software

#1465 Jira DOC-834: RS - Fix 404 error in Database maintenance page
  content/rs/administering/database-operations/_index.md
  content/rs/security/_index.md
Labels: p_Software

#1466 Doc 781 Manage REC credentials procedure
  content/platforms/kubernetes/concepts/manage_REC_credentials.md
Labels: K8s

#1454 Jira DOC-760: RC - Finish reorganizing Concepts content.
  content/glossary/_index.md
  content/rc/administration/aws-zone-mapping.md
  content/rc/administration/configuration/_index.md
  content/rc/administration/multiple-accounts.md
  content/rc/administration/setup/change-plan.md
  content/rc/cloud-accounts/_index.md
  content/rc/cloud-accounts/iam-resources/_index.md
  content/rc/cloud-accounts/iam-resources/aws-console.md
  content/rc/cloud-accounts/iam-resources/cloudformation.md
  content/rc/cloud-accounts/iam-resources/terraform.md
  content/rc/concepts/_index.md
  content/rc/concepts/data-persistence.md
  content/rc/databases/_index.md
  content/rc/databases/configuration/_index.md
  content/rc/databases/configuration/clustering.md
  content/rc/databases/configuration/data-eviction-policies.md
  content/rc/databases/configuration/data-persistence.md
  content/rc/databases/configuration/high-availability.md
  content/rc/databases/create-database.md
  content/rc/databases/flush-data.md
  content/rc/how-to/all-memcached-cloud.md
  content/rc/how-to/creating-iam-resources/_index.md
  content/rc/how-to/creating-iam-resources/terraform.md
  content/rc/how-to/multiple-accounts.md
  content/rc/how-to/view-edit-cloud-account.md
  content/rc/rc-quickstart.md
  content/rc/security/database-security/encryption-at-rest.md
  content/rc/subscriptions/create-flexible-subscription.md
  content/rc/subscriptions/view-flexible-subscription.md
  content/rs/administering/designing-production/networking/using-oss-cluster-api.md
  layouts/partials/home/options.html
  layouts/partials/mini-toc.html
  static/images/rc/redisinsight-cli-flushall-example.png
Labels: p_Cloud

#1471 Updated info on REC password and editorial changes
  content/platforms/faqs/_index.md
Labels: K8s

#1472 Jira DOC-843: Remove {{expands}} from RS & RI FAQs
  content/rc/administration/_index.md
  content/rc/how-to/_index.md
  content/ri/faqs.md
  content/rs/faqs/_index.md
Labels: p_Insight, p_Software

#1087 Update give Cloud access to a GCP user
  content/rc/administration/account-team-settings.md
Labels: bug, p_Cloud
