Repository RedisLabs/redislabs-docs, pull requests merged in 2021-01, with the labels that each got.

#1158 Reorganization of K8s to getting started, concepts, tasks, and reference
  content/platforms/faqs/_index.md
  content/platforms/kubernetes/_index.md
  content/platforms/kubernetes/concepts/_index.md
  content/platforms/kubernetes/concepts/architecture.md
  content/platforms/kubernetes/concepts/db-controller.md
  content/platforms/kubernetes/concepts/logs.md
  content/platforms/kubernetes/concepts/managing-images.md
  content/platforms/kubernetes/concepts/node-selection.md
  content/platforms/kubernetes/concepts/operator.md
  content/platforms/kubernetes/concepts/persistent-volumes.md
  content/platforms/kubernetes/concepts/sizing-on-kubernetes.md
  content/platforms/kubernetes/concepts/stability.md
  content/platforms/kubernetes/getting-started/_index.md
  content/platforms/kubernetes/getting-started/openshift/_index.md
  content/platforms/kubernetes/getting-started/openshift/getting-started-openshift-crdb.md
  content/platforms/kubernetes/getting-started/openshift/openshift-cli.md
  content/platforms/kubernetes/getting-started/openshift/openshift-operatorhub.md
  content/platforms/kubernetes/getting-started/openshift/quick-start.md
  content/platforms/kubernetes/getting-started/tanzu/_index.md
  content/platforms/kubernetes/reference/_index.md
  content/platforms/kubernetes/reference/cluster-options.md
  content/platforms/kubernetes/reference/db-options.md
  content/platforms/kubernetes/tasks/_index.md
  content/platforms/kubernetes/tasks/cluster-recovery.md
  content/platforms/kubernetes/tasks/upgrading-with-operator.md
  content/platforms/pcf/_index.md
  content/platforms/release-notes/k8s-5-4-10-8-january-2020.md
  content/platforms/release-notes/k8s-6-0-6-11-2020-07.md
  content/platforms/release-notes/k8s-6-0-6-23-2020-08.md
  content/platforms/release-notes/k8s-6-0-6-24-2020-08.md
  content/platforms/release-notes/k8s-6-0-6-6-2020-06.md
  content/platforms/release-notes/k8s-6-0-8-1-2020-10.md
  content/platforms/release-notes/k8s-6-0-8-20-2020-12.md
  content/rs/administering/troubleshooting/cluster-recovery.md
Labels: enhancement, p_Platforms

#1168 rhel7.9 support
  content/rs/installing-upgrading/supported-platforms.md
Labels: enhancement, p_Software

#1169 Minor fixes to Creating Database
  content/rs/administering/creating-databases/_index.md
Labels: p_Software, typos/format

#1142 It is important to specify what is the image for the Bootstrapper
  content/platforms/release-notes/k8s-6-0-8-20-2020-12.md
Labels: enhancement, p_Platforms

#1008 An initial set of K8s guides under a new topic of 'Developer Guides'
  content/platforms/kubernetes/tasks/cluster-recovery.md
  content/platforms/kubernetes/tasks/ldap-on-k8s.md
  content/platforms/kubernetes/tasks/replica-of-k8s.md
  content/platforms/kubernetes/tasks/upgrading-with-operator.md
  content/platforms/kubernetes/tasks/using-kustomnize.md
Labels: enhancement, p_Platforms

#1007 Added a quick start guide for generic K8s
  content/platforms/kubernetes/getting-started/quick-start.md
Labels: enhancement, p_Platforms

#1180 DOC-438 5.4 end of life updates
  content/platforms/release-notes/k8s-5-4-10-8-january-2020.md
  content/rs/administering/product-lifecycle.md
  content/rs/installing-upgrading/upgrading.md
  content/rs/release-notes/legacy-release-notes/rs-5-4-10-december-2019.md
  content/rs/release-notes/legacy-release-notes/rs-5-4-14-february-2020.md
  content/rs/release-notes/legacy-release-notes/rs-5-4-2-april-2019.md
  content/rs/release-notes/legacy-release-notes/rs-5-4-4-june-2019.md
  content/rs/release-notes/legacy-release-notes/rs-5-4-6-july-2019.md
  content/rs/release-notes/legacy-release-notes/rs-5-4-december-2018.md
  content/rs/release-notes/rs-5-6-0-april-2020.md
  content/rs/release-notes/rs-6-0-8-september-2020.md
Labels: enhancement, p_Software

#1081 6.0.12 features
  content/embeds/cluster-setup.md
  content/modules/add-module-to-cluster.md
  content/modules/redisgears/installing-redisgears.md
  content/ri/using-redisinsight/troubleshooting.md
  content/rs/administering/access-control/password-rotation.md
  content/rs/administering/designing-production/networking/port-configurations.md
  content/rs/administering/troubleshooting/disabling-services.md
  content/rs/references/crdb-cli-reference.md
  content/rs/release-notes/legacy-release-notes/redis-pack-4-5-0-may-2017.md
  content/rs/release-notes/legacy-release-notes/rs-5-2-june-2018.md
  content/rs/release-notes/legacy-release-notes/rs-5-4-10-december-2019.md
  content/rs/release-notes/legacy-release-notes/rs-5-4-4-june-2019.md
  content/rs/release-notes/rs-6-0-12-january-2021.md
Labels: next version

#1178 Fix reference to DB in rladmin command line
  content/rs/concepts/data-access/persistence.md
Labels: bug, p_Software

#1179 Spelling Correction of GEORADIUSBYMEMBER command
  content/rs/concepts/high-availability/clustering.md
Labels: p_Software, typos/format

#1184 Fix warning formatting
  content/rs/administering/access-control/password-rotation.md
Labels: p_Software, typos/format

#1173 DOC-440 K8s guides for 'Developer Guides'
  content/platforms/kubernetes/tasks/cluster-recovery.md
  content/platforms/kubernetes/tasks/ldap-on-k8s.md
  content/platforms/kubernetes/tasks/replica-of-k8s.md
  content/platforms/kubernetes/tasks/upgrading-with-operator.md
  content/platforms/kubernetes/tasks/using-kustomnize.md
Labels: enhancement, p_Platforms

#1197 Fix : Command segments formatting
  content/rs/administering/designing-production/security/client-connections.md
Labels: customer_request, typos/format

#1202 DOC-513 Add -X POST to password rotation command
  content/rs/administering/access-control/password-rotation.md
Labels: bug, p_Software

#1199 Add RedisAI 1.0.2 and RedisGraph 1.0.3 RNs
  content/modules/redisai/release-notes/redisai-1.0-release-notes.md
  content/modules/redisgears/release-notes/redisgears-1.0-release-notes.md
Labels: enhancement, p_Modules

#1182 Restart client after updating certificates
  content/rs/administering/cluster-operations/updating-certificates.md
Labels: bug, p_Software

#962 Fix typo for importing data from Redis
  content/rc/how-to/importing-data.md
Labels: bug, p_Cloud

#1209 Add OSS API cluster to DB creation
  content/rs/administering/creating-databases/_index.md
  content/rs/administering/creating-databases/create-active-active.md
Labels: enhancement, p_Software

#883 Updated microsoft blobs
  content/rc/administration/configuration/backups.md
Labels: enhancement, p_Cloud
