Repository RedisLabs/redislabs-docs, pull requests merged in 2021-09, with the labels that each got.

#1519 update to annotations explanation
  content/platforms/kubernetes/tasks/set-up-ingress-controller.md
Labels: K8s

#1522 Jira DOC-878: RI - Update release notes to match other release note updates.
  content/ri/release-notes/_index.md
  content/ri/release-notes/archive/_index.md
  content/ri/release-notes/archive/v0.9.32.md
  content/ri/release-notes/archive/v0.9.33.md
  content/ri/release-notes/archive/v0.9.34.1.md
  content/ri/release-notes/archive/v0.9.34.2.md
  content/ri/release-notes/archive/v0.9.34.md
  content/ri/release-notes/archive/v0.9.35.md
  content/ri/release-notes/archive/v0.9.36.md
  content/ri/release-notes/archive/v0.9.37.md
  content/ri/release-notes/archive/v0.9.38.md
  content/ri/release-notes/archive/v0.9.39.md
  content/ri/release-notes/archive/v0.9.40.1.md
  content/ri/release-notes/archive/v0.9.40.md
  content/ri/release-notes/archive/v0.9.41.md
  content/ri/release-notes/archive/v0.9.42.md
  content/ri/release-notes/v1.0.0.md
  content/ri/release-notes/v1.1.0.md
  content/ri/release-notes/v1.10.0.md
  content/ri/release-notes/v1.2.0.md
  content/ri/release-notes/v1.3.0.md
  content/ri/release-notes/v1.4.0.md
  content/ri/release-notes/v1.5.0.md
  content/ri/release-notes/v1.6.0.md
  content/ri/release-notes/v1.7.0.md
  content/ri/release-notes/v1.8.0.md
  content/ri/release-notes/v1.9.0.md
Labels: p_Insight

#1523 Removed duplicated content
  content/platforms/kubernetes/concepts/db-controller.md
  content/platforms/kubernetes/reference/db-options.md
Labels: K8s

#1534 Automated PDF generation
  .circleci/config.yml
  i18n/en.toml
  layouts/partials/download-pdf.html
  layouts/partials/next-prev-page.html
  layouts/partials/original/body-beforecontent.html
  layouts/partials/pdf-prep-recursive.html
  layouts/partials/pdf-prep-single.html
  layouts/partials/post-bottom.html
  layouts/partials/recursive-children.html
  robots.txt
  static/css/pdf-style.css
  static/fonts/lato/Lato-Regular.ttf
  static/fonts/lato/Lato-Regular.woff2
  static/fonts/robotomono/Roboto-Italic.ttf
  static/fonts/robotomono/Roboto-Medium.ttf
  static/fonts/robotomono/Roboto-Regular.ttf
  static/fonts/robotomono/RobotoMono-Medium.ttf
  static/fonts/robotomono/RobotoMono-Regular.ttf
  static/theme-flex/style.css
  utilities/create_pdf_tarball/create_html.sh
  utilities/create_pdf_tarball/create_pdfs_tarball.sh
  utilities/create_pdf_tarball/delete_tmps.sh
  utilities/create_pdf_tarball/edit_links.sh
  utilities/create_pdf_tarball/list_template_recursive.html
  utilities/create_pdf_tarball/local_create_pdfs_tarball.sh
  utilities/create_pdf_tarball/local_delete_tmps.sh
  utilities/create_single_pdfs/create_html.sh
  utilities/create_single_pdfs/create_pdfs.sh
  utilities/create_single_pdfs/delete_tmps.sh
  utilities/create_single_pdfs/list_template_single.html
  utilities/create_single_pdfs/local_create_pdfs.sh
  utilities/create_single_pdfs/local_delete_tmps.sh
Labels: infrastructure

#1526 DOC-885 K8s enable internode encryption
  content/platforms/kubernetes/tasks/internode-encryption.md
  content/platforms/kubernetes/tasks/set-up-ingress-controller.md
Labels: K8s

#1529 Doc-804 K8s connect to the admin console
  content/platforms/kubernetes/tasks/connect-to-admin-console.md
Labels: K8s

#1524 Doc-882 Revise Manage Databases
  content/platforms/kubernetes/concepts/db-controller.md
Labels: K8s

#1527 DOC-818 K8s Galactica release changes
  content/platforms/kubernetes/reference/supported_k8s_distributions.md
  content/platforms/release-notes/k8s-6-2-4-1-2021-09.md
Labels: in progress, K8s

#1537 Updated table-children shortcode to handle page description
  layouts/shortcodes/table-children.html
Labels: enhancement

#1536 Jira DOC-888: Update "Supported distributions" doc to reflect 6.2.4.-1 updates
  content/platforms/kubernetes/reference/supported_k8s_distributions.md
  content/platforms/release-notes/_index.md
  content/platforms/release-notes/k8s-6-2-4-1-2021-09.md
Labels: p_Platforms

#1539 Jira DOC-894: Add aliases for "unbranched" requests
  content/glossary/_index.md
  content/modules/_index.md
  content/modules/redisai/_index.md
  content/modules/redisbloom/_index.md
  content/modules/redisearch/_index.md
  content/modules/redisgears/_index.md
  content/modules/redisgraph/_index.md
  content/modules/redisjson/_index.md
  content/modules/redistimeseries/_index.md
  content/platforms/_index.md
  content/platforms/kubernetes/_index.md
  content/platforms/release-notes/_index.md
  content/rc/_index.md
  content/ri/_index.md
  content/rs/_index.md
  website.json
Labels: infrastructure

#1542 Jira DOC-897: Style review: replica
  content/embeds/shard-placement-intro.md
  content/glossary/_index.md
  content/rc/databases/create-database.md
  content/ri/faqs.md
  content/ri/using-redisinsight/add-instance.md
  content/ri/using-redisinsight/cluster-management.md
  content/ri/using-redisinsight/memory-analysis.md
  content/rs/administering/creating-databases/create-active-active.md
  content/rs/administering/database-operations/replica-ha.md
  content/rs/administering/database-operations/slave-ha.md
  content/rs/administering/designing-production/active-active.md
  content/rs/administering/troubleshooting/replicaof-repeatedly-fails.md
  content/rs/concepts/_index.md
  content/rs/concepts/data-access/consistency-durability.md
  content/rs/concepts/high-availability/rack-zone-awareness.md
  content/rs/concepts/high-availability/replication.md
  content/rs/concepts/shard-placement-policy.md
  content/rs/concepts/terminology.md
  content/rs/getting-started/getting-started-docker.md
  content/rs/installing-upgrading/configuring-aws-instances.md
  content/rs/references/memtier-benchmark.md
  content/rs/release-notes/legacy-release-notes/rs-5-4-december-2018.md
  content/rs/release-notes/rs-5-6-0-april-2020.md
  content/rs/release-notes/rs-6-0-20-april-2021.md
  static/images/rs/sharding.png
Labels: p_Software, p_Cloud, p_Insight, p_Glossary

#1544 Doc-545 Update K8s Openshift links
  content/platforms/kubernetes/getting-started/openshift/_index.md
  content/platforms/kubernetes/getting-started/openshift/openshift-cli.md
  content/platforms/kubernetes/getting-started/openshift/openshift-operatorhub.md
Labels: K8s

#1551 Jira DOC 910: RC - Update "View/edit databases" to match recent workflow changes.
  content/rc/databases/view-edit-database.md
  static/images/rc/icon-database-list-filter-active.png
  static/images/rc/icon-database-list-filter-normal.png
  static/images/rc/icon-database-list-sort-ascending.png
  static/images/rc/icon-database-list-sort-descending.png
Labels: p_Cloud

#1550 Added more detail to rladmin verify commands
  content/rs/references/rladmin.md
Labels: p_Software, RS6.2.8

#1548 Jira DOC-703: Update Database backup to reflect start time and updated directions.
  content/rs/administering/import-export/database-backup.md
  static/images/rs/database-configuration-periodic-backup.png
Labels: p_Software

#1554 Jira DOC-769: Update TLS support statement for TLS.
  content/embeds/supported-platforms-embed.md
  content/rs/administering/cluster-operations/updating-certificates.md
Labels: p_Software
