Repository RedisLabs/redislabs-docs, pull requests merged in 2022-08, with the labels that each got.

#2055 DOC-1525: Create RS landing page
  content/rs/_index.md
Labels: p_Software

#2032 DOC-1477: Update bdbs/actions endpoints
  content/rs/references/rest-api/requests/bdbs/actions/backup_reset_status.md
  content/rs/references/rest-api/requests/bdbs/actions/export.md
  content/rs/references/rest-api/requests/bdbs/actions/export_reset_status.md
  content/rs/references/rest-api/requests/bdbs/actions/import.md
  content/rs/references/rest-api/requests/bdbs/actions/import_reset_status.md
  content/rs/references/rest-api/requests/bdbs/actions/optimize_shards_placement.md
Labels: p_Software

#2068 DOC-1464: RC - Consolidate duplicate "change plan" article
  content/rc/administration/setup/change-plan.md
  content/rc/subscriptions/view-fixed-subscription.md
Labels: p_Cloud

#2073 Change RedisJSON v2.2 release notes to a draft
  content/modules/redisjson/release-notes/redisjson-2.2-release-notes.md
Labels: p_Modules

#2076 Revert "Change RedisJSON v2.2 release notes to a draft"
  content/modules/redisjson/release-notes/redisjson-2.2-release-notes.md
Labels: p_Modules

#2061 Updated RedisJSON quick start
  content/modules/redisjson/redisjson-quickstart.md
Labels: p_Modules

#2072 DOC-842: RC Reorg - Rework Admin menu, part II
  content/rc/_index.md
  content/rc/administration/_index.md
  content/rc/databases/back-up-data.md
  content/rc/databases/configuration/_index.md
  content/rc/databases/flush-data.md
  content/rc/databases/import-data.md
  content/rc/databases/migrate-databases.md
  content/rc/databases/monitor-performance.md
  content/rc/databases/system-logs.md
  content/rc/databases/usage-reports.md
  content/rc/databases/view-edit-database.md
  content/rc/security/_index.md
  content/rc/security/access-management.md
Labels: p_Cloud

#2071 Added A-A JSON design link
  content/modules/redisjson/active-active.md
Labels: p_Modules

#2078 Changed RedisJSON v2.2 to preview release
  content/modules/enterprise-capabilities.md
  content/modules/redisjson/release-notes/redisjson-2.2-release-notes.md
Labels: p_Modules

#2070 DOC-1548 delete outdated K8s LDAP article
  content/kubernetes/security/_index.md
  content/kubernetes/security/ldap-on-k8s.md
  content/rs/references/cli-utilities/rladmin/cluster/config.md
Labels: K8s

#2080 Search + JSON quick start
  content/modules/redisearch/_index.md
  content/modules/redisearch/redisearch-quickstart.md
  content/modules/redisearch/search-json-quickstart.md
  content/modules/redisjson/_index.md
Labels: p_Modules

#2084 RS - v6.2.12 release notes and doc updates
  content/glossary/_index.md
  content/rs/references/cli-utilities/rladmin/cluster/ocsp.md
  content/rs/references/rest-api/objects/cluster/alert_settings.md
  content/rs/references/rest-api/objects/ocsp.md
  content/rs/references/rest-api/objects/ocsp_status.md
  content/rs/references/rest-api/permissions.md
  content/rs/references/rest-api/requests/ocsp/_index.md
  content/rs/references/rest-api/requests/ocsp/status.md
  content/rs/references/rest-api/requests/ocsp/test.md
  content/rs/release-notes/rs-6-0-20-april-2021.md
  content/rs/release-notes/rs-6-2-12.md
  content/rs/release-notes/rs-6-2-4-august-2021.md
  content/rs/security/access-control/ldap/_index.md
  content/rs/security/access-control/ldap/cluster-based-ldap-authentication.md
  content/rs/security/access-control/ldap/migrate-to-role-based-ldap.md
  content/rs/security/access-control/manage-users/login-lockout.md
  content/rs/security/access-control/manage-users/manage-passwords.md
  content/rs/security/certificates/ocsp-stapling.md
  static/images/rs/cluster-settings-preferences.png
Labels: p_Software

#2067 New AA articles
  content/glossary/_index.md
  content/kubernetes/deployment/tanzu.md
  content/rs/_index.md
  content/rs/concepts/data-access/consistency-durability.md
  content/rs/databases/active-active/_index.md
  content/rs/databases/active-active/aa-planning.md
  content/rs/databases/active-active/causal-consistency-crdb.md
  content/rs/databases/active-active/connect-to-aa-db.md
  content/rs/databases/active-active/create-active-active.md
  content/rs/databases/active-active/delete-aa-database.md
  content/rs/databases/active-active/develop/_index.md
  content/rs/databases/active-active/develop/data-types/_index.md
  content/rs/databases/active-active/develop/data-types/hashes.md
  content/rs/databases/active-active/develop/data-types/hyperloglog.md
  content/rs/databases/active-active/develop/data-types/lists.md
  content/rs/databases/active-active/develop/data-types/sets.md
  content/rs/databases/active-active/develop/data-types/sorted-sets.md
  content/rs/databases/active-active/develop/data-types/streams.md
  content/rs/databases/active-active/develop/data-types/strings.md
  content/rs/databases/active-active/develop/develop-for-aa.md
  content/rs/databases/active-active/edit-aa-database.md
  content/rs/databases/active-active/get-started-active-active.md
  content/rs/databases/active-active/intercluster-replication.md
  content/rs/databases/active-active/manage-aa.md
  content/rs/databases/active-active/syncer.md
  content/rs/databases/active-active/synchronization-mode.md
  content/rs/databases/configure/_index.md
  content/rs/databases/configure/consistency-durability.md
  content/rs/databases/configure/durability-ha.md
  content/rs/databases/configure/replication.md
  content/rs/databases/create-database.md
  content/rs/databases/edit-delete-db.md
  content/rs/databases/import-export/replica-of.md
  content/rs/networking/configuring-aws-route53-dns-redis-enterprise.md
  content/rs/release-notes/rs-6-0-20-april-2021.md
  content/rs/release-notes/rs-6-0-may-2020.md
Labels: p_Software

#2089 RS: Update release note links
  content/rs/release-notes/rs-6-2-12.md
Labels: p_Software

#2092 Added RedisBloom commands table
  content/modules/redisbloom/_index.md
  content/modules/redisbloom/commands.md
  content/modules/redisbloom/redisbloom-quickstart.md
Labels: p_Modules

#2093 Fixed formatting on Prometheus integrations
  content/rs/monitoring-metrics/prometheus-integration.md
Labels: p_Software

#2087 Added RedisGraph command table
  content/modules/redisgraph/_index.md
  content/modules/redisgraph/commands.md
  content/modules/redisgraph/redisgraph-quickstart.md
Labels: p_Modules

#2091 Added RedisTimeSeries command table
  content/modules/redistimeseries/_index.md
  content/modules/redistimeseries/commands.md
  content/modules/redistimeseries/redistimeseries-quickstart.md
Labels: p_Modules

#2090 DOC-1562: RC - Fix broken image in API System Logs example
  content/rc/api/examples/audit-system-logs.md
  content/rc/databases/system-logs.md
Labels: p_Cloud

#2094 DOC-1571: RS - Update Supported platforms to RHEL 8.6
  content/embeds/supported-platforms-embed.md
Labels: p_Software

#2095 DOC-1557: RS - Update memory requirements
  content/embeds/hardware-requirements-embed.md
Labels: p_Software

#2101 RC: Updated TLS doc
  content/rc/security/database-security/tls-ssl.md
  static/images/rc/button-account-settings-security-ca-download.png
  static/images/rc/button-database-config-security-server-ca-download.png
  static/images/rc/database-details-configuration-tab-security-tls-client-auth-certificate.png
  static/images/rc/database-details-configuration-tab-security-tls-toggle.png
Labels: p_Cloud

#2103 DOC-1576: Update RedisGraph support for eviction expiration
  content/modules/enterprise-capabilities.md
Labels: p_Modules

#2105 RC - Active-Active GA
  content/rc/databases/active-active-redis.md
  content/rc/subscriptions/create-active-active-subscription.md
  static/images/rc/create-database-active-active.png
  static/images/rc/create-flexible-sub-active-active-off.png
  static/images/rc/create-flexible-sub-active-active-on.png
  static/images/rc/create-sub-active-active-cidr.png
  static/images/rc/create-sub-active-active-regions.png
  static/images/rc/icon-cidr-address-error.png
  static/images/rc/icon-cidr-address-ok.png
  static/images/rc/icon-region-delete.png
Labels: p_Cloud

#2098 Update redisjson-2.2-release-notes.md
  content/modules/redisjson/release-notes/redisjson-2.2-release-notes.md
Labels: p_Modules

#2102 RC: Update TLS to new UI
  content/rc/security/database-security/tls-ssl.md
  static/images/rc/button-account-settings-security-ca-download.png
  static/images/rc/button-database-config-security-server-ca-download.png
  static/images/rc/database-details-configuration-tab-security-tls-client-auth-certificate.png
  static/images/rc/database-details-configuration-tab-security-tls-toggle.png
Labels: p_Cloud

#2109 Added RedisGraph v2.8.19 release notes
  content/modules/redisgraph/release-notes/redisgraph-2.8-release-notes.md
Labels: p_Modules

#2104 RC: Update CIDR allow list to new UI
  content/rc/security/cidr-whitelist.md
  content/rc/security/database-security/network-security.md
  static/images/rc/button-database-config-security-add-cidr.png
  static/images/rc/button-subscription-connectivity-add-allow-list.png
  static/images/rc/button-subscription-connectivity-allow-list-apply-all-changes.png
  static/images/rc/database-details-configuration-tab-security-cidr-allowlist-add-first-ip.png
  static/images/rc/database-details-configuration-tab-security-cidr-allowlist-add-more-ips.png
  static/images/rc/database-details-configuration-tab-security-cidr-allowlist-toggle.png
  static/images/rc/icon-allow-list-add-entry.png
  static/images/rc/icon-check-mark.png
  static/images/rc/subscription-connectivity-allow-list-add-entry.png
  static/images/rc/subscription-connectivity-allow-list-type-dropdown.png
Labels: p_Cloud

#2111 Added RediSearch v2.4.14 release notes
  content/modules/redisearch/release-notes/redisearch-2.4-release-notes.md
Labels: p_Modules

#2121 JSON: Key name rules only apply to legacy path syntax
  content/modules/redisjson/_index.md
Labels: p_Modules

#2119 RC: New account settings screenshot & CA info
  content/rc/accounts/account-settings.md
  static/images/rc/account-settings-account-tab.png
Labels: p_Cloud

#2124 Fixed RedisGears install OS & version
  content/modules/redisgears/installing-redisgears.md
Labels: p_Modules

#2123 DOC-1467: Create Flexible Subscription update
  content/rc/subscriptions/create-flexible-subscription.md
  static/images/rc/flexible-add-database-advanced.png
  static/images/rc/flexible-add-database-basic.png
  static/images/rc/subscription-new-flexible-review.png
  static/images/rc/subscription-new-flexible-setup-general.png
Labels: p_Cloud

#2114 DOC-1581: RC Backup data updates
  content/rc/databases/back-up-data.md
  content/rc/databases/delete-database.md
  content/rc/databases/view-edit-database.md
  static/images/rc/button-database-backup-now.png
  static/images/rc/database-details-configuration-durability-backup.png
  static/images/rc/database-details-configuration-tab-durability-flexible.png
  static/images/rc/database-details-configuration-tab-general-flexible.png
  static/images/rc/subscription-flexible-databases-tab-pending.png
Labels: p_Cloud

#2128 DOC-1605: Update View Fixed Subscription
  content/rc/subscriptions/view-fixed-subscription.md
  static/images/rc/button-subscription-cancel.png
  static/images/rc/icon-edit-subscription-name.png
  static/images/rc/subscription-change-fixed-tiers.png
  static/images/rc/subscription-details-fixed-databases-tab.png
  static/images/rc/subscription-details-fixed-overview-tab.png
  static/images/rc/subscription-list-select.png
Labels: p_Cloud

#2131 DOC-1609: RC: Update Billing and Payments Credit screenshot
  content/rc/billing-and-payments.md
  static/images/rc/billing-payments-credits-tab.png
Labels: p_Cloud

#2130 DOC-1608: RC Update Delete Subscription
  content/rc/subscriptions/delete-subscription.md
  static/images/rc/subscription-cancel-confirm-dialog.png
  static/images/rc/subscription-free-cancel-subscription.png
  static/images/rc/subscription-list-free-no-databases.png
Labels: p_Cloud

#2129 DOC-1606: RC View Flexible Subscription Update
  content/rc/subscriptions/view-fixed-subscription.md
  content/rc/subscriptions/view-flexible-subscription.md
  static/images/rc/icon-database-detail-status-active.png
  static/images/rc/icon-database-detail-status-pending.png
  static/images/rc/icon-database-status-active.png
  static/images/rc/icon-subscription-detail-change-payment-flexible.png
  static/images/rc/icon-subscription-status-pending.png
  static/images/rc/subscription-details-connectivity-tab-flexible.png
  static/images/rc/subscription-details-overview-flexible.png
Labels: p_Cloud

#2117 RC: Updates for VPC peering UI & multiple CIDRs
  content/rc/security/database-security/network-security.md
  content/rc/security/vpc-peering.md
  static/images/rc/button-subscription-connectivity-vpc-peering-add-cidr.png
  static/images/rc/button-subscription-connectivity-vpc-peering-add-peering.png
  static/images/rc/button-subscription-connectivity-vpc-peering-initiate-peering.png
  static/images/rc/subscription-connectivity-vpc-peering-add-multiple-cidrs.png
  static/images/rc/subscription-connectivity-vpc-peering-aws.png
  static/images/rc/subscription-connectivity-vpc-peering-gcloud-command.png
  static/images/rc/subscription-connectivity-vpc-peering-gcp.png
Labels: p_Cloud

#2134 DOC-1483: Update /boostrap/ REST API Reference
  content/rs/references/rest-api/requests/bootstrap/_index.md
Labels: p_Software

#2136 DOC-1600: Update RedisInsight Links
  content/ri/installing/install-redis-desktop.md
Labels: p_Insight
