Repository RedisLabs/redislabs-docs, pull requests merged in 2022-12, with the labels that each got.

#2242 DOC-1761 K8s: log collector mode
  content/kubernetes/logs/collect-logs.md
Labels: K8s

#2261 DOC-1788 update ssl-passthrough annotation
  content/kubernetes/re-clusters/create-aa-database.md
  content/kubernetes/re-databases/set-up-ingress-controller.md
Labels: K8s

#2258 Updated RS default role permissions
  content/rs/security/access-control/create-roles.md
Labels: p_Software

#2254 OSS command & config compatibility
  content/rc/_index.md
  content/rc/databases/_index.md
  content/rc/faqs/_index.md
  content/rs/references/compatibility.md
  content/rs/references/compatibility/_index.md
  content/rs/references/compatibility/commands/_index.md
  content/rs/references/compatibility/commands/cluster.md
  content/rs/references/compatibility/commands/connection.md
  content/rs/references/compatibility/commands/data-types.md
  content/rs/references/compatibility/commands/generic.md
  content/rs/references/compatibility/commands/pub-sub.md
  content/rs/references/compatibility/commands/scripting.md
  content/rs/references/compatibility/commands/server.md
  content/rs/references/compatibility/commands/transactions.md
  content/rs/references/compatibility/config-settings.md
  content/rs/release-notes/rs-6-2-4-august-2021.md
Labels: p_Software, p_Cloud

#2263 RC pub/sub ACLs
  content/rc/security/database-security/passwords-users-roles.md
Labels: p_Cloud

#2266 DOC-1794: RS - Broken links on "Configure database persistence"
  content/rs/databases/configure/database-persistence.md
Labels: p_Software

#2276 DOC-1784 K8s Neptune maint 6.2.18-41 release notes
  content/kubernetes/re-clusters/upgrade-redis-cluster.md
  content/kubernetes/release-notes/k8s-6-2-18-3.md
  content/kubernetes/release-notes/k8s-6-2-18-41.md
Labels: K8s

#2280 DOC-1792: Update to GCP integration step
  content/rc/cloud-integrations/gcp-marketplace/_index.md
Labels: p_Cloud

#2284 Fix typo in RS main page
  content/rs/_index.md
Labels: p_Software

#2285 RC Private Service Connect
  content/rc/security/private-service-connect.md
  static/images/rc/button-subscription-connectivity-psc-accept-continue.png
  static/images/rc/button-subscription-connectivity-psc-accept.png
  static/images/rc/button-subscription-connectivity-psc-complete-setup.png
  static/images/rc/button-subscription-connectivity-psc-connect.png
  static/images/rc/button-subscription-connectivity-psc-continue.png
  static/images/rc/button-subscription-connectivity-psc-create-connection.png
  static/images/rc/button-subscription-connectivity-psc-remove-service-confirm.png
  static/images/rc/icon-psc-actions.png
  static/images/rc/icon-psc-delete-endpoint.png
  static/images/rc/subscription-connectivity-psc-gcloud-script.png
Labels: p_Cloud

#2275 RS certificates table
  content/kubernetes/security/manage-rec-certificates.md
  content/rs/references/cli-utilities/rladmin/cluster/certificate.md
  content/rs/references/rest-api/requests/cluster/certificates/_index.md
  content/rs/references/rest-api/requests/cluster/update-cert.md
  content/rs/security/certificates/_index.md
  content/rs/security/certificates/create-certificates.md
  content/rs/security/certificates/updating-certificates.md
Labels: p_Software

#2273 Create v.2.16.0.md
  content/ri/release-notes/v.2.16.0.md
Labels: p_Insight
