Repository RedisLabs/redislabs-docs, pull requests merged in 2022-04, with the labels that each got.

#1843 Review feedback Doc-941
  content/kubernetes/deployment/quick-start.md
  content/kubernetes/re-clusters/delete_custom_resources.md
Labels: K8s

#1848 DOC-1277 remove pivotal articles
  content/kubernetes/deployment/tanzu.md
  content/kubernetes/deployment/tanzu/pcf/backup-restore-pcf.md
  content/kubernetes/deployment/tanzu/pcf/using-pcf.md
  content/kubernetes/reference/supported_k8s_distributions.md
Labels: K8s

#1856 DOC-1266 RS - Change username to user email for password reset command
  content/rs/security/admin-console-security/user-security.md
Labels: p_Software

#1860 RS: rladmin page should clarify that username must be a mail
  content/rs/references/rladmin.md
Labels: in progress, p_Software

#1864 RS - DOC-1231: RHEL 8.5 support
  content/embeds/supported-platforms-embed.md
  content/rs/release-notes/rs-6-2-10-february-2022.md
Labels: p_Software

#1863 DOC-1292 K8s: "Copy to clipboard" button scrolls with text in code snippet
  content/kubernetes/re-databases/set-up-ingress-controller.md
Labels: bug, infrastructure, K8s

#1866 RS - DOC-1296: Link to DNS instructions on "Setting up a new cluster" showing as plain text
  content/embeds/new-cluster-embed.md
Labels: bug, p_Software

#1865 Added CRDB health_report request to RS REST API
  content/rs/references/rest-api/objects/crdb/health_report/_index.md
  content/rs/references/rest-api/objects/crdb/health_report/health_report_configuration.md
  content/rs/references/rest-api/requests/crdbs/health_report.md
  content/rs/references/rest-api/requests/crdbs/updates.md
  content/rs/release-notes/rs-6-2-10-february-2022.md
Labels: p_Software

#1862 RS reorg: Connections section
  content/rs/concepts/data-access/discovery-service.md
  content/rs/connections/_index.md
  content/rs/connections/supported-clients-browsers.md
  content/rs/connections/testing-client-connectivity.md
Labels: p_Software

#1844 DOC-1194 K8s - add client certificates
  content/kubernetes/faqs/_index.md
  content/kubernetes/re-clusters/create-aa-database.md
  content/kubernetes/security/add-client-certificates.md
  content/kubernetes/security/manage-rec-certificates.md
  content/kubernetes/security/manage-rec-credentials.md
Labels: K8s

#1867 Added OCSP commands to rladmin reference
  content/rs/references/rladmin.md
Labels: p_Software

#1845 RS reorg: TLS and certificates
  content/embeds/adding-node-embed.md
  content/embeds/new-cluster-embed.md
  content/glossary/_index.md
  content/kubernetes/re-databases/set-up-ingress-controller.md
  content/kubernetes/reference/db-options.md
  content/kubernetes/security/manage-rec-certificates.md
  content/rs/administering/cluster-operations/updating-certificates.md
  content/rs/databases/_index.md
  content/rs/databases/configure/_index.md
  content/rs/databases/create-database.md
  content/rs/release-notes/legacy-release-notes/rlec-4-3-aug-2016.md
  content/rs/release-notes/legacy-release-notes/rs-5-4-10-december-2019.md
  content/rs/release-notes/legacy-release-notes/rs-5-4-14-february-2020.md
  content/rs/release-notes/legacy-release-notes/rs-5-4-2-april-2019.md
  content/rs/release-notes/legacy-release-notes/rs-5-4-4-june-2019.md
  content/rs/release-notes/legacy-release-notes/rs-5-4-6-july-2019.md
  content/rs/release-notes/rs-5-6-0-april-2020.md
  content/rs/release-notes/rs-6-0-12-january-2021.md
  content/rs/release-notes/rs-6-0-20-april-2021.md
  content/rs/release-notes/rs-6-0-8-september-2020.md
  content/rs/security/_index.md
  content/rs/security/admin-console-security/_index.md
  content/rs/security/admin-console-security/encryption.md
  content/rs/security/certificates/_index.md
  content/rs/security/certificates/create-certificates.md
  content/rs/security/certificates/updating-certificates.md
  content/rs/security/tls/_index.md
  content/rs/security/tls/ciphers.md
  content/rs/security/tls/enable-tls.md
  content/rs/security/tls/tls-protocols.md
Labels: p_Software

#1868 RS - DOC 1298: Update 6.2.10 release notes with fixes for build 96
  content/rs/release-notes/rs-6-2-10-february-2022.md
Labels: p_Software

#1871 Added OCSP to RS REST API reference
  content/rs/references/rest-api/objects/cluster/alert_settings.md
  content/rs/references/rest-api/objects/ocsp.md
  content/rs/references/rest-api/objects/ocsp_status.md
  content/rs/references/rest-api/permissions.md
  content/rs/references/rest-api/requests/ocsp/_index.md
  content/rs/references/rest-api/requests/ocsp/status.md
  content/rs/references/rest-api/requests/ocsp/test.md
Labels: p_Software

#1875 DOC-1283 update apiversion
  content/kubernetes/re-databases/set-up-ingress-controller.md
Labels: K8s

#1883 Added RedisGears v1.2.3 release notes
  content/modules/redisgears/release-notes/redisgears-1.2-release-notes.md
Labels: p_Modules

#1873 Add RS OCSP stapling article
  content/rs/references/rladmin.md
  content/rs/security/certificates/ocsp-stapling.md
Labels: p_Software

#1886 RC Fixed subscription supports TLS
  content/rc/security/database-security/tls-ssl.md
Labels: p_Cloud

#1888 Jira DOC-660: Update REST API sample parameter value
  content/rs/references/rest-api/requests/bdbs/_index.md
Labels: p_Software

#1889 RS: DOC-1209 - Update consistency image terminology
  static/images/rs/strong-consistency.png
  static/images/rs/strong_consistency-300x156.png
  static/images/rs/weak-consistency.png
  static/images/rs/weak_consistency-300x161.png
Labels: p_Software

#1887 DOC-1317 - RS: CLI Utitilites Reorg rladmin help and rladmin info commands
  content/rs/references/cli-utilities/rladmin/help.md
  content/rs/references/cli-utilities/rladmin/info.md
Labels: p_Software

#1869 expire after 90 days not 45 days
  content/rs/security/internode-encryption.md
Labels: p_Software

#1885 DOC-1160 - RS API: Document v1 /actions/ API request.
  content/rs/references/rest-api/objects/state-machine.md
  content/rs/references/rest-api/requests/actions.md
Labels: p_Software

#1890 Edits for upgrade RediSearch 1.x DB to 2.x
  content/modules/redisearch/redisearch-2-upgrade.md
Labels: p_Modules

#1892 Modules: Update module lifecycle and add links
  content/modules/_index.md
  content/modules/modules-lifecycle.md
  content/modules/redis-stack.md
  content/modules/redisai/_index.md
  content/modules/redisbloom/_index.md
  content/modules/redisearch/_index.md
  content/modules/redisgears/_index.md
  content/modules/redisgraph/_index.md
  content/modules/redisjson/_index.md
  content/modules/redistimeseries/_index.md
  static/tables/redisbloom-lifecycle.csv
  static/tables/redisearch-lifecycle.csv
  static/tables/redisgears-lifecycle.csv
  static/tables/redisgraph-lifecycle.csv
  static/tables/redisjson-lifecycle.csv
  static/tables/redistimeseries-lifecycle.csv
Labels: p_Modules

#1891 DOC-1319 - RS Utilities Reorg: rladmin status page
  content/rs/references/cli-utilities/rladmin/status.md
Labels: p_Software

#1894 Added RediSearch v2.4.5 release notes
  content/modules/redisearch/release-notes/redisearch-2.4-release-notes.md
Labels: p_Modules

#1895 DOC-1323 - RS CLI Utilities Reorg: rladmin failover command
  content/rs/references/cli-utilities/rladmin/failover.md
Labels: p_Software

#1896 DOC-1065 durability and availability article
  content/rs/concepts/high-availability/_index.md
Labels: p_Software

#1897 Merge OCSP docs into release-rs-blanc
  content/rs/references/rest-api/objects/cluster/alert_settings.md
  content/rs/references/rest-api/objects/ocsp.md
  content/rs/references/rest-api/objects/ocsp_status.md
  content/rs/references/rest-api/permissions.md
  content/rs/references/rest-api/requests/ocsp/_index.md
  content/rs/references/rest-api/requests/ocsp/status.md
  content/rs/references/rest-api/requests/ocsp/test.md
  content/rs/references/rladmin.md
  content/rs/security/certificates/ocsp-stapling.md
Labels: p_Software
