Repository RedisLabs/redislabs-docs, pull requests merged in 2022-06, with the labels that each got.

#1966 DOC-1371: RS CRDB-CLI reorg - crdb-cli crdb list command
  content/rs/references/cli-utilities/crdb-cli/crdb/list.md
Labels: p_Software

#1965 DOC-1368: crdb-cli create command
  content/rs/references/cli-utilities/crdb-cli/crdb/create.md
Labels: p_Software

#1968 Added release notes for RedisJSON v2.0.9, RedisTimeSeries v1.6.13
  content/modules/redisjson/release-notes/redisjson-2.0-release-notes.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.6-release-notes.md
Labels: p_Modules

#1970 DOC-1376: crdb-cli crdb health-report page
  content/rs/references/cli-utilities/crdb-cli/crdb/health-report.md
Labels: p_Software

#1976 K8s: add upgrade warning DOC-1441
  content/kubernetes/re-clusters/upgrade-redis-cluster.md
Labels: K8s

#1978 DOC-1374: crdb-cli crdb remove-instance page
  content/rs/references/cli-utilities/crdb-cli/crdb/remove-instance.md
Labels: p_Software

#1981 DOC-1369: crdb-cli crdb delete page
  content/rs/references/cli-utilities/crdb-cli/crdb/delete.md
Labels: p_Software

#1979 DOC-1373: crdb-cli crdb add-instance page
  content/rs/references/cli-utilities/crdb-cli/crdb/add-instance.md
Labels: p_Software

#1977 DOC-1375: crdb-cli purge-instance page
  content/rs/references/cli-utilities/crdb-cli/crdb/purge-instance.md
  content/rs/references/cli-utilities/crdb-cli/crdb/remove-instance.md
Labels: p_Software

#1971 DOC-1370 - crdb-cli crdb flush page
  content/rs/references/cli-utilities/crdb-cli/crdb/flush.md
Labels: p_Software

#1967 DOC-1377: crdb-cli crdb get command
  content/rs/references/cli-utilities/crdb-cli/crdb/get.md
Labels: p_Software

#1928 Changes in Ingress spec in Kubernetes 1.19
  content/kubernetes/re-databases/set-up-ingress-controller.md
Labels: K8s

#1983 DOC-1372: crdb-cli crdb update page, and fixing crdb-cli crdb create page
  content/rs/references/cli-utilities/crdb-cli/crdb/create.md
  content/rs/references/cli-utilities/crdb-cli/crdb/update.md
Labels: p_Software

#1989 rladmin OCSP reference updates
  content/rs/references/cli-utilities/rladmin/cluster/ocsp.md
  content/rs/security/certificates/ocsp-stapling.md
Labels: p_Software

#1973 RedisJSON conflict resolution
  content/modules/redisjson/active-active.md
  content/rs/databases/active-active/_index.md
Labels: p_Modules

#1986 Added RedisGears register events doc
  content/modules/redisgears/jvm/classes/gearsbuilder/register.md
  content/modules/redisgears/jvm/classes/readers/keysreader.md
  content/modules/redisgears/register-events.md
Labels: p_Modules

#1995 DOC-1453 broken link
  content/rs/clusters/new-cluster-setup.md
Labels: bug

#2001 Added RedisBloom v2.2.17 release notes
  content/modules/redisbloom/release-notes/redisbloom-2.2-release-notes.md
Labels: p_Modules

#2000 DOC-1410 edits to Upgrade REC on K8s article
  content/kubernetes/re-clusters/upgrade-redis-cluster.md
Labels: K8s

#2006 Fix minor typo in REC CR troubleshooting docs
  content/kubernetes/re-clusters/delete_custom_resources.md
Labels: K8s

#1961 DOC-1431: API Clean-up - Identify existing REST API Examples in RC docs and simplify the presentation
  content/modules/install/add-module-to-cluster.md
  content/modules/redisgears/installing-redisgears.md
  content/rc/api/examples/audit-system-logs.md
  content/rc/api/examples/back-up-and-import-data.md
  content/rc/api/examples/create-database.md
  content/rc/api/examples/dryrun-cost-estimates.md
  content/rc/api/examples/manage-cloud-accounts.md
  content/rc/api/examples/manage-subscriptions.md
  content/rc/api/examples/view-account-information.md
  content/rc/api/get-started/manage-tasks.md
  content/rc/api/get-started/process-lifecycle.md
Labels: p_Cloud, p_Modules

#2004 DOC-1415: Identify existing REST API Examples in RS docs and simplify the presentation
  content/rs/clusters/maintenance-mode.md
  content/rs/clusters/optimize/turn-off-services.md
  content/rs/clusters/remove-node.md
  content/rs/databases/import-export/flush-db-crdb.md
  content/rs/security/access-control/manage-users/login-lockout.md
  content/rs/security/access-control/manage-users/manage-passwords.md
  content/rs/security/certificates/updating-certificates.md
Labels: p_Software

#2008 RS reorg: Logging section DOC-1419
  content/glossary/_index.md
  content/kubernetes/deployment/quick-start.md
  content/kubernetes/re-clusters/cluster-recovery.md
  content/rs/administering/designing-production/persistent-ephemeral-storage.md
  content/rs/databases/active-active/develop/hyperloglog-active-active.md
  content/rs/installing-upgrading/get-started-redis-enterprise-software.md
  content/rs/logging/_index.md
  content/rs/logging/log-security.md
  content/rs/logging/redis-slow-log.md
  content/rs/logging/rsyslog-logging/_index.md
  content/rs/logging/rsyslog-logging/bdb-events.md
  content/rs/logging/rsyslog-logging/cluster-events.md
  content/rs/logging/rsyslog-logging/node-events.md
  content/rs/logging/rsyslog-logging/user-events.md
  content/rs/security/_index.md
  content/rs/security/tls/enable-tls.md
Labels: p_Software
