Repository RedisLabs/redislabs-docs, pull requests merged in 2022-02, with the labels that each got.

#1770 Changelog update January 2022
  changelog.md
Labels: infrastructure

#1017 Add RC API backup parameters
  content/rc/api/examples/back-up-and-import-data.md
Labels: bug, expired, p_Cloud

#1771 DOC-1134: RS "Configure Cluster DNS" includes a malformed link
  content/embeds/cluster-dns-embed.md
Labels: p_Software

#1773 DOC-1137 fix broken link
  content/kubernetes/faqs/_index.md
Labels: bug, K8s

#1772 Added /v2/modules requests to RS REST API
  content/rs/references/rest-api/requests/modules/_index.md
Labels: p_Software

#1774 DOC-920 Connect to prometheus operator
  content/kubernetes/re-clusters/connect-prometheus-operator.md
Labels: next version, K8s

#1780 Upgraded Hugo version in CircleCI config
  .circleci/config.yml
Labels: infrastructure

#1776 Added RedisTimeSeries v1.4.14 release notes
  content/modules/redistimeseries/release-notes/redistimeseries-1.4-release-notes.md
Labels: p_Modules

#1779 DOC-1030: Reorder modules in TOC and other lists
  .circleci/config.yml
  content/embeds/modules.html
  content/modules/enterprise-capabilities.md
  content/modules/redisai/_index.md
  content/modules/redisbloom/_index.md
  content/modules/redisearch/_index.md
  content/modules/redisgears/_index.md
  content/modules/redisgraph/_index.md
  content/modules/redisjson/_index.md
  content/modules/redistimeseries/_index.md
Labels: p_Modules

#1777 Added RediSearch v2.2.7 release notes
  content/modules/redisearch/release-notes/redisearch-2.2-release-notes.md
Labels: p_Modules

#1785 Fix typo for vpc-perring.md document
  content/rc/security/vpc-peering.md
Labels: p_Cloud

#1778 DOC-1131: RS - Arbel release note updates.
  content/rs/release-notes/rs-6-2-10-february-2022.md
  content/rs/release-notes/rs-6-2-8-october-2021.md
Labels: p_Software

#1790 Added RedisGraph v2.8 GA release notes
  content/modules/redisgraph/release-notes/redisgraph-2.8-release-notes.md
Labels: p_Modules

#1789 Added RedisGears v1.2 release notes
  content/modules/redisgears/release-notes/redisgears-1.2-release-notes.md
Labels: p_Modules
