Repository RedisLabs/redislabs-docs, pull requests merged in 2022-09, with the labels that each got.

#2125 Search release notes: fields changed to attributes
  content/modules/redisearch/release-notes/redisearch-2.2-release-notes.md
Labels: p_Modules

#2140 Avoid label selector in operator deployment verification
  content/kubernetes/deployment/quick-start.md
Labels: p_Platforms

#2145 RS: remove duplicated content and comments
  content/rs/databases/active-active/causal-consistency.md
Labels: bug

#2138 DOC-1582: RC GCP Marketplace Subscription article
  content/rc/cloud-integrations/_index.md
  content/rc/cloud-integrations/gcp-marketplace/_index.md
  static/images/rc/gcp-marketplace-billing-badge.png
  static/images/rc/gcp-marketplace-manage-on-provider.png
  static/images/rc/gcp-marketplace-map-account-dialog.png
  static/images/rc/gcp-marketplace-rc-payg-pending-approval.png
  static/images/rc/gcp-marketplace-rc-payg-plan.png
Labels: p_Cloud

#2143 DOC-1607: RC - Update Account Settings screenshot
  static/images/rc/account-settings-account-tab.png
Labels: p_Cloud

#2141 DOC-1561 one node REC not supported
  content/kubernetes/deployment/openshift/openshift-cli.md
  content/kubernetes/deployment/openshift/openshift-operatorhub.md
  content/kubernetes/deployment/quick-start.md
Labels: K8s

#2156 RS - DOC-1616: v6.2.18 release notes and supporting docs
  content/rs/release-notes/rs-6-2-18.md
  content/rs/security/audit-events.md
  content/rs/security/internode-encryption.md
Labels: p_Software

#2162 K8s: update supported distros
  content/kubernetes/reference/supported_k8s_distributions.md
Labels: bug, K8s

#2164 K8s: new RED-75388 wording
  content/kubernetes/release-notes/k8s-6-2-12-1.md
Labels: K8s

#2166 DOC-1641 - RS: "Hero" page should reflect the reorg
  content/rs/_index.md
  layouts/partials/home/options.html
Labels: p_Software

#2167 DOC 1645 - RS: 6.2.18 release note typos
  content/rs/release-notes/rs-6-2-18.md
Labels: p_Software

#2153 SAML SSO updates
  content/rc/security/single-sign-on/saml-sso.md
  static/images/rc/access-management-saml-bind-accounts.png
  static/images/rc/access-management-saml-config.png
  static/images/rc/button-sign-in-sso.png
Labels: p_Cloud

#2160 RC: Custom ports for flexible subscriptions
  content/rc/databases/create-database.md
  static/images/rc/database-new-flexible.png
Labels: p_Cloud

#2157 DOC-1625 fix HAproxy ingress annotations
  content/kubernetes/re-clusters/create-aa-database.md
Labels: K8s

#2158 DOC-1639 OpenShift CLI deployment fixes
  content/kubernetes/deployment/openshift/openshift-cli.md
Labels: bug, K8s

#2172 DOC-1451 - RS: Update Create Replica Of database article
  content/embeds/tls-configuration-procedure.md
  content/rs/databases/import-export/replica-of/create.md
  content/rs/release-notes/rs-6-2-10-february-2022.md
  content/rs/security/certificates/updating-certificates.md
Labels: p_Software

#2173 K8s: DOC-1683 incorrect command to remove replace password
  content/kubernetes/reference/cluster-options.md
  content/kubernetes/security/manage-rec-credentials.md
Labels: bug, K8s

#2174 DOC-1645: Fix typos in 6.2.18 release notes
  content/rs/release-notes/rs-6-2-18.md
Labels: p_Software
