Repository RedisLabs/redislabs-docs, pull requests merged in 2022-10, with the labels that each got.

#2177 RS - crdb-cli create: Remove unsupported parameter.
  content/rs/references/cli-utilities/crdb-cli/crdb/create.md
Labels: p_Software

#2187 RS - 6.2.18 release note typo fix
  content/rs/release-notes/rs-6-2-18.md
Labels: p_Software

#2165 K8s: RoF preview content
  content/kubernetes/re-clusters/redis-on-flash.md
Labels: K8s

#2182 DOC-1690: RS - Update crdb-cli task command reference
  content/rs/references/cli-utilities/crdb-cli/_index.md
  content/rs/references/cli-utilities/crdb-cli/task-status.md
  content/rs/references/cli-utilities/crdb-cli/task/_index.md
  content/rs/references/cli-utilities/crdb-cli/task/cancel.md
  content/rs/references/cli-utilities/crdb-cli/task/list.md
  content/rs/references/cli-utilities/crdb-cli/task/status.md
Labels: p_Software

#2186 DOC-1692 - RS: Update Configure distributed synchronization to include syncer_mode
  content/rs/databases/active-active/synchronization-mode.md
Labels: p_Software

#2180 Data type commands compatibility
  content/rs/references/compatibility/commands/data-types.md
Labels: p_Software, p_Cloud

#2188 Cluster commands compatibility
  content/rs/references/compatibility/commands/cluster.md
Labels: p_Software, p_Cloud

#2191 Connection commands compatibility
  content/rs/references/compatibility/commands/connection.md
Labels: p_Software, p_Cloud

#2195 DOC-1647: Redis on Flash quick start edits
  content/glossary/_index.md
  content/rs/databases/redis-on-flash/getting-started-redis-flash.md
  content/rs/databases/redis-on-flash/rof-quickstart.md
  content/rs/installing-upgrading/get-started-redis-enterprise-software.md
Labels: p_Software

#2199 DOC-1725: Edit RC Quick Start to reflect new workflow
  content/rc/rc-quickstart.md
  content/rc/subscriptions/create-fixed-subscription.md
  static/images/rc/quickstart-database-overview.png
  static/images/rc/quickstart-quick-dialog.png
  static/images/rc/quickstart-subscription-overview.png
Labels: p_Cloud

#2192 Key commands compatibility
  content/rs/references/compatibility/commands/generic.md
Labels: p_Software, p_Cloud

#2193 Pub/sub command compatibility
  content/rs/references/compatibility/commands/pub-sub.md
Labels: p_Software, p_Cloud

#2194 Scripting command compatibility
  content/rs/references/compatibility/commands/scripting.md
Labels: p_Software, p_Cloud

#2196 Transaction commands compatibility
  content/rs/references/compatibility/commands/transactions.md
Labels: p_Software, p_Cloud

#2201 OSS Redis config compatibility
  content/rs/references/compatibility/config-settings.md
Labels: p_Software, p_Cloud

#2205 Build error fix: Typo in VPC peering relref
  content/rc/security/database-security/network-security.md
Labels: p_Cloud

#2202 Link to new compatibility docs & remove Cloud FAQ
  content/rc/_index.md
  content/rc/databases/_index.md
  content/rc/faqs/_index.md
Labels: p_Cloud

#2209 Memory Limits DOC-1444
  content/rs/clusters/optimize/node-memory.md
  content/rs/databases/active-active/planning.md
  content/rs/databases/memory-performance/_index.md
  content/rs/databases/memory-performance/eviction-policy.md
  content/rs/databases/memory-performance/memory-limit.md
  content/rs/installing-upgrading/configuring/linux-swap.md
Labels: p_Software

#2220 RI release notes update
  content/ri/release-notes/v.2.4.0.md
  content/ri/release-notes/v.2.6.0.md
  content/ri/release-notes/v1.12.0.md
  content/ri/release-notes/v1.13.0.md
  content/ri/release-notes/v2.0.md
  content/ri/release-notes/v2.10.0.md
  content/ri/release-notes/v2.12.0.md
  content/ri/release-notes/v2.2.0.md
  content/ri/release-notes/v2.8.0.md
Labels: p_Insight
