Repository RedisLabs/redislabs-docs, pull requests merged in 2022-05, with the labels that each got.

#1901 DOC-1326 - RS CLI Utilities Reorg: rladmin placement command
  content/rs/references/cli-utilities/rladmin/placement.md
Labels: p_Software

#1902 DOC-1328 - RS CLI Utilities Reorg: rladmin restart page
  content/rs/references/cli-utilities/rladmin/restart.md
Labels: p_Software

#1906 Modules: Clarify Redis Stack support
  content/modules/_index.md
  content/modules/enterprise-capabilities.md
  content/modules/redis-stack.md
Labels: p_Modules

#1910 DOC-1361 remove old REDB option
  content/kubernetes/reference/db-options.md
Labels: K8s

#1909 DOC-1350 add redisVersion to db-options page
  content/kubernetes/reference/db-options.md
Labels: K8s

#1908 DOC-1050: RedisJSON Quick Start Rewrite
  content/modules/redisjson/redisjson-quickstart.md
Labels: p_Modules

#1917 DOC-1321: RS CLI Utilities - rladmin suffix
  content/rs/references/cli-utilities/rladmin/suffix.md
Labels: p_Software

#1904 DOC-1304 Kraken release notes
  content/kubernetes/reference/db-options.md
  content/kubernetes/release-notes/k8s-6-2-10-34-2022-05.md
  content/kubernetes/release-notes/k8s-6-2-10-4-2022-03 copy.md
Labels: K8s

#1903 K8s release Kraken 6.2.10-34
  content/kubernetes/reference/cluster-options.md
  content/kubernetes/reference/db-options.md
  content/kubernetes/reference/supported_k8s_distributions.md
  content/kubernetes/release-notes/k8s-6-2-10-34-2022-05.md
  content/kubernetes/release-notes/k8s-6-2-10-4-2022-03 copy.md
Labels: K8s

#1918 DOC-1382: Connect - Preview
  content/connect/_index.md
  layouts/404.html
  layouts/partials/home/options.html
  layouts/partials/menu.html
  static/theme-flex/img/ico-blank-icon.svg
  static/theme-flex/img/ico-connect.svg
Labels: p_Connect

#1919 DOC-1324: RS CLI Reorg - rladmin migrate page
  content/rs/references/cli-utilities/rladmin/migrate.md
Labels: p_Software

#1907 Revised RedisGraph quick start
  content/modules/redisai/redisai-quickstart.md
  content/modules/redisbloom/redisbloom-quickstart.md
  content/modules/redisearch/redisearch-quickstart.md
  content/modules/redisgears/jvm/quickstart.md
  content/modules/redisgears/python/quickstart.md
  content/modules/redisgraph/redisgraph-quickstart.md
  content/modules/redisjson/redisjson-quickstart.md
  content/modules/redistimeseries/redistimeseries-quickstart.md
  static/images/modules/visualize-graph.png
  static/images/ri/icon-run-command.png
  static/images/ri/icon-workbench.png
Labels: p_Modules

#1922 Reorg rladmin cluster commands
  content/rs/references/cli-utilities/rladmin/cluster/_index.md
  content/rs/references/cli-utilities/rladmin/cluster/certificate.md
  content/rs/references/cli-utilities/rladmin/cluster/config.md
  content/rs/references/cli-utilities/rladmin/cluster/create.md
  content/rs/references/cli-utilities/rladmin/cluster/debug_info.md
  content/rs/references/cli-utilities/rladmin/cluster/join.md
  content/rs/references/cli-utilities/rladmin/cluster/recover.md
  content/rs/references/cli-utilities/rladmin/cluster/reset_password.md
  content/rs/references/cli-utilities/rladmin/cluster/running_actions.md
  content/rs/references/cli-utilities/rladmin/cluster/stats_archiver.md
  layouts/shortcodes/table-children.html
Labels: p_Software

#1920 DOC-1325: RS CLI Reorg: rladmin node
  content/rs/references/cli-utilities/rladmin/node/_index.md
  content/rs/references/cli-utilities/rladmin/node/addr.md
  content/rs/references/cli-utilities/rladmin/node/enslave.md
  content/rs/references/cli-utilities/rladmin/node/external-addr.md
  content/rs/references/cli-utilities/rladmin/node/maintenance-mode.md
  content/rs/references/cli-utilities/rladmin/node/recovery-path.md
  content/rs/references/cli-utilities/rladmin/node/remove.md
  content/rs/references/cli-utilities/rladmin/node/snapshot.md
Labels: p_Software

#1923 Added release notes for RedisBloom 2.2.15 and RedisTimeSeries 1.6.10
  content/modules/redisbloom/release-notes/redisbloom-2.2-release-notes.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.6-release-notes.md
Labels: p_Modules

#1924 DOC-1329: RS CLI Utilites Reorg - rladmin upgrade command page
  content/rs/references/cli-utilities/rladmin/upgrade.md
Labels: p_Software

#1925 DOC-1406 correct internal links
  content/rs/databases/configure/edit-delete-db.md
Labels: bug

#1926 DOC-1327: RS CLI Utilities - rladmin recover page
  content/rs/references/cli-utilities/rladmin/recover.md
Labels: p_Software

#1930 DOC-1055: RedisTimeSeries Quick Start
  content/modules/redistimeseries/redistimeseries-quickstart.md
Labels: p_Modules

#1932 Removed name option from rladmin cluster join
  content/rs/references/cli-utilities/rladmin/cluster/join.md
Labels: p_Software

#1933 Added more info to the CLI landing page
  content/rs/references/cli-utilities/_index.md
Labels: p_Software

#1927 DOC-866
  content/rs/installing-upgrading/configuring/cluster-lba-setup.md
Labels: bug

#1939 Added RedisGears v1.2.4 release notes
  content/modules/redisgears/release-notes/redisgears-1.2-release-notes.md
Labels: p_Modules

#1948 Added RediSearch v2.4.6 release notes
  content/modules/redisearch/release-notes/redisearch-2.4-release-notes.md
Labels: p_Modules

#1949 Added release notes for RediSearch v2.4.8, RedisGraph v2.4.14
  content/modules/redisearch/release-notes/redisearch-2.4-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-2.4-release-notes.md
Labels: p_Modules

#1952 RIv2: Fix rn file ext
  content/ri/release-notes/v2.2.0.md
Labels: p_Insight

#1936 DOC-1341: RS - Update LDAP docs to reflect changes
  content/glossary/_index.md
  content/rs/release-notes/rs-6-0-20-april-2021.md
  content/rs/release-notes/rs-6-2-4-august-2021.md
  content/rs/security/ldap/_index.md
  content/rs/security/ldap/cluster-based-ldap-authentication.md
  content/rs/security/ldap/migrate-to-role-based-ldap.md
Labels: p_Software

#1935 DOC-1018: RS - User security admin console settings
  content/rs/security/admin-console-security/user-security.md
  static/images/rs/cluster-settings-preferences.png
Labels: p_Software

#1953 DOC-1397: Connect - Initial docs
  content/connect/_index.md
  content/connect/architecture.md
  content/connect/install.md
  content/connect/upgrade.md
  static/images/connect/redis-connect-architecture.png
  static/images/connect/redis-connect-db-update-available.png
Labels: p_Connect

#1959 DOC-1398: Connect preview - data type conversions
  content/connect/_index.md
  content/connect/architecture.md
  content/connect/data-types/_index.md
  content/connect/install.md
  content/connect/upgrade.md
Labels: p_Connect

#1957 DOC-1432 - RS: Swift is no longer an option for import
  content/rs/databases/import-export/import-data.md
Labels: p_Software
