Repository RedisLabs/redislabs-docs, pull requests merged in 2022-01, with the labels that each got.

#1720 Jira DOC-1087: RC - Update Billing & Payments to include Credits tab
  content/rc/administration/_index.md
  content/rc/administration/billing-history.md
  content/rc/administration/payment-methods.md
  content/rc/billing-and-payments.md
  static/images/rc/billing-billing-history-tab.png
  static/images/rc/billing-payment-method-tab.png
  static/images/rc/billing-payments-credits-tab.png
  static/images/rc/button-billing-payments-apply.png
Labels: p_Cloud

#1726 Added RedisGraph v2.4.13 release notes
  content/modules/redisgraph/release-notes/redisgraph-2.4-release-notes.md
Labels: p_Modules

#1727 Changelog updates for December 2021
  changelog.md
Labels: infrastructure

#1730 RI 2.0.3 changes from commit ca7aa53 on 2.0 release branch
  content/ri/release-notes/v2.0.2.md
Labels: p_Insight

#1732 DOC-1071 refactor K8s release note page
  content/kubernetes/release-notes/_index.md
  content/kubernetes/release-notes/k8s-5-4-10-8-january-2020.md
  content/kubernetes/release-notes/k8s-5-4-14-2-2020-03.md
  content/kubernetes/release-notes/k8s-6-0-12-5-2021-02.md
  content/kubernetes/release-notes/k8s-6-0-20-12-2021-07.md
  content/kubernetes/release-notes/k8s-6-0-20-4-2021-05.md
  content/kubernetes/release-notes/k8s-6-0-6-11-2020-07.md
  content/kubernetes/release-notes/k8s-6-0-6-23-2020-08.md
  content/kubernetes/release-notes/k8s-6-0-6-24-2020-08.md
  content/kubernetes/release-notes/k8s-6-0-6-6-2020-06.md
  content/kubernetes/release-notes/k8s-6-0-8-1-2020-10.md
  content/kubernetes/release-notes/k8s-6-0-8-20-2020-12.md
  content/kubernetes/release-notes/k8s-6-2-4-1-2021-09.md
  content/kubernetes/release-notes/k8s-6-2-8-2-2021-11.md
Labels: K8s

#1716 Revising memory management landing page
  content/embeds/adding-node-embed.md
  content/embeds/hardware-requirements-embed.md
  content/embeds/new-cluster-embed.md
  content/glossary/_index.md
  content/kubernetes/re-clusters/cluster-recovery.md
  content/kubernetes/reference/db-options.md
  content/rc/databases/configuration/data-eviction-policies.md
  content/rc/databases/create-database.md
  content/rc/faqs/_index.md
  content/rc/subscriptions/create-flexible-subscription.md
  content/rs/_index.md
  content/rs/administering/cluster-operations/replacing-node.md
  content/rs/administering/creating-databases/_index.md
  content/rs/administering/creating-databases/create-active-active.md
  content/rs/administering/database-operations/updating-configurations.md
  content/rs/administering/designing-production/performance/_index.md
  content/rs/administering/designing-production/performance/optimization.md
  content/rs/administering/designing-production/performance/shard-placement.md
  content/rs/administering/designing-production/persistent-ephemeral-storage.md
  content/rs/concepts/high-availability/replication.md
  content/rs/concepts/memory-architecture/_index.md
  content/rs/concepts/memory-performance/_index.md
  content/rs/concepts/memory-performance/disk-sizing-heavy-write-scenarios.md
  content/rs/concepts/memory-performance/eviction-policy.md
  content/rs/concepts/memory-performance/memory-limit.md
  content/rs/concepts/memory-performance/memory-management.md
  content/rs/concepts/memory-performance/persistence.md
  content/rs/concepts/memory-performance/redis-flash.md
  content/rs/concepts/memory-performance/shard-placement-policy.md
  content/rs/getting-started/getting-started-redis-flash.md
  content/rs/installing-upgrading/_index.md
  content/rs/installing-upgrading/configuring-aws-instances.md
  content/rs/installing-upgrading/configuring/linux-swap.md
  content/rs/references/rest-api/objects/bdb/dataset_import_sources.md
  content/rs/references/rladmin.md
  content/rs/release-notes/legacy-release-notes/rlec-4-3-aug-2016.md
  content/rs/release-notes/rs-5-6-0-april-2020.md
  content/rs/release-notes/rs-6-0-20-april-2021.md
  content/rs/release-notes/rs-6-0-8-september-2020.md
  content/rs/release-notes/rs-6-0-may-2020.md
Labels: p_Software

#1734 DOC-994 Istio ingress configuration
  content/kubernetes/re-databases/ingress_routing_with_istio.md
Labels: K8s

#1742 DOC-1092 adding Istio section to K8s AA article
  content/kubernetes/re-clusters/create-aa-database.md
  content/kubernetes/re-databases/ingress_routing_with_istio.md
Labels: K8s

#1738 DOC-1091 Intrepid release notes
  content/kubernetes/reference/supported_k8s_distributions.md
  content/kubernetes/release-notes/k8s-6-2-8-10-2022-01.md
Labels: K8s

#1747 DOC-993 added private repo link to quick start prereq
  content/kubernetes/deployment/quick-start.md
Labels: K8s

#1745 Added RedisGears v1.0.9 release notes
  content/modules/redisgears/release-notes/redisgears-1.0-release-notes.md
Labels: p_Modules

#1746 Added RediSearch v2.2.6 release notes
  content/modules/redisearch/release-notes/redisearch-2.2-release-notes.md
Labels: p_Modules

#1713 DOC-1077: Doc new Manager role
  content/glossary/_index.md
  content/rc/administration/access-management.md
  content/rc/administration/account-team-settings.md
  content/rc/security/_index.md
  content/rc/security/admin-console-security/_index.md
  content/rc/security/admin-console-security/user-team-management.md
  content/rc/security/cidr-whitelist.md
  content/rc/security/database-security/_index.md
  content/rc/security/database-security/network-security.md
  content/rc/security/database-security/passwords-users-roles.md
  content/rc/security/encryption-at-rest.md
  content/rc/security/multi-factor-authentication.md
  content/rc/security/shared-responsibility-model.md
  content/rc/security/single-sign-on.md
  content/rc/security/vpc-peering.md
  static/images/rc/access-management-add-user-dialog.png
  static/images/rc/access-management-delete-user-dialog.png
  static/images/rc/access-management-edit-user-dialog.png
  static/images/rc/button-access-management-add-user.png
  static/images/rc/button-access-management-delete-user.png
  static/images/rc/icon-access-management-delete-user.png
  static/images/rc/icon-access-management-edit-user.png
  static/images/rc/icon-list-filter.png
  static/images/rc/icon-list-sort-asc.png
  static/images/rc/icon-list-sort-desc.png
Labels: p_Cloud

#1751 K8s 6.2.8-11 RN update about upgrade failure
  content/kubernetes/release-notes/k8s-6-2-8-11-2022-01.md
Labels: bug, K8s

#1756 K8s: release notes for 6.2.8-15
  content/kubernetes/release-notes/k8s-6-2-8-15-2022-01.md
Labels: K8s

#1763 DOC-1128: RC - Doc Active-Active workflow changes
  content/rc/subscriptions/create-active-active-subscription.md
  static/images/rc/create-database-active-active.png
  static/images/rc/create-flexible-sub-active-active-off.png
  static/images/rc/create-flexible-sub-active-active-on.png
  static/images/rc/create-sub-active-active-cidr.png
  static/images/rc/create-sub-active-active-regions.png
  static/images/rc/icon-cidr-address-error.png
  static/images/rc/icon-cidr-address-ok.png
  static/images/rc/icon-region-delete.png
Labels: p_Cloud

#1765 DOC-1118: RS-Add command-line options to install doc.
  content/rs/installing-upgrading/_index.md
Labels: p_Software

#1767 DOC-1097: RC - Update Monitor Performance article to reflect current UX
  content/rc/databases/monitor-performance.md
  static/images/rc/database-metrics-tab.png
Labels: p_Cloud

#1766 DOC-961: RS - Update images on Getting Started to reflect current UX
  content/embeds/cluster-setup.md
  static/images/rs/rs-setup-new-cluster.png
  static/images/rs/rs-setup-node-config.png
  static/images/rs/rs-setup-set-admin-creds.png
Labels: p_Software

#1758 Redisgears JVM Plugin docs
  content/modules/add-module-to-cluster.md
  content/modules/redisgears/jvm/_index.md
  content/modules/redisgears/jvm/classes/_index.md
  content/modules/redisgears/jvm/classes/gearsbuilder/_index.md
  content/modules/redisgears/jvm/classes/gearsbuilder/accumulate.md
  content/modules/redisgears/jvm/classes/gearsbuilder/accumulateby.md
  content/modules/redisgears/jvm/classes/gearsbuilder/asyncfilter.md
  content/modules/redisgears/jvm/classes/gearsbuilder/asyncforeach.md
  content/modules/redisgears/jvm/classes/gearsbuilder/asyncmap.md
  content/modules/redisgears/jvm/classes/gearsbuilder/callnext.md
  content/modules/redisgears/jvm/classes/gearsbuilder/callnextarray.md
  content/modules/redisgears/jvm/classes/gearsbuilder/collect.md
  content/modules/redisgears/jvm/classes/gearsbuilder/config-get.md
  content/modules/redisgears/jvm/classes/gearsbuilder/count.md
  content/modules/redisgears/jvm/classes/gearsbuilder/creategearsbuilder.md
  content/modules/redisgears/jvm/classes/gearsbuilder/execute.md
  content/modules/redisgears/jvm/classes/gearsbuilder/executearray.md
  content/modules/redisgears/jvm/classes/gearsbuilder/filter.md
  content/modules/redisgears/jvm/classes/gearsbuilder/flatmap.md
  content/modules/redisgears/jvm/classes/gearsbuilder/foreach.md
  content/modules/redisgears/jvm/classes/gearsbuilder/hashtag.md
  content/modules/redisgears/jvm/classes/gearsbuilder/localaccumulateby.md
  content/modules/redisgears/jvm/classes/gearsbuilder/log.md
  content/modules/redisgears/jvm/classes/gearsbuilder/map.md
  content/modules/redisgears/jvm/classes/gearsbuilder/register.md
  content/modules/redisgears/jvm/classes/gearsbuilder/repartition.md
  content/modules/redisgears/jvm/classes/gearsbuilder/run.md
  content/modules/redisgears/jvm/classes/gearsfuture/_index.md
  content/modules/redisgears/jvm/classes/gearsfuture/seterror.md
  content/modules/redisgears/jvm/classes/gearsfuture/setresult.md
  content/modules/redisgears/jvm/classes/readers/_index.md
  content/modules/redisgears/jvm/classes/readers/commandoverrider.md
  content/modules/redisgears/jvm/classes/readers/commandreader.md
  content/modules/redisgears/jvm/classes/readers/javareader.md
  content/modules/redisgears/jvm/classes/readers/keysonlyreader.md
  content/modules/redisgears/jvm/classes/readers/keysreader.md
  content/modules/redisgears/jvm/classes/readers/shardsidreader.md
  content/modules/redisgears/jvm/classes/readers/streamreader.md
  content/modules/redisgears/jvm/commands/_index.md
  content/modules/redisgears/jvm/commands/rg-jdumpsessions.md
  content/modules/redisgears/jvm/commands/rg-jexecute.md
  content/modules/redisgears/jvm/install.md
  content/modules/redisgears/jvm/quickstart.md
  content/modules/redisgears/jvm/recipes/_index.md
  content/modules/redisgears/jvm/recipes/write-behind.md
Labels: p_Modules
