Repository RedisLabs/redislabs-docs, pull requests merged in 2023-09, with the labels that each got.

#2814 K8s: Missing releases from supported distro page
  content/kubernetes/reference/supported_k8s_distributions.md
Labels: K8s, doc_bug

#2754 RS: Troubleshoot DB connectivity guide
  content/rs/databases/connect/troubleshooting-guide.md
Labels: p_Software

#2823 support for tls1.3 with curl
  content/rdi/installation/install-redis-gears.md
Labels: rdi

#2810 RDSC-1493-ingest-quickstrat-prerequisites-redis-enterprise-cluster-version-is-not-correct
  config.toml
  content/rdi/architecture.md
  content/rdi/benchmark.md
  content/rdi/installation/install-k8s.md
  content/rdi/installation/install-offline.md
  content/rdi/installation/install-redis-gears.md
  content/rdi/quickstart/ingest-guide.md
Labels: rdi

#2811 RDSC-1380-scaffold-should-have-a-user-password-for-redis-sink: Auto generated
  content/rdi/reference/cli/redis-di-add-context.md
  content/rdi/reference/cli/redis-di-configure.md
  content/rdi/reference/cli/redis-di-delete.md
  content/rdi/reference/cli/redis-di-deploy.md
  content/rdi/reference/cli/redis-di-describe-job.md
  content/rdi/reference/cli/redis-di-dump-support-package.md
  content/rdi/reference/cli/redis-di-get-rejected.md
  content/rdi/reference/cli/redis-di-list-jobs.md
  content/rdi/reference/cli/redis-di-monitor.md
  content/rdi/reference/cli/redis-di-reset.md
  content/rdi/reference/cli/redis-di-set-secret.md
  content/rdi/reference/cli/redis-di-start.md
  content/rdi/reference/cli/redis-di-status.md
  content/rdi/reference/cli/redis-di-stop.md
  content/rdi/reference/cli/redis-di-trace.md
  content/rdi/reference/cli/redis-di-upgrade.md
  content/rdi/reference/config-yaml-reference.md
  content/rdi/reference/debezium/cassandra.md
  content/rdi/reference/debezium/mongodb.md
  content/rdi/reference/debezium/mysql.md
  content/rdi/reference/debezium/oracle.md
  content/rdi/reference/debezium/postgresql.md
  content/rdi/reference/debezium/sqlserver.md
Labels: rdi

#2784 RDSC-1456 Add default job information
  content/rdi/data-transformation/data-transformation-pipeline.md
  content/rdi/quickstart/ingest-guide.md
Labels: rdi

#2820 RS: Fix outdated test DB connections examples
  content/rs/databases/connect/test-client-connectivity.md
Labels: p_Software

#2818 RS: Add units to config compatibility descriptions
  content/rs/references/compatibility/config-settings.md
Labels: p_Software

#2815 RS: Update recommended clients with Sentinel support
  content/rs/databases/connect/supported-clients-browsers.md
Labels: p_Software

#2824 RS: More info for rladmin node snapshot reference
  content/rs/references/cli-utilities/rladmin/node/snapshot.md
Labels: p_Software

#2808 RS: Add Prometheus ports 8000 & 9090 to ports table
  content/rs/networking/port-configurations.md
Labels: p_Software

#2826 Update config.toml
  config.toml
Labels: rdi

#2830 RS: Remove tutorial mention from REST API index's certificates section
  content/rs/references/rest-api/_index.md
Labels: p_Software

#2828 RS: Multiple IP addresses syntax in rladmin cluster create/join reference
  content/rs/references/cli-utilities/rladmin/cluster/create.md
  content/rs/references/cli-utilities/rladmin/cluster/join.md
Labels: p_Software

#2825 RS 7.2.4 September maintenance release
  content/rs/references/cli-utilities/rladmin/cluster/config.md
  content/rs/references/rest-api/objects/cluster/_index.md
  content/rs/references/rest-api/objects/node.md
  content/rs/references/rest-api/requests/license/_index.md
  content/rs/release-notes/rs-7-2-4-releases/_index.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-64.md
Labels: p_Software

#2834 RS: Update CVEs in 7.2.4-52 release notes
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52.md
Labels: p_Software

#2829 Update prometheus-metrics-definitions.md
  content/rs/clusters/monitoring/prometheus-metrics-definitions.md
  content/rs/security/certificates/monitor-certificates.md
Labels: p_Software

#2832 DOC-2666: Amazon Bedrock Integration Phase 1
  content/rc/cloud-integrations/aws-marketplace/aws-bedrock.md
Labels: p_Cloud

#2835 DOC-2236 and DOC-2725: Fixed subscription limits need to be clearer & New subscription screenshots
  content/rc/subscriptions/create-fixed-subscription.md
  static/images/rc/new-subscription-plans-flexible.png
  static/images/rc/subscription-new-plan-options.png
Labels: p_Cloud

#2841 Update modules lifecycle CSVs
  static/tables/redisbloom-lifecycle.csv
  static/tables/redisearch-lifecycle.csv
  static/tables/redisjson-lifecycle.csv
  static/tables/redistimeseries-lifecycle.csv
Labels: p_Modules

#2836 RS: Moved clusters above databases in ToC
  content/rs/clusters/_index.md
Labels: p_Software

#2840 K8s: formatting fix
  content/kubernetes/delete_custom_resources.md
Labels: typos/format, K8s

#2847 Update redisgraph-2.10-release-notes.md
  content/stack/release-notes/redisgraph/redisgraph-2.10-release-notes.md
Labels: p_Modules

#2843 RS: Removed unavailable crdb-cli task cancel from v6.2 docs
  content/rs/references/cli-utilities/crdb-cli/task/_index.md
  content/rs/references/cli-utilities/crdb-cli/task/cancel.md
Labels: p_Software, doc_bug

#2838 RS: Copy certificate to client machine for redis-cli mTLS
  content/rs/references/cli-utilities/redis-cli/_index.md
Labels: p_Software

#2805 RS: New change internal IP procedure
  content/rs/networking/multi-ip-ipv6.md
  content/rs/references/cli-utilities/rladmin/node/addr.md
Labels: p_Software

#2842 RDSC-1499: support for redis lookup transformation block
  content/rdi/reference/data-transformation-block-types/lookup.md
Labels: rdi

#2839 RDSC-1510-add-message-to-scaffold-about-table-name-conventions-in-query-override-property: Auto generated
  content/rdi/reference/debezium/mysql.md
  content/rdi/reference/debezium/oracle.md
  content/rdi/reference/debezium/postgresql.md
  content/rdi/reference/debezium/sqlserver.md
Labels: rdi

#2851 DOC-2478: K8s: Backslash in reapplying security context command
  content/kubernetes/re-clusters/upgrade-redis-cluster.md
Labels: K8s

#2850 Update port-configurations.md
  content/rs/networking/port-configurations.md
Labels: p_Software

#2852 RS: Copy supported platforms to references & update limitations
  content/embeds/supported-platforms-embed.md
  content/rs/references/supported-platforms.md
Labels: p_Software

#2844 RDSC-1514: Convert RDI CLI pod definition to deployment
  content/rdi/installation/install-k8s.md
Labels: rdi

#2837 DOC-2578-copy-edit-rpb
  content/rdi/_index.md
  content/rdi/architecture.md
  content/rdi/benchmark.md
  content/rdi/data-transformation/_index.md
  content/rdi/data-transformation/data-denormalization.md
  content/rdi/data-transformation/data-transformation-pipeline.md
  content/rdi/data-transformation/data-type-handling.md
  content/rdi/data-transformation/examples/foreach-example.md
  content/rdi/data-transformation/examples/multiple-targets-example.md
  content/rdi/data-transformation/examples/redis-hash-example.md
  content/rdi/data-transformation/examples/redis-json-example.md
  content/rdi/data-transformation/examples/redis-set-example.md
  content/rdi/data-transformation/examples/redis-sorted-set-example.md
  content/rdi/data-transformation/examples/redis-stream-example.md
  content/rdi/data-transformation/examples/write-behind-to-redis-example.md
  content/rdi/installation/adding-tables-to-existing-pipeline.md
  content/rdi/installation/debezium-server-configuration.md
  content/rdi/installation/debezium-server-deployment.md
  content/rdi/installation/distributed-installation.md
  content/rdi/installation/install-k8s.md
  content/rdi/installation/install-offline.md
  content/rdi/installation/install-rdi-cli.md
  content/rdi/installation/install-redis-gears.md
  content/rdi/installation/multiple-debezium-connectors.md
  content/rdi/installation/pacemaker.md
  content/rdi/monitoring-guide.md
  content/rdi/quickstart/ingest-guide.md
  content/rdi/quickstart/write-behind-guide.md
  content/rdi/troubleshoot.md
  content/rdi/upgrade.md
  content/rdi/write-behind/configuration-guide.md
Labels: rdi

#2857 Update redisjson-2.6-release-notes.md
  content/stack/release-notes/redisjson/redisjson-2.6-release-notes.md
Labels: p_Modules

#2775 docs review
  content/embeds/k8s-admission-webhook-cert.md
  content/kubernetes/delete_custom_resources.md
  content/kubernetes/re-clusters/multi-namespace.md
Labels: K8s
