Repository RedisLabs/redislabs-docs, pull requests merged in 2023-08, with the labels that each got.

#2721 Update redis_acl.md
  content/rs/references/rest-api/objects/redis_acl.md
Labels: p_Software

#2719 RS: Update private/public DB endpoints for new UI
  content/rs/networking/private-public-endpoints.md
  static/images/rs/screenshots/cluster/setup/enable-public-endpoints.png
  static/images/rs/screenshots/databases/config-general-endpoints.png
Labels: p_Software

#2693 RS: Update manage users & passwords for new UI
  content/rs/security/access-control/manage-passwords/password-complexity-rules.md
  content/rs/security/access-control/manage-passwords/password-expiration.md
  content/rs/security/access-control/manage-users/add-users.md
  content/rs/security/access-control/manage-users/default-user.md
  static/images/rs/screenshots/databases/security-access-control-acl-only.png
  static/images/rs/screenshots/databases/security-access-control-password-only.png
Labels: p_Software

#2709 RS: Update install and add modules for new UI
  content/stack/install/add-module-to-cluster.md
  content/stack/install/add-module-to-database.md
  content/stack/install/upgrade-module.md
  static/images/rs/screenshots/databases/quick-db-modules.png
Labels: p_Software, p_Modules

#2704 RS: Update logs, cluster, nodes for new UI
  content/rs/clusters/add-node.md
  content/rs/clusters/logging/_index.md
  content/rs/clusters/logging/redis-slow-log.md
  content/rs/clusters/new-cluster-setup.md
  content/rs/clusters/remove-node.md
  content/rs/installing-upgrading/creating-support-package.md
  content/rs/references/cli-utilities/redis-cli/_index.md
  static/images/rs/screenshots/cluster/cluster-logs.png
  static/images/rs/screenshots/create-support-package.png
Labels: p_Software

#2689 RDSC-1396 `from_entries`, `to_entries` and `filter_entries` custom JMESPath functions
  content/rdi/reference/jmespath-custom-functions.md
Labels: rdi

#2716 Maintenance Windows
  content/rc/security/access-control/access-management.md
  content/rc/subscriptions/create-flexible-subscription.md
  content/rc/subscriptions/maintenance/_index.md
  content/rc/subscriptions/maintenance/set-maintenance-windows.md
  content/rc/subscriptions/view-flexible-subscription.md
  static/images/rc/subscriptions-set-maintenance-window.png
Labels: p_Cloud

#2708 Stack: Added deprecation banner to RedisGraph release notes
  content/stack/release-notes/redisgraph/_index.md
Labels: p_Modules

#2737 RS: RESP3 support - policy flag
  content/rs/references/cli-utilities/rladmin/tune.md
  content/rs/references/compatibility/resp.md
  content/rs/references/rest-api/objects/bdb/_index.md
  content/rs/references/rest-api/objects/cluster_settings.md
Labels: p_Software

#2736 Triggers and functions landing page
  content/stack/enterprise-capabilities.md
  content/stack/triggers-functions/_index.md
Labels: p_Modules

#2700 RS: Update Linux & Docker quickstarts for new UI
  content/embeds/cluster-setup.md
  content/embeds/quick-db-setup.md
  content/rs/installing-upgrading/quickstarts/docker-quickstart.md
  content/rs/installing-upgrading/quickstarts/redis-enterprise-software-quickstart.md
  static/images/rs/icons/db-active-icon.png
  static/images/rs/screenshots/cluster/setup/admin-credentials.png
  static/images/rs/screenshots/cluster/setup/cluster-license-key.png
  static/images/rs/screenshots/cluster/setup/config-cluster.png
  static/images/rs/screenshots/cluster/setup/create-cluster.png
  static/images/rs/screenshots/databases/db-screen.png
  static/images/rs/screenshots/databases/quick-db.png
Labels: p_Software

#2738 RS: Update log rotation
  content/rs/clusters/logging/log-security.md
Labels: p_Software

#2743 Update redisearch-2.6-release-notes.md
  content/stack/release-notes/redisearch/redisearch-2.6-release-notes.md
Labels: p_Modules

#2732 K8s: correct webhook steps
  content/embeds/k8s-admission-webhook-cert.md
  content/kubernetes/deployment/openshift/openshift-cli.md
Labels: K8s, doc_bug

#2741 RC: maintenance windows feedback updates
  content/rc/subscriptions/maintenance/_index.md
Labels: p_Cloud

#2747 Updating Redis Stack 7.2 features
  content/rs/release-notes/rs-7-2-releases/rs-7-2-tba.md
Labels: p_Software

#2749 K8s: remove speedb option from RS release branch
  content/kubernetes/re-clusters/auto-tiering.md
Labels: K8s

#2718 RS: Everest release notes draft
  content/embeds/r7.2-combined-breaking-changes.md
  content/embeds/r7.2-known-limitations.md
  content/embeds/supported-platforms-embed.md
  content/rc/changelog/june-2023.md
  content/rs/references/rest-api/objects/user.md
  content/rs/references/rest-api/requests/users/_index.md
  content/rs/release-notes/rs-7-2-releases/_index.md
  content/rs/release-notes/rs-7-2-releases/rs-7-2-tba.md
Labels: p_Software

#2742 RS: API deprecations & updates
  content/rs/references/rest-api/objects/bdb/_index.md
  content/rs/references/rest-api/objects/cluster/_index.md
  content/rs/references/rest-api/objects/cluster_settings.md
  content/rs/references/rest-api/objects/crdb/database_config.md
  content/rs/references/rest-api/objects/db_alerts_settings/_index.md
  content/rs/references/rest-api/objects/job_scheduler/_index.md
  content/rs/references/rest-api/objects/job_scheduler/redis_cleanup_job_settings.md
  content/rs/references/rest-api/objects/node.md
  content/rs/references/rest-api/objects/user.md
  content/rs/references/rest-api/requests/modules/_index.md
  content/stack/install/add-module-to-cluster.md
Labels: p_Software

#2664 Update RS version dropdown - 6.2-build branch
  layouts/404.html
  layouts/partials/flex/body-beforecontent.html
  layouts/partials/flex/scripts.html
Labels: infrastructure, p_Software

#2663 Update RS version dropdown - 6.0-build branch
  layouts/404.html
  layouts/partials/flex/body-beforecontent.html
  layouts/partials/flex/scripts.html
Labels: infrastructure, p_Software

#2705 RDSC-1404-key-name-for-nesting-not-constructed-correctly
  content/rdi/data-transformation/data-denormalization.md
Labels: rdi

#2707 RDSC-1359: support for mapping in JSON
  content/rdi/reference/data-transformation-block-types/redis_write.md
Labels: rdi

#2744 Distinguish between official clients & community clients
  content/rs/references/client_references/_index.md
  content/rs/references/client_references/client_c.md
  content/rs/references/client_references/client_csharp.md
  content/rs/references/client_references/client_drupal.md
  content/rs/references/client_references/client_ioredis.md
  content/rs/references/client_references/client_java.md
  content/rs/references/client_references/client_nodejs.md
  content/rs/references/client_references/client_php.md
  content/rs/references/client_references/client_python.md
  content/rs/references/client_references/client_ruby.md
Labels: p_Software

#2752 Fix triggers and functions links in August changelog
  content/rc/changelog/august-2023.md
Labels: p_Cloud

#2735 RDSC-1446-Pacemaker-setup-must-include-the-reuse-so-we-don-t-lose-the…
  content/rdi/installation/pacemaker.md
Labels: rdi, doc_bug

#2710 RDSC-1367-replace-all-download-link-in-preview-docs-with-a-var
  config.toml
  content/rdi/benchmark.md
  content/rdi/installation/debezium-server-deployment.md
  content/rdi/installation/install-offline.md
  content/rdi/installation/install-rdi-cli.md
  content/rdi/quickstart/ingest-guide.md
  content/rdi/upgrade.md
Labels: rdi

#2703 RDSC-1415: applier-should-use-keyspace-property-for-job-matching-in-cassandra
  content/rdi/data-transformation/data-transformation-pipeline.md
  content/rdi/data-transformation/examples/multiple-targets-example.md
  content/rdi/data-transformation/examples/redis-hash-example.md
  content/rdi/data-transformation/examples/redis-json-example.md
Labels: rdi

#2759 Fix 7.2 version number in supported platforms table
  content/embeds/supported-platforms-embed.md
Labels: p_Software, doc_bug

#2753 RS: Fix OSS compatibility versions in release notes
  content/rs/release-notes/rs-6-4-2-releases/_index.md
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-30.md
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-43.md
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-61.md
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-69.md
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-81.md
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-94.md
Labels: p_Software

#2595 Update configure-acl.md
  content/rs/security/access-control/rbac/configure-acl.md
Labels: p_Software

#2746 DOC-2610 K8s: Expand supported distribution page
  content/kubernetes/reference/supported_k8s_distributions.md
  layouts/shortcodes/table-scrollable.html
Labels: enhancement, K8s

#2745 RDSC-876: builtin-rdi-monitor
  content/rdi/monitoring-guide.md
  static/images/rdi/monitoring-architecture.png
  static/images/rdi/monitoring-diagram.png
Labels: rdi

#2767 RDSC-876-builtin-rdi-monitor-fixes
  content/rdi/monitoring-guide.md
Labels: rdi

#2776 rdi download from latest
  config.toml
Labels: rdi

#2763 K8s: 7.2.4-2 release notes and supported distributions
  content/kubernetes/reference/supported_k8s_distributions.md
  content/kubernetes/release-notes/7-2-4-releases/7-2-4-2.md
  content/kubernetes/release-notes/7-2-4-releases/_index.md
Labels: next version, K8s

#2760 RS: Generalize virtualization platform section
  content/embeds/supported-platforms-embed.md
Labels: p_Software

#2779 K8s: 7.2.4-2 Quartz release docs
  content/kubernetes/deployment/_index.md
  content/kubernetes/deployment/openshift/_index.md
  content/kubernetes/deployment/openshift/openshift-cli.md
  content/kubernetes/deployment/openshift/openshift-operatorhub.md
  content/kubernetes/faqs/_index.md
  content/kubernetes/memory/_index.md
  content/kubernetes/re-clusters/auto-tiering.md
  content/kubernetes/re-clusters/cluster-recovery.md
  content/kubernetes/re-clusters/upgrade-redis-cluster.md
  content/kubernetes/recommendations/_index.md
  content/kubernetes/recommendations/node-resources.md
  content/kubernetes/recommendations/node-selection.md
  content/kubernetes/recommendations/persistent-volumes.md
  content/kubernetes/recommendations/pod-stability.md
  content/kubernetes/recommendations/sizing-on-kubernetes.md
  content/kubernetes/reference/supported_k8s_distributions.md
  content/kubernetes/release-notes/7-2-4-releases/7-2-4-2.md
  content/kubernetes/release-notes/7-2-4-releases/_index.md
Labels: K8s

#2771 k8s version selector for 6.4 branch
  layouts/404.html
  layouts/partials/flex/body-beforecontent.html
Labels: infrastructure, K8s, hold-off

#2770 k8s version selector for 7.2 latest branch
  layouts/404.html
  layouts/partials/flex/body-beforecontent.html
Labels: infrastructure, K8s, hold-off

#2782 remove old gears links
  content/rdi/installation/install-redis-gears.md
Labels: rdi

#2780 RDSC-1381-add-duplicate-counter-if-dedup-is-used: Auto generated
  content/rdi/reference/cli/_index.md
  content/rdi/reference/config-yaml-reference.md
  content/rdi/reference/data-transformation-block-types/redis_write.md
  content/rdi/reference/debezium/mysql.md
  content/rdi/reference/debezium/postgresql.md
  content/rdi/reference/debezium/sqlserver.md
Labels: rdi

#2783 RS: Cluster recovery with manually uploaded modules (7.2.4 release notes)
  content/rs/release-notes/rs-7-2-4-releases/_index.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52.md
Labels: p_Software

#2787 fixed gears links
  content/rdi/installation/install-redis-gears.md
Labels: rdi

#2790 K8s: Quartz release - remove OLM warning
  content/kubernetes/release-notes/7-2-4-releases/7-2-4-2.md
Labels: K8s

#2788 update architecture
  content/rdi/architecture.md
Labels: rdi

#2793 K8s: cluster recovery with modules - changes to highlights and known limitations
  content/kubernetes/release-notes/7-2-4-releases/7-2-4-2.md
  content/kubernetes/release-notes/7-2-4-releases/_index.md
Labels: bug, K8s

#2794 K8s: modules limitation - add warning to recover and upgrade pages
  content/kubernetes/re-clusters/cluster-recovery.md
  content/kubernetes/re-clusters/upgrade-redis-cluster.md
Labels: bug, K8s

#2769 RS: Fix accept_servers description in node REST API object
  content/rs/references/rest-api/objects/node.md
Labels: p_Software

#2785 RS: rladmin cluster master reference
  content/rs/references/cli-utilities/rladmin/cluster/master.md
Labels: p_Software

#2739 RS REST API: Add missing BDB object attribute for replica buffer
  content/rs/references/rest-api/objects/bdb/_index.md
Labels: p_Software

#2796 K8s: module doc changes
  content/embeds/k8s-642-redb-admission-webhook-name-change.md
  content/embeds/k8s-admission-webhook-cert.md
  content/kubernetes/re-clusters/cluster-recovery.md
  content/kubernetes/re-clusters/upgrade-redis-cluster.md
  content/kubernetes/release-notes/7-2-4-releases/7-2-4-2.md
Labels: bug, K8s

#2797 K8s: correct openshift image number
  content/kubernetes/release-notes/6-4-2-releases/6-4-2-8.md
Labels: typos/format, K8s

#2802 DOC-2657: Add notes clarifying refunds and charging policies
  content/rc/billing-and-payments.md
  content/rc/databases/delete-database.md
Labels: p_Cloud

#2800 K8s: release note updates
  content/kubernetes/_index.md
  content/kubernetes/release-notes/7-2-4-releases/7-2-4-2.md
  content/kubernetes/release-notes/7-2-4-releases/_index.md
Labels: K8s, doc_bug

#2807 Update rs-7-2-4-52.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52.md
Labels: p_Software

#2804 RS: Remove saslauthd from REST API object
  content/rs/references/rest-api/objects/services_configuration/_index.md
  content/rs/references/rest-api/objects/services_configuration/saslauthd.md
Labels: p_Software

#2812 Stack: Update module versions in release notes index table
  content/stack/release-notes/redisbloom/_index.md
  content/stack/release-notes/redisearch/_index.md
  content/stack/release-notes/redisjson/_index.md
  content/stack/release-notes/redistimeseries/_index.md
Labels: p_Modules
