Repository RedisLabs/redislabs-docs, pull requests merged in 2023-10, with the labels that each got.

#2848 DOC-2566: SAML Account linking changes
  content/rc/changelog/october-2023.md
  content/rc/security/access-control/saml-sso/_index.md
  static/images/rc/saml/button-saml-link-account.png
  static/images/rc/saml/popup-saml-convert-users.png
  static/images/rc/saml/popup-saml-get-token.png
Labels: p_Cloud, hold-off

#2845 DOC-2602: CSV Cost Report Download changes
  content/embeds/rc-cost-report-csv.md
  content/rc/billing-and-payments.md
  content/rc/changelog/october-2023.md
  content/rc/databases/usage-reports.md
  static/images/rc/button-cost-report-download.png
Labels: p_Cloud, hold-off

#2864 Update redistimeseries-1.10-release-notes.md
  content/stack/release-notes/redistimeseries/redistimeseries-1.10-release-notes.md
Labels: p_Modules

#2859 Create v.2.34.0.md
  content/ri/release-notes/v.2.34.0.md
Labels: p_Insight

#2863 RS: TLS improvements for new UI
  content/embeds/replica-of-tls-config.md
  content/rs/security/tls/enable-tls.md
  static/images/rs/screenshots/databases/security-mtls-add-cert-validation-multi-ou.png
  static/images/rs/screenshots/databases/security-mtls-clients.png
  static/images/rs/screenshots/databases/security-tls-replica-of.png
Labels: p_Software

#2831 K8s: 7.2.4 main release notes
  content/kubernetes/reference/supported_k8s_distributions.md
  content/kubernetes/release-notes/7-2-4-releases/7-2-4-7.md
Labels: K8s

#2855 RS: Configure DB defaults in new UI
  content/rs/databases/configure/db-defaults.md
  content/rs/databases/configure/replica-ha.md
  content/rs/security/internode-encryption.md
Labels: p_Software

#2856 RS: User lockout parameters & session timeout in new UI
  content/rs/security/access-control/manage-users/login-lockout.md
  static/images/rs/screenshots/cluster/security-preferences-lockout-threshold.png
Labels: p_Software

#2871 RS: Fixed /bdbs/stats/last/uid endpoint
  content/rs/references/rest-api/requests/bdbs/stats/last.md
Labels: p_Software

#2873 RS: Standard hashing policy behaves differently from OSS Redis for multiple hash tags
  content/rs/databases/durability-ha/clustering.md
Labels: p_Software

#2877 RS: Fixed typos & issue numbers in RS 7.2.4 release notes
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-72.md
Labels: p_Software

#2878 K8s: add upgrade RHEL note
  content/kubernetes/release-notes/7-2-4-releases/7-2-4-7.md
Labels: bug, K8s

#2875 K8s small doc bugs
  content/kubernetes/delete-custom-resources.md
  content/kubernetes/deployment/container-images.md
  content/kubernetes/re-databases/db-controller.md
Labels: K8s, doc_bug

#2881 DOC-2568: Transit Gateway Documentation
  content/rc/security/aws-transit-gateway.md
  static/images/rc/aws-tgw-add-principal.png
  static/images/rc/tgw-accept-resource-shares.png
  static/images/rc/tgw-add-additional-cidrs-button.png
  static/images/rc/tgw-add-cidrs-button.png
  static/images/rc/tgw-attachment-more-actions-menu.png
  static/images/rc/tgw-create-attachment-button.png
  static/images/rc/tgw-producer-cidr-copy.png
  static/images/rc/tgw-resource-shares-button.png
  static/images/rc/tgw-share-transit-gateway.png
Labels: p_Cloud

#2853 RDSC-1550-change-value-of-property-log-mining-transaction-retention-ms: Auto generated
  content/rdi/reference/data-transformation-block-types/lookup.md
  content/rdi/reference/debezium/oracle.md
Labels: rdi

#2879 Use RedisGears 1.2.7
  config.toml
  content/rdi/installation/install-k8s.md
  content/rdi/quickstart/write-behind-guide.md
Labels: rdi

#2883 RS: Value ranges for rladmin tune proxy parameters
  content/rs/references/cli-utilities/rladmin/tune.md
Labels: p_Software

#2884 RS: Reorg REST API encryption & admin console security edits
  content/rs/references/rest-api/encryption.md
  content/rs/security/admin-console-security/_index.md
Labels: p_Software

#2846 K8s: improvements to upgrade
  content/kubernetes/deployment/openshift/_index.md
  content/kubernetes/re-clusters/multi-namespace.md
  content/kubernetes/re-databases/_index.md
  content/kubernetes/release-notes/6-2-18-releases/_index.md
  content/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-3.md
  content/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-41-jan-2023.md
  content/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-41.md
  content/kubernetes/release-notes/6-4-2-releases/6-4-2-5.md
  content/kubernetes/release-notes/6-4-2-releases/6-4-2-6.md
  content/kubernetes/release-notes/6-4-2-releases/6-4-2-8.md
  content/kubernetes/release-notes/6-4-2-releases/_index.md
  content/kubernetes/release-notes/6-4-2-releases/k8s-6-4-2-4.md
  content/kubernetes/release-notes/7-2-4-releases/7-2-4-2.md
  content/kubernetes/release-notes/7-2-4-releases/_index.md
  content/kubernetes/release-notes/previous-releases/k8s-5-4-10-8.md
  content/kubernetes/release-notes/previous-releases/k8s-6-0-12-5.md
  content/kubernetes/release-notes/previous-releases/k8s-6-0-20-4.md
  content/kubernetes/release-notes/previous-releases/k8s-6-0-6-11.md
  content/kubernetes/release-notes/previous-releases/k8s-6-0-6-23.md
  content/kubernetes/release-notes/previous-releases/k8s-6-0-6-24.md
  content/kubernetes/release-notes/previous-releases/k8s-6-0-6-6.md
  content/kubernetes/release-notes/previous-releases/k8s-6-0-8-1.md
  content/kubernetes/release-notes/previous-releases/k8s-6-0-8-20.md
  content/kubernetes/upgrade/_index.md
  content/kubernetes/upgrade/openshift-cli.md
  content/kubernetes/upgrade/upgrade-redis-cluster.md
Labels: enhancement, K8s

#2887 RDSC-1614 - Header appears twice in `config.yaml` reference document: Auto generated
  content/rdi/reference/config-yaml-reference.md
Labels: bug, rdi

#2890 K8s: correct rancher table format
  content/kubernetes/reference/supported_k8s_distributions.md
Labels: K8s, doc_bug

#2882 DOC-2933: mark RI pages as deprecated
  content/ri/_index.md
Labels: p_Insight

#2891 RS: Fixed GPG key file download link
  content/rs/installing-upgrading/install/GPG-KEY-redislabs-packages.gpg
  content/rs/installing-upgrading/install/install-on-linux.md
Labels: p_Software

#2849 DOC-2452: Add more information on the "Back up data" page
  content/rc/databases/back-up-data.md
  content/rc/databases/import-data.md
Labels: p_Cloud

#2898 RDSC-1617-add-rac-nodes-to-oracle-scaffold: Auto generated
  content/rdi/reference/debezium/oracle.md
Labels: rdi

#2893 Fixed version selector to keep the full URL path instead of trimming it to the base path
  layouts/partials/flex/body-beforecontent.html
Labels: infrastructure, p_Software, K8s, rdi

#2896 6.0: Fixed version selector to keep the full URL path instead of trimming it
  layouts/partials/flex/body-beforecontent.html
Labels: infrastructure, p_Software

#2895 6.2: Fixed version selector to keep the full URL path instead of trimming it
  layouts/partials/flex/body-beforecontent.html
Labels: infrastructure, p_Software

#2894 6.4: Fixed version selector to keep the full URL path instead of trimming it
  layouts/partials/flex/body-beforecontent.html
Labels: infrastructure, p_Software, K8s

#2897 rdi-preview: Fixed version selector to keep the full URL path instead of trimming it
  layouts/partials/flex/body-beforecontent.html
Labels: infrastructure, rdi

#2886 DOC-2804 hidden TAS docs
  content/tas/_index.md
  content/tas/backup.md
  content/tas/installing.md
  content/tas/modules.md
  content/tas/release-notes.md
  content/tas/using.md
  static/images/tas/pcf_add-to-dash_tile.png
  static/images/tas/pcf_add_license.png
  static/images/tas/pcf_apps_config_create.png
  static/images/tas/pcf_apps_config_create_bf.png
  static/images/tas/pcf_apps_marketplace.png
  static/images/tas/pcf_apps_service_plan.png
  static/images/tas/pcf_apps_service_plans.png
  static/images/tas/pcf_config-success_tile.png
  static/images/tas/pcf_import-product_tile.png
  static/images/tas/pcf_ops_service_plan.png
  static/images/tas/pcf_ops_service_plan_created.png
  static/images/tas/pcf_ops_service_plan_created_bf.png
  static/images/tas/pcf_pre-install_tile.png
  static/images/tas/pcf_rc_loggregator.png
  static/images/tas/pcf_resource_config.png
  static/images/tas/pcf_rp_config_cert1.png
  static/images/tas/pcf_rp_config_cert2.png
  static/images/tas/pcf_rp_config_cert3.png
  static/images/tas/pcf_rp_config_cert4.png
  static/images/tas/pcf_rp_config_full_screen.png
  static/images/tas/pcf_rp_config_full_screen2.png
  static/images/tas/pcf_rp_config_routing.png
  static/images/tas/pcf_service_plans.png
  static/images/tas/post-install-dashboard.png
Labels: enhancement

#2892 DOC-2769: replica of between different SM account require open a support ticket
  content/rc/databases/migrate-databases.md
Labels: p_Cloud

#2901 Create v.2.36.0.md
  content/ri/release-notes/v.2.36.0.md
Labels: p_Insight
