Repository RedisLabs/redislabs-docs, pull requests merged in 2023-07, with the labels that each got.

#2655 Update replica-ha.md
  content/rs/databases/configure/replica-ha.md
Labels: p_Software

#2643 Release notes for 2.28.0
  content/ri/release-notes/v2.28.0.md
Labels: p_Insight

#2656 Update modules-release-notes.md
  content/modules/redisearch/release-notes/redisearch-2.6-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-2.10-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-2.8-release-notes.md
  content/modules/redisjson/release-notes/redisjson-2.4-release-notes.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.8-release-notes.md
  static/tables/redisgraph-lifecycle.csv
Labels: p_Modules

#2641 DOC-2352: Add documentation for 7.2 Fixed Opt-in
  content/rc/subscriptions/create-fixed-subscription.md
  static/images/rc/subscription-new-cloud-vendor-options-redis-7-preview.png
  static/images/rc/subscription-new-redis-7-preview-toggle.png
Labels: p_Cloud, hold-off

#2657 Renamed previous features to deprecated features
  content/rc/subscriptions/create-flexible-subscription.md
  content/ri/_index.md
  content/stack/deprecated-features/_index.md
  content/stack/deprecated-features/graph/_index.md
  content/stack/deprecated-features/graph/commands.md
  content/stack/deprecated-features/graph/config.md
  content/stack/deprecated-features/graph/graph-quickstart.md
  content/stack/enterprise-capabilities.md
Labels: p_Modules

#2659 Remove conflicting alias
  content/stack/deprecated-features/_index.md
Labels: p_Modules

#2665 capitalize URI
  content/kubernetes/re-databases/replica-redb.md
Labels: typos/format

#2667 DOC-2464 RS 6.2.12 CVE update
  content/rs/release-notes/rs-6-2-12.md
Labels: p_Software

#2635 redis-cli TLS connections
  content/rs/references/cli-utilities/redis-cli/_index.md
Labels: p_Software, p_Cloud

#2654 DOC-1586: Add Terraform to the documentation
  content/rc/cloud-integrations/terraform/_index.md
  content/rc/cloud-integrations/terraform/get-started.md
Labels: p_Cloud

#2670 Update release-notes.md
  content/stack/release-notes/redisgraph/redisgraph-2.10-release-notes.md
  content/stack/release-notes/redistimeseries/redistimeseries-1.8-release-notes.md
Labels: p_Modules

#2652 RS: Update databases for new UI part 2
  content/rs/databases/configure/_index.md
  content/rs/databases/create.md
Labels: p_Software

#2671 Merge reviewed UI updates into Everest release branch
  content/rs/clusters/configure/cluster-settings.md
  content/rs/clusters/configure/license-keys.md
  content/rs/clusters/monitoring/_index.md
  content/rs/clusters/replace-node.md
  content/rs/databases/configure/_index.md
  content/rs/databases/configure/database-persistence.md
  content/rs/databases/create.md
  content/rs/databases/delete.md
  content/rs/databases/import-export/export-data.md
  content/rs/databases/import-export/import-data.md
  content/rs/databases/import-export/schedule-backups.md
  static/images/rs/buttons/button-toggle-actions.png
  static/images/rs/icon_warning.png
  static/images/rs/icons/icon_warning.png
  static/images/rs/icons/node-down-icon.png
  static/images/rs/icons/tmp.txt
  static/images/rs/screenshots/access-control/tmp.txt
  static/images/rs/screenshots/cluster/tmp.txt
  static/images/rs/screenshots/databases/tmp.txt
  static/images/rs/screenshots/nodes/tmp.txt
Labels: p_Software

#2678 RS 6.4.2 July maintenance release notes
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-94.md
Labels: p_Software, hold-off

#2682 6.4.2-94 release notes update
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-94.md
Labels: p_Software

#2683 Update proxy-policy.md
  content/rs/databases/configure/proxy-policy.md
Labels: p_Software

#2666 K8s: added replication status
  content/kubernetes/active-active/create-reaadb.md
  content/kubernetes/active-active/edit-rerc.md
Labels: K8s

#2685 K8s: AA - add preview version note
  content/kubernetes/active-active/_index.md
  content/kubernetes/active-active/create-reaadb.md
  content/kubernetes/active-active/edit-clusters.md
  content/kubernetes/active-active/edit-rerc.md
  content/kubernetes/active-active/global-config.md
  content/kubernetes/active-active/global-db-secret.md
  content/kubernetes/active-active/prepare-clusters.md
Labels: K8s

#2677 K8s: change redis.com to example.com
  content/kubernetes/active-active/create-reaadb.md
  content/kubernetes/active-active/edit-clusters.md
  content/kubernetes/active-active/edit-rerc.md
  content/kubernetes/active-active/prepare-clusters.md
  content/kubernetes/networking/ingressorroutespec.md
  content/kubernetes/security/manage-rec-credentials.md
Labels: K8s

#2675 RDSC-1403-update-docs-for-write-behind-job-changes
  content/rdi/quickstart/write-behind-guide.md
Labels: rdi

#2687 wrong reference
  content/rdi/reference/data-transformation-block-types/redis_write.md
Labels: rdi

#2676 RS: Known limitation & workaround for root directory installation
  content/rs/installing-upgrading/install/customize-install-directories.md
  content/rs/installing-upgrading/install/install-on-linux.md
  content/rs/release-notes/rs-6-0-12-january-2021.md
  content/rs/release-notes/rs-6-0-20-april-2021.md
  content/rs/release-notes/rs-6-0-8-september-2020.md
  content/rs/release-notes/rs-6-0-may-2020.md
  content/rs/release-notes/rs-6-2-10-february-2022.md
  content/rs/release-notes/rs-6-2-12.md
  content/rs/release-notes/rs-6-2-18-releases/_index.md
  content/rs/release-notes/rs-6-2-4-august-2021.md
  content/rs/release-notes/rs-6-2-8-october-2021.md
  content/rs/release-notes/rs-6-4-2-releases/_index.md
Labels: p_Software

#2688 RDSC-1404: key-name-for-nesting
  content/rdi/reference/data-transformation-block-types/redis_write.md
Labels: rdi

#2661 RS: Updated supported platforms (DOC-2134 DOC-1215)
  content/embeds/supported-platforms-embed.md
Labels: p_Software

#2673 RS: RESP3 compatibility
  content/rs/references/cli-utilities/rladmin/tune.md
  content/rs/references/compatibility/_index.md
  content/rs/references/compatibility/commands/connection.md
  content/rs/references/compatibility/resp.md
Labels: p_Software

#2674 Modules EOL updates
  static/tables/redisbloom-lifecycle.csv
  static/tables/redisearch-lifecycle.csv
  static/tables/redisjson-lifecycle.csv
  static/tables/redistimeseries-lifecycle.csv
Labels: p_Modules

#2692 RS: Update TLS, OCSP, internode encryption for new UI
  content/rs/security/certificates/ocsp-stapling.md
  content/rs/security/internode-encryption.md
  content/rs/security/tls/enable-tls.md
  static/images/rs/screenshots/cluster/security-syncer-cert.png
  static/images/rs/screenshots/databases/security-mtls-clients.png
  static/images/rs/screenshots/databases/security-tls-replica-of.png
  static/images/rs/screenshots/switch-to-legacy-ui.png
Labels: p_Software

#2698 DOC-2515 speedb changes
  content/kubernetes/re-clusters/auto-tiering.md
  content/rs/references/rest-api/objects/bootstrap/node_identity.md
  content/rs/references/rest-api/objects/node.md
  content/rs/references/rest-api/requests/bootstrap/_index.md
Labels: p_Software, K8s

#2711 DOC-2557 Split up RDI data type tables
  content/rdi/reference/data-types-conversion.md
Labels: rdi

#2697 K8s 6.4.2-8 release notes
  content/kubernetes/release-notes/6-4-2-releases/6-4-2-6.md
  content/kubernetes/release-notes/6-4-2-releases/6-4-2-8.md
  layouts/shortcodes/details.html
Labels: K8s

#2691 Create v.2.30.0.md
  content/ri/release-notes/v.2.30.0.md
Labels: p_Insight

#2694 Update ciphers.md
  content/rs/security/tls/ciphers.md
Labels: p_Software

#2695 Update tls-protocols.md
  content/rs/security/tls/tls-protocols.md
Labels: p_Software

#2660 Command compatibility updates (v7)
  content/rs/references/compatibility/commands/cluster.md
  content/rs/references/compatibility/commands/connection.md
  content/rs/references/compatibility/commands/data-types.md
  content/rs/references/compatibility/commands/generic.md
  content/rs/references/compatibility/commands/pub-sub.md
  content/rs/references/compatibility/commands/scripting.md
  content/rs/references/compatibility/commands/server.md
Labels: p_Software

#2669 RS: Upgrade paths & bundled DB versions
  content/rs/installing-upgrading/upgrading/upgrade-cluster.md
  content/rs/installing-upgrading/upgrading/upgrade-database.md
  static/images/rs/icons/info-icon.png
Labels: p_Software
