Repository RedisLabs/redislabs-docs, pull requests merged in 2023-02, with the labels that each got.

#2337 Updated create.md to match the UI
  content/rs/databases/active-active/create.md
Labels: p_Software

#2329 K8s: 6.2.18-41 Jan 2023 release notes
  content/kubernetes/release-notes/k8s-6-2-18-41-jan-2023.md
  content/kubernetes/release-notes/k8s-6-2-18-41.md
Labels: K8s

#2335 RS: Added Ubuntu 20.04 to supported platforms
  content/embeds/supported-platforms-embed.md
Labels: p_Software

#2346 DOC-1875: RC - Billing alert user limit
  content/rc/security/access-management.md
Labels: p_Cloud

#2339 RS mTLS full subject
  content/rs/references/rest-api/objects/bdb/_index.md
  content/rs/security/tls/enable-tls.md
  static/images/rs/database-tls-config-full-subject.png
Labels: p_Software

#2347 Fixed /modules/config REST API request examples
  content/rs/references/rest-api/requests/bdbs/modules/config.md
  content/rs/references/rest-api/requests/modules/config.md
Labels: p_Software

#2350 DOC-1878 - RS: Update password complexity rule text
  content/rs/security/access-control/manage-users/manage-passwords.md
Labels: p_Software

#2351 RS v6.4.2 release notes
  content/rs/release-notes/rs-6-4-2.md
Labels: p_Software

#2349 REST API references for RS audit events
  content/rs/references/rest-api/objects/bdb/_index.md
  content/rs/references/rest-api/objects/cluster_settings.md
  content/rs/references/rest-api/objects/db-conns-auditing-config.md
  content/rs/references/rest-api/requests/cluster/auditing-db-conns.md
  content/rs/references/rest-api/requests/cluster/policy.md
  content/rs/security/audit-events.md
Labels: p_Software

#2352 Create redistimeseries-1.8-release-notes.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.8-release-notes.md
  static/images/modules/GapFilling.png
  static/images/modules/twa.png
Labels: p_Modules

#2342 RS pub/sub ACLs
  content/rs/references/cli-utilities/rladmin/tune.md
  content/rs/references/rest-api/objects/cluster_settings.md
  content/rs/security/access-control/configure-acl.md
Labels: p_Software

#2354 Update config.md
  content/modules/redistimeseries/config.md
Labels: p_Modules

#2357 Update redisgraph-2.8-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-2.8-release-notes.md
Labels: p_Modules

#2353 Create redisbloom-2.4-release-notes.md
  content/modules/redisbloom/release-notes/redisbloom-2.4-release-notes.md
Labels: p_Modules

#2356 Create redisjson-2.4-release-notes.md
  content/modules/redisjson/release-notes/redisjson-2.4-release-notes.md
Labels: p_Modules

#2355 Create redisearch-2.6-release-notes.md
  content/modules/redisearch/release-notes/redisearch-2.6-release-notes.md
Labels: p_Modules

#2358 Active-Active eviction policy support updates
  content/rc/databases/configuration/data-eviction-policies.md
  content/rs/databases/active-active/create.md
  content/rs/databases/active-active/develop/develop-for-aa.md
Labels: p_Software, p_Cloud

#2344 Upgrade RS - default DB version change
  content/rs/installing-upgrading/upgrading.md
Labels: p_Software

#2366 Update turn-off-services.md
  content/rs/clusters/optimize/turn-off-services.md
Labels: p_Software

#2362 DOC-1857 RS v6.4.2 release notes and docs
  content/embeds/supported-platforms-embed.md
  content/rs/installing-upgrading/upgrading.md
  content/rs/references/cli-utilities/rladmin/tune.md
  content/rs/references/rest-api/objects/bdb/_index.md
  content/rs/references/rest-api/objects/cluster_settings.md
  content/rs/release-notes/rs-6-4-2.md
  content/rs/security/access-control/configure-acl.md
  content/rs/security/tls/enable-tls.md
  static/images/rs/database-tls-config-full-subject.png
Labels: p_Software

#2363 Update RS version dropdown - main branch
  layouts/404.html
  layouts/partials/flex/body-beforecontent.html
  layouts/partials/flex/scripts.html
  robots.txt
  website.json
Labels: infrastructure, p_Software

#2365 Update RS version dropdown - 6.0-build branch
  .circleci/config.yml
  layouts/404.html
  layouts/partials/flex/body-beforecontent.html
  layouts/partials/flex/scripts.html
Labels: infrastructure, p_Software

#2364 Update RS version dropdown - 6.2-build branch
  layouts/404.html
  layouts/partials/flex/body-beforecontent.html
  layouts/partials/flex/scripts.html
Labels: infrastructure, p_Software

#2359 Fixed RediSearch config compatibility
  content/modules/redisearch/commands.md
  content/modules/redisearch/config.md
Labels: p_Modules

#2369 RC Private Service Connect
  content/rc/security/private-service-connect.md
  static/images/rc/button-subscription-connectivity-psc-accept-continue.png
  static/images/rc/button-subscription-connectivity-psc-accept.png
  static/images/rc/button-subscription-connectivity-psc-complete-setup.png
  static/images/rc/button-subscription-connectivity-psc-connect.png
  static/images/rc/button-subscription-connectivity-psc-continue.png
  static/images/rc/button-subscription-connectivity-psc-create-connection.png
  static/images/rc/button-subscription-connectivity-psc-remove-service-confirm.png
  static/images/rc/icon-psc-actions.png
  static/images/rc/icon-psc-delete-endpoint.png
  static/images/rc/subscription-connectivity-psc-gcloud-script.png
Labels: p_Cloud

#2368 DOC-1722: Edit descriptions for clusters/optimize index page
  content/rs/clusters/optimize/_index.md
Labels: p_Software

#2338 K8s: OperatorHub deployment dev edits DOC-1780 DOC-1840
  content/kubernetes/deployment/openshift/openshift-operatorhub.md
Labels: K8s

#2317 K8s: Admission controller quick start edits
  content/kubernetes/deployment/quick-start.md
Labels: K8s, hold-off

#2373 DOC-1583 - RS: Create certificate updates (self-signed & TLS guidelines)
  content/rs/security/certificates/create-certificates.md
  content/rs/security/certificates/updating-certificates.md
Labels: p_Software

#2375 DOC-1912 - RS: Add RHEL 8.7 to supported platforms
  content/embeds/supported-platforms-embed.md
Labels: p_Software

#2374 DOC-1627: Update LDAP Migration process
  content/rs/security/access-control/ldap/migrate-to-role-based-ldap.md
Labels: p_Software

#2377 Update redistimeseries-1.6-release-notes.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.6-release-notes.md
Labels: p_Modules

#2378 Update redisgraph-2.8-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-2.8-release-notes.md
Labels: p_Modules

#2380 Update redisearch-2.6-release-notes.md
  content/modules/redisearch/release-notes/redisearch-2.6-release-notes.md
Labels: p_Modules

#2382 Update redisbloom-2.4-release-notes.md
  content/modules/redisbloom/release-notes/redisbloom-2.4-release-notes.md
Labels: p_Modules

#2381 Update redisjson-2.4-release-notes.md
  content/modules/redisjson/release-notes/redisjson-2.4-release-notes.md
Labels: p_Modules

#2383 Update redisgraph-2.8-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-2.8-release-notes.md
Labels: p_Modules

#2379 Fixed RedisGraph config compatibility
  content/modules/redisgraph/commands.md
  content/modules/redisgraph/config.md
  content/rs/references/cli-utilities/rladmin/tune.md
  content/rs/references/rest-api/objects/module.md
  content/rs/references/rest-api/requests/bdbs/modules/config.md
  content/rs/references/rest-api/requests/modules/config.md
Labels: p_Modules

#2384 Create redisgraph-2.10-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-2.10-release-notes.md
Labels: p_Modules

#2389 Update the date in v.2.18.0.md
  content/ri/release-notes/v.2.18.0.md
Labels: p_Insight

#2288 Update schedule-backups.md
  content/rs/databases/import-export/schedule-backups.md
Labels: p_Software

#2391 [RI DOC] Re-sort release notes appearance
  content/ri/release-notes/v.2.14.0.md
  content/ri/release-notes/v.2.16.0.md
  content/ri/release-notes/v.2.4.0.md
  content/ri/release-notes/v.2.6.0.md
  content/ri/release-notes/v1.12.0.md
  content/ri/release-notes/v1.13.0.md
  content/ri/release-notes/v2.0.md
  content/ri/release-notes/v2.10.0.md
  content/ri/release-notes/v2.12.0.md
  content/ri/release-notes/v2.2.0.md
  content/ri/release-notes/v2.8.0.md
Labels: p_Insight

#2386 DOC-1817 Update scc.yaml steps in OpenShift install
  content/kubernetes/deployment/openshift/openshift-cli.md
  content/kubernetes/deployment/openshift/openshift-operatorhub.md
Labels: K8s

#2387 DOC-1827 Remove ServiceAccount for admission
  content/kubernetes/re-clusters/multi-namespace.md
Labels: K8s

#2085 new certificates location
  content/rs/security/certificates/updating-certificates.md
Labels: p_Software

#2395 Update rs-6-4-2.md
  content/rs/release-notes/rs-6-4-2.md
Labels: p_Software

#2393 Update _index.md
  content/rs/references/rest-api/objects/bdb/_index.md
Labels: p_Software

#2394 Update remove.md
  content/rs/references/cli-utilities/rladmin/node/remove.md
Labels: p_Software

#2392 Update enable-tls.md
  content/rs/security/tls/enable-tls.md
Labels: p_Software

#1982 ZRANGESTORE with special zset-max-ziplist-entries
  content/rs/release-notes/rs-6-2-10-february-2022.md
  content/rs/release-notes/rs-6-2-4-august-2021.md
  content/rs/release-notes/rs-6-2-8-october-2021.md
Labels: p_Software

#2267 Update create.md to fix database naming criteria
  content/rs/databases/create.md
Labels: p_Software

#2397 K8s: persistent storage wording change
  content/kubernetes/memory/persistent-volumes.md
Labels: bug, K8s

#2079 Update upgrading.md
  content/rs/installing-upgrading/upgrading.md
Labels: p_Software
