Repository RedisLabs/redislabs-docs, pull requests merged in 2023-06, with the labels that each got.

#2586 Update hardware-requirements-embed.md
  content/embeds/hardware-requirements-embed.md
Labels: p_Software

#2564 DOC-2239 delete RERC
  content/kubernetes/delete_custom_resources.md
  content/kubernetes/re-databases/db-controller.md
Labels: K8s

#2587 RS: Update known issues in 6.4.2 & 6.2 release notes
  content/rs/release-notes/rs-6-2-10-february-2022.md
  content/rs/release-notes/rs-6-2-12.md
  content/rs/release-notes/rs-6-2-18-releases/_index.md
  content/rs/release-notes/rs-6-2-4-august-2021.md
  content/rs/release-notes/rs-6-2-8-october-2021.md
  content/rs/release-notes/rs-6-4-2-releases/_index.md
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-30.md
Labels: p_Software

#2590 RDI multi-targets and data_types
  content/rdi/data-transformation/data-transformation-pipeline.md
  content/rdi/data-transformation/examples/multiple-targets-example.md
  content/rdi/data-transformation/examples/redis-hash-example.md
  content/rdi/data-transformation/examples/redis-json-example.md
  content/rdi/data-transformation/examples/redis-set-example.md
  content/rdi/data-transformation/examples/redis-stream-example.md
  content/rdi/quickstart/ingest-guide.md
Labels: rdi

#2593 Update TLS cipher examples to remove 3DES keys
  content/rs/security/tls/ciphers.md
Labels: p_Software

#2528 Fix keys/generic command compatibility and add notes
  content/rs/references/compatibility/commands/generic.md
Labels: p_Software

#2605 Update internode-encryption.md
  content/rs/security/internode-encryption.md
Labels: p_Software

#2597 RDSC-1302: added sorted sets example
  content/rdi/data-transformation/examples/multiple-targets-example.md
  content/rdi/data-transformation/examples/redis-sorted-set-example.md
Labels: rdi

#2576 RDSC-1204-document-log-rotations-and-configuration-on-the-pacemaker-page
  content/rdi/installation/pacemaker.md
Labels: enhancement, rdi

#2604 Create json.md
  content/rs/databases/active-active/develop/data-types/json.md
Labels: p_Software

#2608 Update data-eviction-policies.md
  content/rc/databases/configuration/data-eviction-policies.md
Labels: p_Cloud

#2579 DOC-1934: RC Maintenance Windows
  content/rc/security/access-control/access-management.md
  content/rc/subscriptions/create-flexible-subscription.md
  content/rc/subscriptions/maintenance/_index.md
  content/rc/subscriptions/maintenance/set-maintenance-windows.md
  content/rc/subscriptions/view-flexible-subscription.md
  static/images/rc/subscriptions-set-maintenance-window.png
Labels: feature, p_Cloud, hold-off

#2610 DOC-2332 RS 6.4.2 June release notes and docs
  content/rs/installing-upgrading/upgrading.md
  content/rs/release-notes/rs-6-2-10-february-2022.md
  content/rs/release-notes/rs-6-2-12.md
  content/rs/release-notes/rs-6-2-18-releases/_index.md
  content/rs/release-notes/rs-6-2-4-august-2021.md
  content/rs/release-notes/rs-6-2-8-october-2021.md
  content/rs/release-notes/rs-6-4-2-releases/_index.md
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-81.md
Labels: p_Software

#2592 RDSC-296 update `map` block documentation with the accurate expression type and add example for nested jmespath
  content/rdi/reference/data-transformation-block-types/map.md
Labels: rdi, doc_bug

#2602 RSC-1311-fixed k8s prereq
  content/rdi/installation/install-k8s.md
Labels: rdi

#2603 RDSC-1328 update config.yaml reference
  content/rdi/reference/config-yaml-reference.md
Labels: rdi

#2549 Max simultaneous backups defaults to 4
  content/rc/api/examples/back-up-and-import-data.md
  content/rc/databases/back-up-data.md
  content/rs/databases/import-export/schedule-backups.md
  content/rs/references/cli-utilities/rladmin/tune.md
  content/rs/references/rest-api/objects/cluster_settings.md
Labels: p_Software, p_Cloud

#2600 RDSC-1311 Additional info about Gears on K8s
  content/rdi/installation/install-k8s.md
Labels: rdi

#2612 K8s: remove kustomize page - outdated
  content/kubernetes/deployment/_index.md
  content/kubernetes/deployment/using-kustomize.md
Labels: K8s

#2616 DOC-2365 & DOC-2366: Update June changelog with breaking changes
  content/embeds/r7.2-breaking-changes.md
  content/rc/changelog/june-2023.md
Labels: p_Cloud

#2614 RDSC-1131 document access to key and before
  content/rdi/data-transformation/data-transformation-pipeline.md
Labels: rdi

#2617 RDSC-1319: document redis enterprise as target for write behind
  content/rdi/data-transformation/examples/write-behind-to-redis-example.md
  content/rdi/quickstart/write-behind-guide.md
Labels: enhancement, rdi

#2621 RDSC-1339: document redis write block in docs reference section
  content/rdi/reference/data-transformation-block-types/redis_write.md
Labels: rdi

#2625 navigation for data transformations examples
  content/rdi/data-transformation/examples/_index.md
  content/rdi/data-transformation/examples/foreach-example.md
Labels: rdi

#2620 RS: Removed outdated Replica Of video & fixed note format
  content/rs/databases/import-export/replica-of/_index.md
Labels: p_Software

#2606 K8s: add real words to example values
  content/kubernetes/active-active/create-reaadb.md
  content/kubernetes/active-active/edit-clusters.md
  content/kubernetes/active-active/edit-rerc.md
  content/kubernetes/active-active/global-config.md
  content/kubernetes/active-active/prepare-clusters.md
Labels: next version, K8s

#2624 RDI_Config_File_Updates
  content/rdi/installation/debezium-server-configuration.md
  content/rdi/reference/cli/redis-di-scaffold.md
  content/rdi/reference/config-yaml-reference.md
  content/rdi/reference/debezium/oracle.md
Labels: rdi

#2629 RDSC-1246-adding-config-ref-for-mongo
  content/rdi/reference/debezium/mongodb.md
Labels: rdi

#2628 DOC-2377: Add Disclaimer about when maintenance window changes are updated to the Maintenance window docs
  content/rc/subscriptions/maintenance/set-maintenance-windows.md
Labels: p_Cloud

#2611 K8s Poseidon release notes
  content/kubernetes/active-active/_index.md
  content/kubernetes/active-active/create-aa-crdb-cli.md
  content/kubernetes/deployment/openshift/openshift-cli.md
  content/kubernetes/re-clusters/upgrade-redis-cluster.md
  content/kubernetes/reference/supported_k8s_distributions.md
  content/kubernetes/release-notes/6-4-2-releases/6-4-2-6.md
Labels: next version, K8s

#2598 K8s: ingressOrRouteSpec changes
  changelog.md
  content/glossary/_index.md
  content/kubernetes/active-active/_index.md
  content/kubernetes/active-active/create-aa-crdb-cli.md
  content/kubernetes/active-active/prepare-clusters.md
  content/kubernetes/networking/_index.md
  content/kubernetes/networking/external-routing.md
  content/kubernetes/networking/ingress.md
  content/kubernetes/networking/ingressorroutespec.md
  content/kubernetes/networking/istio-ingress.md
  content/kubernetes/networking/routes.md
  content/kubernetes/re-clusters/connect-to-admin-console.md
  content/kubernetes/re-databases/db-controller.md
Labels: next version, K8s

#2633 K8s: OpenShift ingressOrRoutes example
  content/kubernetes/networking/ingressorroutespec.md
Labels: next version, K8s

#2634 K8s: AA install prereq checklist
  content/kubernetes/active-active/_index.md
  content/kubernetes/active-active/create-reaadb.md
  content/kubernetes/active-active/prepare-clusters.md
  content/kubernetes/networking/routes.md
Labels: K8s

#2637 K8s: revise delete scc steps in upgrade article
  content/kubernetes/re-clusters/upgrade-redis-cluster.md
Labels: next version, K8s

#2638 K8s: Red-102241 Upgrade path info
  content/kubernetes/re-clusters/upgrade-redis-cluster.md
  content/kubernetes/reference/supported_k8s_distributions.md
  content/kubernetes/release-notes/6-2-18-releases/_index.md
  content/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-3.md
  content/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-41-jan-2023.md
  content/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-41.md
  content/kubernetes/release-notes/6-4-2-releases/6-4-2-5.md
  content/kubernetes/release-notes/6-4-2-releases/6-4-2-6.md
  content/kubernetes/release-notes/6-4-2-releases/_index.md
  content/kubernetes/release-notes/6-4-2-releases/k8s-6-4-2-4.md
  content/kubernetes/release-notes/k8s-6-2-10-34-2022-05.md
  content/kubernetes/release-notes/k8s-6-2-10-4-2022-03 copy.md
  content/kubernetes/release-notes/k8s-6-2-10-45-2022-07.md
  content/kubernetes/release-notes/k8s-6-2-12-1.md
  content/kubernetes/release-notes/k8s-6-2-4-1-2021-09.md
  content/kubernetes/release-notes/k8s-6-2-8-11-2022-01.md
  content/kubernetes/release-notes/k8s-6-2-8-15-2022-01.md
  content/kubernetes/release-notes/k8s-6-2-8-2-2021-11.md
Labels: bug, K8s

#2631 Added rladmin to commands
  content/modules/redisgears/python/recipes/write-behind.md
  content/rs/clusters/cluster-recovery.md
  content/rs/databases/active-active/develop/data-types/streams.md
  content/rs/databases/active-active/synchronization-mode.md
  content/rs/networking/multi-ip-ipv6.md
  content/rs/references/cli-utilities/rladmin/migrate.md
  content/rs/release-notes/rs-6-2-4-august-2021.md
Labels: p_Software

#2632 Fixed upgrade db keep_redis_version parameter
  content/rs/references/cli-utilities/rladmin/upgrade.md
Labels: p_Software

#2646 Update redisearch-active-active.md
  content/modules/redisearch/redisearch-active-active.md
Labels: p_Modules

#2648 Update tune.md
  content/rs/references/cli-utilities/rladmin/tune.md
Labels: p_Software

#2649 Update upgrade.md
  content/rs/references/cli-utilities/rladmin/upgrade.md
Labels: p_Software

#2650 K8s: correct/clarify AA version support
  content/kubernetes/active-active/_index.md
  content/kubernetes/active-active/create-reaadb.md
  content/kubernetes/active-active/edit-clusters.md
  content/kubernetes/active-active/edit-rerc.md
  content/kubernetes/active-active/global-config.md
  content/kubernetes/active-active/global-db-secret.md
  content/kubernetes/active-active/prepare-clusters.md
Labels: K8s, doc_bug
