Repository RedisLabs/redislabs-docs, pull requests merged in 2023-12, with the labels that each got.

#2963 DOC-2046 Fixed RoF reference.
  content/rs/databases/configure/_index.md
Labels: p_Software

#2981 DOC-3034 Focused OSS cluster config article on the config and redirec…
  content/rs/databases/configure/oss-cluster-api.md
Labels: p_Software

#2965 DOC-2828 Moved Auto Tiering install to install on Linux.
  content/rs/installing-upgrading/install/install-on-linux.md
  content/rs/installing-upgrading/install/prepare-install/_index.md
  content/rs/installing-upgrading/install/prepare-install/prepare-flash.md
Labels: p_Software

#2999 Update upgrade-database.md
  content/rs/installing-upgrading/upgrading/upgrade-database.md
Labels: p_Software

#3002 RS: bug bash - upgrade cluster
  content/rs/installing-upgrading/upgrading/upgrade-cluster.md
  content/rs/installing-upgrading/upgrading/upgrade-database.md
Labels: p_Software

#2998 RS: Reduce image width
  content/rs/security/access-control/manage-users/add-users.md
Labels: p_Software

#2955 DOC-3006 Created monitor redis cloud section and moved system-logs an…
  content/rc/api/examples/audit-system-logs.md
  content/rc/changelog/october-2023.md
  content/rc/cloud-integrations/prometheus-integration.md
  content/rc/databases/monitor-performance.md
  content/rc/logs-reports/_index.md
  content/rc/logs-reports/system-logs.md
  content/rc/logs-reports/usage-reports.md
Labels: p_Cloud

#2991 RS: Avoid node majority in one availability zone
  content/rs/clusters/configure/rack-zone-awareness.md
Labels: p_Software

#2990 RS: Add note & link to RESP3 client prereqs from DB upgrade prereqs
  content/rs/installing-upgrading/upgrading/upgrade-database.md
Labels: p_Software

#2986 RS: Add port 9125 to metrics ports
  content/rs/networking/port-configurations.md
Labels: p_Software

#2983 RS: Upgrade CRDB with modules
  content/rs/installing-upgrading/upgrading/upgrade-active-active.md
Labels: p_Software

#2985 RS: Reserved ports rladmin & REST API examples
  content/rs/networking/port-configurations.md
Labels: p_Software

#2996 RS: Add rladmin status modules reference & missing parameter for rladmin status endpoints
  content/rs/references/cli-utilities/rladmin/status.md
Labels: p_Software

#3003 RC: Update screenshots to reflect AWS and GCP marketplace name changes
  content/rc/cloud-integrations/aws-marketplace/_index.md
  content/rc/cloud-integrations/gcp-marketplace/_index.md
  static/images/rc/aws-marketplace-rc-flexible-plan.png
  static/images/rc/gcp-marketplace-rc-payg-plan.png
Labels: p_Cloud

#2976 Fixes related to the RS cluster section
  content/rs/clusters/configure/sync-clocks.md
  content/rs/clusters/maintenance-mode.md
  content/rs/clusters/monitoring/prometheus-integration.md
  content/rs/clusters/remove-node.md
  content/rs/clusters/replace-node.md
  static/images/rs/prometheus-connection.png
Labels: p_Software

#3004 DOC-2826 add a note
  content/embeds/port-53.md
Labels: p_Software

#2994 Updates to the networking RS section
  content/rs/networking/configuring-aws-route53-dns-redis-enterprise.md
  content/rs/networking/private-public-endpoints.md
  static/images/rs/00-CreateHostedZone-en.png
  static/images/rs/01-ServicesRoute53-en.png
  static/images/rs/03-HostedZoneSelection-en.png
  static/images/rs/04-CreateRecordSet-en.png
  static/images/rs/05-NS1Configuration-en.png
  static/images/rs/06-NSList-en.png
  static/images/rs/07-NSRecord-en.png
  static/images/rs/08-FinalConfig-en.png
Labels: p_Software

#3022 RS: Reconnect clients to apply TLS changes
  content/rs/security/encryption/tls/enable-tls.md
Labels: p_Software

#2978 K8s: 6.4.2-8 maint 2 release notes
  content/kubernetes/release-notes/6-4-2-releases/6-4-2-8-dec23.md
  content/kubernetes/release-notes/7-2-4-releases/7-2-4-2.md
  content/kubernetes/release-notes/7-2-4-releases/7-2-4-7.md
Labels: K8s, release branch

#3023 RS: Banner - Nagios plugin is retired
  content/rs/clusters/monitoring/nagios-plugin.md
Labels: p_Software

#3024 RS: Snapshot persistence is not supported for Active-Active DBs
  content/rs/databases/active-active/create.md
Labels: p_Software, doc_bug

#3025 RC: Add message about cluster/database(s) not being impacted when configuring Maintenance Window
  content/rc/subscriptions/maintenance/set-maintenance-windows.md
Labels: bug, p_Cloud

#3026 RC/RS: Active-Passive eviction/expiration limitation
  content/rc/databases/migrate-databases.md
  content/rc/subscriptions/upgrade-fixed-flexible.md
  content/rs/databases/import-export/replica-of/create.md
Labels: bug, p_Software, p_Cloud

#3027 Update docker-memory-limitation.md
  content/embeds/docker-memory-limitation.md
Labels: enhancement, p_Software

#3020 RC: Full mTLS support
  content/rc/changelog/december-2023.md
  content/rc/cloud-integrations/aws-marketplace/aws-bedrock/set-up-redis.md
  content/rc/security/database-security/tls-ssl.md
  static/images/rc/database-details-configuration-tab-security-tls-client-auth-certificate.png
  static/images/rc/mtls-add-client-certificate.png
  static/images/rc/mtls-certificate-details.png
  static/images/rc/mtls-download-certificate.png
Labels: p_Cloud, hold-off

#3019 RC: Active-Active with JSON
  content/rc/changelog/december-2023.md
  content/rc/databases/create-database.md
  content/rc/subscriptions/create-active-active-subscription.md
  static/images/rc/active-active-json-detail.png
  static/images/rc/create-database-active-active.png
Labels: p_Cloud, hold-off

#3034 RC: Add editor role to 3pic management page
  content/rc/cloud-integrations/gcp-marketplace/team-management.md
Labels: p_Cloud

#3036 Typo fix
  content/rs/databases/active-active/develop/data-types/streams.md
Labels: p_Software

#3032 K8s: update distro to remove unsupported 1.28
  content/kubernetes/reference/supported_k8s_distributions.md
  content/kubernetes/release-notes/7-2-4-releases/7-2-4-12.md
Labels: K8s, doc_bug

#3031 Fix december changelog
  content/rc/changelog/december-2023.md
Labels: p_Cloud

#3033 RC: Availability Zones are now in the subscription overview tab
  content/rc/subscriptions/view-flexible-subscription.md
  static/images/rc/subscription-details-overview-flexible.png
Labels: p_Cloud

#3039 K8s: OPERATOR_NAMESPACE placeholder
  content/embeds/k8s-admission-webhook-cert.md
  content/kubernetes/deployment/quick-start.md
  content/kubernetes/recommendations/node-selection.md
Labels: typos/format, K8s, doc_bug

#3042 RC: Database tags private preview
  content/embeds/rc-tags-tag-module.md
  content/rc/databases/back-up-data.md
  content/rc/databases/configuration/_index.md
  content/rc/databases/create-database.md
  content/rc/databases/delete-database.md
  content/rc/databases/flush-data.md
  content/rc/databases/import-data.md
  content/rc/databases/migrate-databases.md
  content/rc/databases/tag-database.md
  content/rc/databases/view-edit-database.md
  static/images/rc/database-list-filter-selected.png
  static/images/rc/database-list-filter.png
  static/images/rc/database-new-tags.png
  static/images/rc/migrate-database-select-source.png
  static/images/rc/tags-button-add-tag.png
  static/images/rc/tags-button-save-tags.png
  static/images/rc/tags-database-list.png
  static/images/rc/tags-database-tab.png
  static/images/rc/tags-icon-add-tags.png
  static/images/rc/tags-icon-delete.png
  static/images/rc/tags-icon-edit.png
  static/images/rc/tags-icon-manage-tags.png
  static/images/rc/tags-icon-more-actions.png
  static/images/rc/tags-new-tag.png
  static/images/rc/tags-tag-manager.png
Labels: p_Cloud

#3050 DOC-524
  content/contribution-guide.md
Labels: enhancement
