Repository RedisLabs/redislabs-docs, pull requests merged in 2023-03, with the labels that each got.

#2398 Update rs-6-2-18.md
  content/rs/release-notes/rs-6-2-18.md
Labels: p_Software

#2390 Create v.2.20.0.md
  content/ri/release-notes/v.2.20.0.md
Labels: p_Insight

#2372 Breaking changes list
  content/rs/references/compatibility/breaking-changes.md
  content/rs/references/compatibility/commands/_index.md
  content/rs/references/compatibility/config-settings.md
Labels: p_Software, p_Cloud

#2402 Update rs-6-2-18.md
  content/rs/release-notes/rs-6-2-18.md
Labels: p_Software

#2396 K8s Orion: LDAP support
  content/kubernetes/security/ldap.md
Labels: next version, K8s

#2404 DOC-1835 and DOC-1836: Metrics Reference: Redis on Flash and Active-Active metrics
  content/rs/references/metrics/active-active.md
  content/rs/references/metrics/database-operations.md
  content/rs/references/metrics/redis-on-flash.md
  content/rs/references/metrics/resource-usage.md
Labels: p_Software

#2410 Fix PEM bundle contents
  content/rc/security/database-security/tls-ssl.md
Labels: p_Cloud

#2409 Update _index.md
  content/rs/references/rest-api/objects/cluster/_index.md
Labels: p_Software

#2376 DOC-1822: Edit mailing/billing address UX changes
  content/rc/accounts/account-settings.md
  content/rc/billing-and-payments.md
  static/images/rc/account-settings-account-tab.png
  static/images/rc/account-settings-change-billing-address.png
  static/images/rc/account-settings-edit-address-button.png
  static/images/rc/billing-add-credit-card.png
  static/images/rc/billing-change-mailing-address.png
  static/images/rc/billing-credit-card-options-menu.png
  static/images/rc/billing-update-billing-address.png
  static/images/rc/button-billing-save-card.png
Labels: p_Cloud, hold-off

#2399 RS Ubuntu 20 support
  content/embeds/supported-platforms-embed.md
Labels: p_Software

#2403 RS 6.4.2 March release notes update
  content/rs/databases/import-export/import-data.md
  content/rs/release-notes/legacy-release-notes/_index.md
  content/rs/release-notes/legacy-release-notes/rs-5-5-preview-april-2019.md
  content/rs/release-notes/legacy-release-notes/rs-5-6-0-april-2020.md
  content/rs/release-notes/rs-6-4-2.md
Labels: p_Software

#2412 DOC-1921 RS v6.4.2-43 March release notes and docs
  content/embeds/supported-platforms-embed.md
  content/rs/databases/import-export/import-data.md
  content/rs/networking/port-configurations.md
  content/rs/references/cli-utilities/rladmin/node/remove.md
  content/rs/references/rest-api/objects/bdb/_index.md
  content/rs/references/rest-api/objects/cluster/_index.md
  content/rs/release-notes/legacy-release-notes/_index.md
  content/rs/release-notes/legacy-release-notes/rs-5-5-preview-april-2019.md
  content/rs/release-notes/legacy-release-notes/rs-5-6-0-april-2020.md
  content/rs/release-notes/rs-6-4-2.md
  content/rs/security/tls/enable-tls.md
Labels: p_Software

#2413 Update rs-6-4-2.md
  content/rs/release-notes/rs-6-4-2.md
Labels: p_Software

#2416 Update port-configurations.md
  content/rs/networking/port-configurations.md
Labels: p_Software

#2411 K8s Orion: Release notes
  content/kubernetes/reference/supported_k8s_distributions.md
  content/kubernetes/release-notes/k8s-6-4-2-4.md
Labels: next version, K8s

#2419 Update rs-6-4-2.md
  content/rs/release-notes/rs-6-4-2.md
Labels: p_Software

#2408 Disallows for RDI snapshots
  robots.txt
Labels: rdi

#2406 Archived self-managed AWS account docs
  content/rc/cloud-integrations/_index.md
  content/rc/cloud-integrations/aws-cloud-accounts/_index.md
Labels: p_Cloud

#2417 DOC-1926: Metrics Reference top-level page
  content/rs/clusters/monitoring/_index.md
  content/rs/clusters/monitoring/console-metrics-definitions.md
  content/rs/clusters/monitoring/prometheus-integration.md
  content/rs/clusters/monitoring/uptrace-integration.md
  content/rs/databases/memory-performance/memory-limit.md
  content/rs/databases/redis-on-flash/_index.md
  content/rs/references/metrics/_index.md
Labels: p_Software

#2422 Update _index.md
  content/rs/references/rest-api/objects/bdb/_index.md
Labels: p_Software

#2401 K8s: Active-Active public preview
  changelog.md
  content/glossary/_index.md
  content/kubernetes/active-active/_index.md
  content/kubernetes/active-active/create-aa-database.md
  content/kubernetes/active-active/preview/_index.md
  content/kubernetes/active-active/preview/create-reaadb.md
  content/kubernetes/active-active/preview/prepare-clusters.md
  content/kubernetes/networking/_index.md
  content/kubernetes/networking/external-routing.md
  content/kubernetes/networking/ingress-routing-with-istio.md
  content/kubernetes/networking/routes.md
  content/kubernetes/networking/set-up-ingress-controller.md
  content/kubernetes/re-databases/db-controller.md
  content/kubernetes/reference/_index.md
Labels: next version, K8s

#2424 Add desc to release note
  content/kubernetes/release-notes/k8s-6-4-2-4.md
Labels: K8s

#2425 RC r7 preview
  content/rc/security/database-security/passwords-users-roles.md
  content/rc/subscriptions/create-fixed-subscription.md
  static/images/rc/subscription-new-cloud-vendor-options-redis-7-preview.png
  static/images/rc/subscription-new-redis-7-preview-toggle.png
Labels: p_Cloud, hold-off

#2420 RS Metrics Reference
  content/rs/clusters/monitoring/_index.md
  content/rs/clusters/monitoring/console-metrics-definitions.md
  content/rs/clusters/monitoring/prometheus-integration.md
  content/rs/clusters/monitoring/uptrace-integration.md
  content/rs/databases/memory-performance/memory-limit.md
  content/rs/databases/redis-on-flash/_index.md
  content/rs/references/metrics/_index.md
  content/rs/references/metrics/database-operations.md
  content/rs/references/metrics/redis-on-flash.md
  content/rs/references/metrics/resource-usage.md
Labels: p_Software

#2421 RS release notes format updates (6.2.18 & 6.4.2)
  content/rs/release-notes/rs-6-2-18.md
  content/rs/release-notes/rs-6-4-2.md
Labels: p_Software

#2435 Update postgresql.md
  content/rdi/reference/debezium/postgresql.md
Labels: rdi

#2434 Update mysql.md
  content/rdi/reference/debezium/mysql.md
Labels: rdi

#2429 Update debezium-server-configuration.md
  content/rdi/installation/debezium-server-configuration.md
Labels: rdi

#2428 Update debezium-server-configuration.md
  content/rdi/installation/debezium-server-configuration.md
Labels: rdi

#2433 Update cassandra.md
  content/rdi/installation/debezium-server-configuration.md
  content/rdi/reference/debezium/cassandra.md
Labels: rdi

#2432 Update oracle.md
  content/rdi/installation/debezium-server-configuration.md
  content/rdi/reference/debezium/oracle.md
Labels: rdi

#2431 Update debezium-server-deployment.md
  content/rdi/installation/debezium-server-deployment.md
  content/rdi/reference/debezium/cassandra.md
Labels: rdi

#2440 K8s: DOC-1945
  content/kubernetes/deployment/openshift/openshift-operatorhub.md
Labels: bug, K8s

#2437 K8s: move SCC steps before operator install
  content/kubernetes/deployment/openshift/openshift-cli.md
  content/kubernetes/deployment/openshift/openshift-operatorhub.md
Labels: bug, K8s

#2442 K8s: corrected scc 6.2.18-41 note
  content/kubernetes/deployment/openshift/openshift-cli.md
Labels: bug, K8s

#2445 DOC-1820: Update New Subscription screenshots to match new UX Card Style
  static/images/rc/new-subscription-plans-flexible.png
  static/images/rc/subscription-new-plan-options.png
Labels: p_Cloud

#2454 DOC-1315: Missing limitation indicator for S3 bucket usage on multiple accounts
  content/rc/databases/back-up-data.md
Labels: p_Cloud

#2455 DOC-1927: Improve redisAccountMapping field description
  content/rc/security/single-sign-on/saml-sso/_index.md
Labels: p_Cloud

#2457 Update rs-6-2-10-february-2022.md
  content/rs/release-notes/rs-6-2-10-february-2022.md
Labels: p_Software

#2443 K8s: multi-namespace corrections DOC-1953
  content/kubernetes/re-clusters/multi-namespace.md
Labels: bug, K8s

#2449 Clarified/cleaned up RS version cipher suite support
  content/rs/security/tls/ciphers.md
Labels: p_Software

#2430 Update rack-zone-awareness.md
  content/rs/clusters/configure/rack-zone-awareness.md
Labels: p_Software

#2459 aa-modules-upgrade-bug-RN.md
  content/rs/release-notes/rs-6-2-18.md
  content/rs/release-notes/rs-6-4-2.md
Labels: p_Software

#2460 Update rs-6-4-2.md
  content/rs/release-notes/rs-6-4-2.md
Labels: p_Software

#2462 Update hardware-requirements-embed.md
  content/embeds/hardware-requirements-embed.md
Labels: p_Software

#2461 Update rs-6-2-18.md
  content/rs/release-notes/rs-6-2-18.md
  content/rs/release-notes/rs-6-4-2.md
Labels: p_Software

#2448 Changed RHEL7 to RHEL; CentOS/RHEL firewall copy edits
  content/embeds/supported-platforms-embed.md
  content/rs/installing-upgrading/_index.md
  content/rs/installing-upgrading/configuring/centos-rhel-7-firewall.md
  content/rs/installing-upgrading/configuring/centos-rhel-firewall.md
  content/rs/installing-upgrading/manage-installation-questions.md
Labels: p_Software

#2452 Fix RS 6.2 EOL in release notes
  content/rs/release-notes/rs-6-2-18.md
Labels: p_Software

#2463 Fix K8s code block formatting
  content/kubernetes/security/manage-rec-certificates.md
Labels: bug, K8s

#2468 K8s: release notes - add resharding limitation from RS
  content/kubernetes/release-notes/k8s-6-4-2-4.md
Labels: K8s

#2465 DOC-2069 AA preview content fixes
  content/kubernetes/active-active/preview/_index.md
  content/kubernetes/active-active/preview/create-reaadb.md
  content/kubernetes/active-active/preview/prepare-clusters.md
Labels: bug, K8s

#2472 Update rs-6-4-2.md
  content/rs/release-notes/rs-6-4-2.md
Labels: p_Software

#2470 DOC-2064: Redis Cloud: missing instructions for active-passive when source is TLS enabled
  content/rc/databases/migrate-databases.md
  static/images/rc/database-public-endpoint-copy.png
  static/images/rc/migrate-database-select-source.png
Labels: p_Cloud
