Repository RedisLabs/redislabs-docs, pull requests merged in 2023-11, with the labels that each got.

#2907 DOC-3029: Add Heroku message to November changelog
  content/rc/changelog/november-2023.md
Labels: p_Cloud

#2923 DOC-3002 Docs Bash feedback.
  content/rc/databases/back-up-data.md
Labels: p_Cloud

#2916 Add info to RERC description DOC-2796
  content/kubernetes/active-active/edit-rerc.md
Labels: K8s

#2918 K8s: Sharding disabled with 1 shard REAADB
  content/kubernetes/active-active/create-reaadb.md
Labels: K8s

#2902 RS: OS rolling upgrade
  content/rs/clusters/remove-node.md
  content/rs/installing-upgrading/upgrading/upgrade-os.md
  content/stack/install/add-module-to-cluster.md
Labels: p_Software

#2921 RS: Add anchor to cluster config REST API link
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-64.md
Labels: p_Software

#2917 K8s: delete REDB before namespace
  content/kubernetes/delete-custom-resources.md
Labels: K8s

#2909 RS: PEM encryption & new encryption section/reorg
  content/glossary/_index.md
  content/kubernetes/reference/db-options.md
  content/kubernetes/security/internode-encryption.md
  content/rs/_index.md
  content/rs/databases/configure/_index.md
  content/rs/databases/configure/db-defaults.md
  content/rs/databases/connect/_index.md
  content/rs/references/cli-utilities/rladmin/tune.md
  content/rs/release-notes/rs-6-0-20-april-2021.md
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-69.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-72.md
  content/rs/security/_index.md
  content/rs/security/admin-console-security/_index.md
  content/rs/security/certificates/monitor-certificates.md
  content/rs/security/encryption/_index.md
  content/rs/security/encryption/internode-encryption.md
  content/rs/security/encryption/pem-encryption.md
  content/rs/security/encryption/tls/_index.md
  content/rs/security/encryption/tls/ciphers.md
  content/rs/security/encryption/tls/enable-tls.md
  content/rs/security/encryption/tls/tls-protocols.md
  content/rs/security/tls/_index.md
Labels: p_Software

#2914 DOC-3031: RC: Integrations - terraform - missing sources and resources
  content/rc/cloud-integrations/pulumi/_index.md
  content/rc/cloud-integrations/terraform/_index.md
Labels: p_Cloud

#2912 DOC-3058: RC: Billing & payments - missing step and DOC-2779: SAML setup button outdated
  content/rc/billing-and-payments.md
  content/rc/security/access-control/saml-sso/_index.md
  static/images/rc/account-settings-confirm-billing-address.png
  static/images/rc/button-access-management-sso-setup.png
Labels: bug, p_Cloud

#2922 Doc 3078 Database section of RC - updates from Doc Bash
  content/rc/databases/_index.md
  content/rc/databases/active-active-redis.md
  content/rc/databases/configuration/clustering.md
  content/rc/databases/configuration/data-eviction-policies.md
  content/rc/databases/configuration/data-persistence.md
  content/rc/databases/configuration/high-availability.md
  content/rc/databases/create-database.md
  content/rc/databases/delete-database.md
  content/rc/databases/flush-data.md
  content/rc/databases/import-data.md
  content/rc/databases/migrate-databases.md
  content/rc/databases/monitor-performance.md
  content/rc/databases/system-logs.md
  content/rc/databases/view-edit-database.md
  content/rs/networking/cluster-lba-setup.md
  static/images/rc/button-both-delete.png
  static/images/rc/button-database-delete.png
  static/images/rc/database-delete-last-dialog.png
  static/images/rc/database-details-configuration-tab-scalability-flexible.png
  static/images/rc/database-list-filter-selected.png
  static/images/rc/database-list-filter.png
  static/images/rc/database-list-search.png
  static/images/rc/database-metrics-interval-scrollbar.png
  static/images/rc/redisinsight-cli-flushall-example.png
  static/images/rc/system-logs.png
Labels: p_Cloud

#2930 DOC-2921 Corrected link text on Accounts and settings landing page.
  content/rc/accounts/_index.md
Labels: p_Cloud

#2932 DOC-2923 Feedback from Docs Bash.
  content/rc/accounts/account-settings.md
  static/images/rc/account-settings-account-tab.png
Labels: p_Cloud

#2937 DOC-2827 Corrected ROF to Auto Tiering.
  content/rs/installing-upgrading/install/prepare-install/prepare-flash.md
Labels: p_Software

#2936 DOC-2824 Corrected ROF to be Auto Tiering.
  content/rs/installing-upgrading/install/plan-deployment/configuring-aws-instances.md
Labels: p_Software

#2941 DOC-2906: Bug Bash Billing and Payments changes
  content/rc/billing-and-payments.md
Labels: p_Cloud

#2951 RDSC-1684-write-behind-should-support-db-2: Auto generated
  content/rdi/reference/cli/redis-di-scaffold.md
Labels: rdi

#2949 RS: Role/permissions example for importing data from Google Cloud storage
  content/rs/databases/import-export/import-data.md
Labels: p_Software

#2947 RS: DB defaults for shard placement and proxy policies
  content/rs/databases/configure/db-defaults.md
  content/rs/references/cli-utilities/rladmin/tune.md
Labels: p_Software

#2906 RS: Added capability_name field to module REST API object reference
  content/rs/references/rest-api/objects/module.md
Labels: p_Software

#2913 RS: LDAP config updates for new UI
  content/rs/security/access-control/ldap/_index.md
  content/rs/security/access-control/ldap/enable-role-based-ldap.md
  content/rs/security/access-control/ldap/map-ldap-groups-to-roles.md
  content/rs/security/access-control/ldap/migrate-to-role-based-ldap.md
  content/rs/security/access-control/ldap/update-database-acls.md
  static/images/rs/screenshots/access-control/ldap-config.png
  static/images/rs/screenshots/access-control/tmp.txt
  static/images/rs/screenshots/cluster/tmp.txt
  static/images/rs/screenshots/databases/tmp.txt
Labels: p_Software

#2493 RS: Enable rack-zone awareness for existing clusters & databases
  content/kubernetes/recommendations/node-selection.md
  content/rs/clusters/configure/rack-zone-awareness.md
  content/rs/references/cli-utilities/rladmin/node/maintenance-mode.md
  static/images/rs/screenshots/databases/config-rack-zone-awareness.png
Labels: p_Software

#2956 RS: Debug info REST API requests to create support packages
  content/rs/installing-upgrading/creating-support-package.md
  content/rs/references/rest-api/requests/debuginfo/_index.md
  content/rs/references/rest-api/requests/debuginfo/all/_index.md
  content/rs/references/rest-api/requests/debuginfo/all/bdb.md
  content/rs/references/rest-api/requests/debuginfo/node/_index.md
  content/rs/references/rest-api/requests/debuginfo/node/bdb.md
Labels: p_Software

#2962 RS: Added missing requirement for local mount point imports
  content/rs/databases/import-export/import-data.md
Labels: p_Software

#2958 RS 7.2: Added example to sign private key with CA
  content/rs/security/certificates/create-certificates.md
Labels: p_Software

#2959 RS 6.4: Added example to sign private key with CA
  content/rs/security/certificates/create-certificates.md
Labels: p_Software

#2960 RS 6.2: Added example to sign private key with CA
  content/rs/security/certificates/create-certificates.md
Labels: p_Software

#2948 DOC-3105: Low-Cost Fixed Plan and DOC-3107: Add that 7.2 is available in us-east-1 to November changelog
  content/rc/changelog/november-2023.md
  content/rc/subscriptions/_index.md
  content/rc/subscriptions/create-fixed-subscription.md
  content/rc/subscriptions/view-fixed-subscription.md
  static/images/rc/subscription-change-fixed-tiers.png
  static/images/rc/subscription-new-cloud-vendor-options-redis-7-preview.png
  static/images/rc/subscription-new-fixed-tiers.png
  static/images/rc/subscription-new-redis-7-preview-toggle.png
Labels: p_Cloud

#2967 Update auto-tiering.md
  content/rs/references/metrics/auto-tiering.md
Labels: p_Software

#2961 Doc 2894 bug bash rc security pt2
  content/rc/security/access-control/data-access-control/configure-acls.md
  content/rc/security/access-control/data-access-control/create-assign-users.md
  content/rc/security/access-control/data-access-control/create-roles.md
  content/rc/security/access-control/data-access-control/role-based-access-control.md
  static/images/rc/data-access-control-menu.png
  static/images/rc/data-access-control-redis-acls-add-or-update.png
  static/images/rc/data-access-control-redis-acls-add.png
  static/images/rc/data-access-control-redis-acls-saved.png
  static/images/rc/data-access-control-redis-acls.png
  static/images/rc/data-access-control-roles-add-or-edit.png
  static/images/rc/data-access-control-roles-add.png
  static/images/rc/data-access-control-roles-select-acl.png
  static/images/rc/data-access-control-roles-select-databases.png
  static/images/rc/data-access-control-roles.png
  static/images/rc/data-access-control-users-add-or-edit.png
  static/images/rc/data-access-control-users-add-role.png
  static/images/rc/data-access-control-users-add.png
  static/images/rc/data-access-control-users-no-users.png
  static/images/rc/data-access-control-users-password-and-finish.png
  static/images/rc/data-access-control-users.png
Labels: p_Cloud

#2954 DOC-2869 Refactored the port information as a pre-step to adding info…
  content/embeds/port-availability-embed.md
  content/embeds/port-collision-avoidance.md
  content/rs/installing-upgrading/install/prepare-install/port-availability.md
  content/rs/installing-upgrading/quickstarts/redis-enterprise-software-quickstart.md
  content/rs/networking/port-configurations.md
Labels: p_Software

#2945 Added warning about cluster.local preventing DNS.
  content/embeds/cluster-setup.md
Labels: p_Software

#2938 DOC-2865 Added file locaation details for RS uninstall script.
  content/rs/installing-upgrading/uninstalling.md
Labels: p_Software

#2935 DOC-2822 Removed duplicate content.
  content/embeds/supported-platforms-embed.md
Labels: p_Software

#2939 DOC-2823 Fixed phrasing to improve clarity per docs bash feedback.
  content/rs/installing-upgrading/install/plan-deployment/persistent-ephemeral-storage.md
Labels: p_Software

#2801 DOC-2530: Add skip for a week to maintenance window docs
  content/rc/subscriptions/maintenance/_index.md
  content/rc/subscriptions/maintenance/set-maintenance-windows.md
Labels: hold-off

#2977 Create v.2.38.0.md
  content/ri/release-notes/v.2.38.0.md
Labels: p_Insight

#2992 DOC-3025 added port, password, and host where missing in cli calls.
  content/rs/databases/connect/troubleshooting-guide.md
Labels: p_Software

#2989 DOC-3008 Fix consistency with db name and db id variables in examples.
  content/rs/databases/active-active/synchronization-mode.md
  content/rs/databases/configure/proxy-policy.md
  content/rs/databases/configure/replica-ha.md
  content/rs/installing-upgrading/creating-support-package.md
  content/rs/references/compatibility/resp.md
Labels: p_Software
