Repository RedisLabs/redislabs-docs, pull requests merged in 2023-04, with the labels that each got.

#2475 Update _index.md
  content/rs/references/rest-api/objects/crdb/health_report/_index.md
Labels: p_Software

#2476 Update clustering.md
  content/rs/databases/durability-ha/clustering.md
Labels: p_Software

#2451 Added missing fields for CRDB creation
  content/rs/references/rest-api/objects/crdb/database_config.md
Labels: p_Software

#2464 K8s: add warning not to edit or delete statefulset
  content/kubernetes/deployment/openshift/openshift-cli.md
  content/kubernetes/deployment/openshift/openshift-operatorhub.md
  content/kubernetes/deployment/quick-start.md
Labels: bug, K8s

#2479 K8s: multi-namespace version note
  content/kubernetes/re-clusters/multi-namespace.md
Labels: bug, K8s

#2473 DOC-1949 RS 6.4.2 April release notes and docs
  content/embeds/supported-platforms-embed.md
  content/rs/clusters/configure/rack-zone-awareness.md
  content/rs/references/rest-api/objects/crdb/health_report/_index.md
  content/rs/release-notes/rs-6-2-18-releases/_index.md
  content/rs/release-notes/rs-6-2-18-releases/rs-6-2-18-43.md
  content/rs/release-notes/rs-6-2-18-releases/rs-6-2-18-49.md
  content/rs/release-notes/rs-6-2-18-releases/rs-6-2-18-58.md
  content/rs/release-notes/rs-6-2-18-releases/rs-6-2-18-65.md
  content/rs/release-notes/rs-6-2-18-releases/rs-6-2-18-70.md
  content/rs/release-notes/rs-6-4-2-releases/_index.md
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-30.md
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-43.md
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-61.md
  content/rs/security/certificates/create-certificates.md
Labels: p_Software

#2478 K8s: correct webhook name for 6.2.4-4
  content/kubernetes/deployment/openshift/openshift-cli.md
  content/kubernetes/deployment/quick-start.md
Labels: bug, K8s

#2483 Update rs-6-4-2-61.md
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-61.md
Labels: p_Software

#2477 Added missing fields for CRDB creation
  content/rs/references/rest-api/objects/crdb/database_config.md
Labels: p_Software

#2484 Adds RDI private preview banner
  content/rdi/_index.md
  content/rdi/quickstart/_index.md
Labels: rdi

#2485 Add RDI preview banner
  content/rdi/_index.md
  content/rdi/quickstart/_index.md
Labels: rdi

#2474 I think that the value for rackAwarenessNodeLabel is incorrect
  content/kubernetes/memory/node-selection.md
Labels: bug, K8s

#2486 K8s: DOC-2117 warning
  content/kubernetes/re-clusters/upgrade-redis-cluster.md
Labels: enhancement, K8s

#2489 DOC-2129: Create Access Control and Data Access Control landing pages
  content/rc/security/_index.md
  content/rc/security/access-control/_index.md
  content/rc/security/access-control/data-access-control/_index.md
  content/rc/security/access-control/data-access-control/create-assign-users.md
  content/rc/security/access-control/data-access-control/default-user.md
Labels: p_Cloud

#2495 Update create-certificates.md
  content/rs/security/certificates/create-certificates.md
Labels: p_Software

#2496 DOC-2120 K8s 6.4.2-5 release notes
  content/kubernetes/deployment/openshift/openshift-cli.md
  content/kubernetes/deployment/quick-start.md
  content/kubernetes/re-clusters/upgrade-redis-cluster.md
  content/kubernetes/release-notes/6-2-18-releases/_index.md
  content/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-3.md
  content/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-41-jan-2023.md
  content/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-41.md
  content/kubernetes/release-notes/6-4-2-releases/6-4-2-5.md
  content/kubernetes/release-notes/6-4-2-releases/_index.md
  content/kubernetes/release-notes/6-4-2-releases/k8s-6-4-2-4.md
Labels: K8s, hold-off

#2500 RS: Fix link and note format
  content/rs/databases/create.md
Labels: p_Software

#2491 RC Security Reorg Phase 1: Access control section
  content/glossary/_index.md
  content/rc/_index.md
  content/rc/accounts/account-settings.md
  content/rc/changelog/january-2023.md
  content/rc/databases/monitor-performance.md
  content/rc/security/_index.md
  content/rc/security/access-control/_index.md
  content/rc/security/access-control/access-management.md
  content/rc/security/access-control/data-access-control/_index.md
  content/rc/security/access-control/data-access-control/configure-acls.md
  content/rc/security/access-control/data-access-control/create-assign-users.md
  content/rc/security/access-control/data-access-control/create-roles.md
  content/rc/security/access-control/data-access-control/default-user.md
  content/rc/security/access-control/data-access-control/role-based-access-control.md
  content/rc/security/access-control/multi-factor-authentication.md
  content/rc/security/access-control/saml-sso/_index.md
  content/rc/security/access-control/saml-sso/saml-integration-auth0.md
  content/rc/security/access-control/saml-sso/saml-integration-aws-identity-center.md
  content/rc/security/access-control/saml-sso/saml-integration-azure-ad.md
  content/rc/security/access-control/saml-sso/saml-integration-google.md
  content/rc/security/access-control/saml-sso/saml-integration-okta-generic.md
  content/rc/security/access-control/saml-sso/saml-integration-okta-org2org.md
  content/rc/security/access-control/saml-sso/saml-integration-ping-identity.md
  content/rc/security/access-control/social-login.md
  content/rc/security/database-security/_index.md
  content/rc/security/database-security/passwords-users-roles.md
  content/rc/security/single-sign-on/_index.md
  content/rs/references/compatibility/commands/server.md
Labels: p_Cloud

#2503 DOC-2155 add known limitations to 6.2 release notes
  content/kubernetes/release-notes/k8s-6-2-10-34-2022-05.md
  content/kubernetes/release-notes/k8s-6-2-10-4-2022-03 copy.md
  content/kubernetes/release-notes/k8s-6-2-10-45-2022-07.md
  content/kubernetes/release-notes/k8s-6-2-12-1.md
  content/kubernetes/release-notes/k8s-6-2-4-1-2021-09.md
  content/kubernetes/release-notes/k8s-6-2-8-11-2022-01.md
  content/kubernetes/release-notes/k8s-6-2-8-15-2022-01.md
  content/kubernetes/release-notes/k8s-6-2-8-2-2021-11.md
Labels: K8s

#2509 Updates and unhides write-behind guide, small fixes to ingest guide
  content/rdi/quickstart/ingest-guide.md
  content/rdi/quickstart/write-behind-guide.md
Labels: rdi

#2505 DOC-1964: Exposed the modules in the 'create new DB' flow
  content/rc/databases/create-database.md
  content/rc/subscriptions/create-flexible-subscription.md
  static/images/rc/flexible-add-database-advanced.png
  static/images/rc/flexible-add-database-basic.png
Labels: p_Cloud, hold-off

#2504 DOC-2154 update admission webhook name
  content/kubernetes/deployment/openshift/openshift-cli.md
  content/kubernetes/deployment/quick-start.md
Labels: K8s

#2510 Adds data denormalization, updates data transformation pipeline
  content/rdi/data-transformation/data-denormalization.md
  content/rdi/data-transformation/data-transformation-pipeline.md
  static/images/rdi/nest-flow.png
Labels: rdi

#2511 Updates the monitoring guide
  content/rdi/monitoring-guide.md
Labels: rdi

#2507 Update enterprise-capabilities.md
  content/modules/enterprise-capabilities.md
Labels: p_Modules

#2517 K8s: fix reaadb typo
  content/kubernetes/active-active/preview/create-reaadb.md
Labels: typos/format, K8s

#2519 2023-04 modules release notes
  content/modules/redisbloom/release-notes/redisbloom-2.4-release-notes.md
  content/modules/redisearch/release-notes/redisearch-2.6-release-notes.md
  content/modules/redisgraph/release-notes/redisgraph-2.10-release-notes.md
  content/modules/redisjson/release-notes/redisjson-2.4-release-notes.md
  content/modules/redistimeseries/release-notes/redistimeseries-1.8-release-notes.md
Labels: p_Modules

#2514 Updates benchmark tool reference
  content/rdi/benchmark.md
Labels: rdi

#2515 RDSC-1203-Grafana-s-dashboard-for-monitoring-Oracle-via-JMX
  content/rdi/resources/debezium_jmx_dashboard_oracle.json
Labels: rdi

#2492 Update collect-logs.md
  content/kubernetes/logs/collect-logs.md
Labels: K8s

#2521 K8s: remove pod security policy DOC-533
  content/kubernetes/faqs/_index.md
Labels: bug, K8s

#2523 Update ciphers.md
  content/rs/security/tls/ciphers.md
Labels: p_Software

#2529 DOC-1136: Document the limitation of "admin" SASL user for memcached
  content/rc/security/access-control/data-access-control/create-assign-users.md
Labels: p_Cloud

#2516 Create v.2.24.0.md
  content/ri/release-notes/v.2.24.0.md
Labels: p_Insight
