Repository RedisLabs/redislabs-docs, pull requests merged in 2023-05, with the labels that each got.

#2533 Update _index.md
  content/rs/release-notes/rs-6-4-2-releases/_index.md
Labels: p_Software

#2534 DOC-2205 fixed quick start security link
  content/rc/rc-quickstart.md
Labels: p_Cloud

#2520 DOC-1839 replace kubectl with oc
  content/kubernetes/deployment/openshift/openshift-cli.md
  content/kubernetes/deployment/quick-start.md
Labels: K8s

#2535 DOC-2163: "Modules" -> "Advanced capabilities" in Cloud
  content/rc/databases/create-database.md
  content/rc/databases/view-edit-database.md
  static/images/rc/database-new-flexible.png
Labels: p_Cloud

#2538 Redisinsight v1.14.0 release notes
  content/ri/release-notes/v1.14.0.md
Labels: p_Insight

#2524 DOC-1874: Add Active Active with ACL to our documentation
  content/rc/security/access-control/data-access-control/active-active-roles.md
  content/rc/security/access-control/data-access-control/configure-acls.md
  content/rc/security/access-control/data-access-control/create-roles.md
  static/images/rc/roles-assign-rules-active-active.png
  static/images/rc/roles-select-aa-database.png
Labels: p_Cloud, hold-off

#2518 RS: Customize envoy ports using rladmin
  content/rs/references/cli-utilities/rladmin/cluster/config.md
Labels: p_Software

#2531 RS REST API: Optimize shard placement query parameters
  content/rs/references/rest-api/requests/bdbs/actions/optimize_shards_placement.md
Labels: p_Software

#2508 Update port-configurations.md
  content/rs/networking/port-configurations.md
Labels: p_Software

#2542 RC: Missing the host in the Import data documentation
  content/rc/databases/import-data.md
Labels: bug, p_Cloud

#2543 Clarified configuration support for RediSearch & RedisGraph
  content/modules/redisearch/commands.md
  content/modules/redisgraph/commands.md
Labels: p_Modules

#2544 DOC-2223 Add notes about ACL verification
  content/rc/security/access-control/data-access-control/active-active-roles.md
  content/rc/security/access-control/data-access-control/configure-acls.md
  content/rc/security/access-control/data-access-control/create-roles.md
Labels: p_Cloud

#2539 RS: Deprecated watchdog_profile & added failure_detection_sensitivity
  content/rs/clusters/optimize/optimization.md
  content/rs/references/cli-utilities/rladmin/tune.md
  content/rs/references/rest-api/objects/cluster_settings.md
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-tba.md
Labels: p_Software

#2541 RS: Amazon Linux 2 support update
  content/embeds/supported-platforms-embed.md
Labels: p_Software

#2546 DOC-2234: URLs for ACS and Entity ID interchanged/incorrect for SAML SSO configuration
  content/rc/security/access-control/saml-sso/saml-integration-google.md
Labels: bug, p_Cloud

#2506 K8s: Node resource eviction thresholds and resource quotas (content migration)
  content/kubernetes/memory/node-resources.md
Labels: K8s

#2501 DOC-1844 K8s: Edit RERC
  content/kubernetes/active-active/preview/edit-rerc.md
Labels: K8s

#2436 Update sqlserver.md
  content/rdi/reference/debezium/sqlserver.md
Labels: rdi

#2527 Update api.md to include username for Redis Cluster
  content/ri/using-redisinsight/api.md
Labels: p_Insight

#2540 DOC-2164 RS 6.4.2 May release notes and docs
  content/embeds/supported-platforms-embed.md
  content/rs/clusters/optimize/optimization.md
  content/rs/networking/port-configurations.md
  content/rs/references/cli-utilities/rladmin/cluster/config.md
  content/rs/references/cli-utilities/rladmin/tune.md
  content/rs/references/rest-api/objects/cluster_settings.md
  content/rs/references/rest-api/requests/bdbs/actions/optimize_shards_placement.md
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-69.md
Labels: p_Software

#2551 Fix typo in RS release notes
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-69.md
Labels: p_Software

#2545 Update tls-protocols.md
  content/rs/security/tls/tls-protocols.md
Labels: p_Software

#2552 Add CRDB restart loop to RS 6.2.18 known issues
  content/rs/release-notes/rs-6-2-18-releases/_index.md
Labels: p_Software

#2555 Amiramm patch 3
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-69.md
Labels: p_Software

#2557 RS: Fix persistence typo
  content/rs/databases/configure/database-persistence.md
Labels: typos/format, p_Software

#2525 DOC-1966: REST API | Align documentation after Fixed API release
  content/rc/api/_index.md
  content/rc/api/examples/create-database.md
  content/rc/api/examples/manage-subscriptions.md
  content/rc/api/examples/update-database.md
  content/rc/api/get-started/_index.md
  content/rc/api/get-started/enable-the-api.md
  content/rc/api/get-started/manage-api-keys.md
  content/rc/api/get-started/process-lifecycle.md
  content/rc/api/get-started/use-rest-api.md
Labels: p_Cloud, hold-off

#2530 RDI: adding write-behind configuration section
  content/rdi/write-behind/_index.md
  content/rdi/write-behind/configuration-guide.md
  content/rdi/write-behind/recipes.md
Labels: security, rdi

#2537 document that TLS files need to be on same node
  content/rdi/quickstart/ingest-guide.md
Labels: rdi

#2526 Updates intro page, adds ingest and write-behind images
  content/rdi/_index.md
  static/images/rdi/ingest.png
  static/images/rdi/write-behind.png
Labels: rdi

#2499 adding example folder and foreach example
  content/rdi/data-transformation/examples/foreach-example.md
Labels: rdi

#2488 DOC-1842 K8s AA preview edit participating clusters
  content/kubernetes/active-active/preview/create-reaadb.md
  content/kubernetes/active-active/preview/edit-clusters.md
  content/kubernetes/active-active/preview/prepare-clusters.md
Labels: K8s

#2550 K8s: Delete REAADB and configmap DOC-2138 DOC-1843
  content/kubernetes/re-clusters/delete_custom_resources.md
Labels: K8s

#2490 DOC-2062 Global config article for K8s AA public preview
  content/kubernetes/active-active/preview/global-config.md
Labels: K8s

#2560 DOC-2237: RC Changelog April and May 2023
  content/rc/changelog/april-2023.md
  content/rc/changelog/may-2023.md
Labels: p_Cloud

#2567 RDSC-1255-fix-gears-links-in-docs-redis-com
  content/rdi/_index.md
  content/rdi/installation/install-redis-gears.md
  content/rdi/quickstart/write-behind-guide.md
Labels: rdi

#2570 RDSC-1260-fix-all-references-to-site-variables-in-rdi-latest
  content/rdi/_index.md
  content/rdi/installation/debezium-server-configuration.md
  content/rdi/installation/debezium-server-deployment.md
  content/rdi/installation/install-k8s.md
  content/rdi/installation/install-offline.md
  content/rdi/installation/install-redis-gears.md
  content/rdi/installation/pacemaker.md
  content/rdi/quickstart/ingest-guide.md
Labels: rdi

#2558 RS: Update databases for new UI part 1
  content/rs/databases/configure/database-persistence.md
  content/rs/databases/delete.md
  content/rs/databases/import-export/schedule-backups.md
  static/images/rs/buttons/button-toggle-actions.png
  static/images/rs/buttons/tmp.txt
Labels: p_Software

#2559 RS: Update cluster for new UI part 1
  content/rs/clusters/configure/cluster-settings.md
  content/rs/clusters/configure/license-keys.md
  content/rs/clusters/monitoring/_index.md
Labels: p_Software

#2571 RDSC-1260-fix-all-references-to-site-variables-in-rdi-latest
  content/rdi/_index.md
  content/rdi/installation/debezium-server-configuration.md
  content/rdi/installation/debezium-server-deployment.md
  content/rdi/installation/install-k8s.md
  content/rdi/installation/install-offline.md
  content/rdi/installation/install-redis-gears.md
  content/rdi/installation/pacemaker.md
  content/rdi/quickstart/ingest-guide.md
Labels: rdi

#2423 Added RedisGears 1.2.6 release notes
  content/modules/redisgears/release-notes/redisgears-1.2-release-notes.md
Labels: p_Modules

#2574 Removed installing RDI from source
  content/rdi/quickstart/ingest-guide.md
Labels: rdi

#2575 DOC-2323 RED-102100 warning for SCC upgrade bug
  content/kubernetes/re-clusters/upgrade-redis-cluster.md
  content/kubernetes/release-notes/6-2-18-releases/_index.md
  content/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-3.md
  content/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-41-jan-2023.md
  content/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-41.md
  content/kubernetes/release-notes/6-4-2-releases/6-4-2-5.md
  content/kubernetes/release-notes/6-4-2-releases/_index.md
  content/kubernetes/release-notes/6-4-2-releases/k8s-6-4-2-4.md
Labels: bug

#2580 k8s: Fix possible typo for REDB deletion warning
  content/kubernetes/re-clusters/delete_custom_resources.md
Labels: K8s, doc_bug

#2577 RI: Fixed date in link title for RI v.2.24.0 release notes
  content/ri/release-notes/v.2.24.0.md
Labels: p_Insight

#2582 DOC-2121: Update GCP marketplace integration docs page
  content/rc/cloud-integrations/gcp-marketplace/_index.md
Labels: p_Cloud

#2578 DOC-2244 remove CRD steps and banners
  content/kubernetes/active-active/preview/_index.md
  content/kubernetes/active-active/preview/create-reaadb.md
  content/kubernetes/active-active/preview/edit-clusters.md
  content/kubernetes/active-active/preview/edit-rerc.md
  content/kubernetes/active-active/preview/global-config.md
  content/kubernetes/active-active/preview/prepare-clusters.md
Labels: next version, K8s

#2584 Update config.md
  content/rs/references/cli-utilities/rladmin/cluster/config.md
Labels: p_Software

#2583 Create v.2.26.0.md
  content/ri/release-notes/v.2.26.0.md
Labels: p_Insight

#2547 Removed RedisAI
  content/embeds/modules.html
  content/embeds/tryout-redisai.md
  content/modules/enterprise-capabilities.md
  content/modules/redisai/_index.md
  content/modules/redisai/redisai-quickstart.md
  content/modules/redisai/release-notes/_index.md
  content/modules/redisai/release-notes/redisai-1.0-release-notes.md
  content/modules/redisai/release-notes/redisai-1.2-release-notes.md
  website.json
Labels: p_Modules
