Repository RedisLabs/redislabs-docs, pull requests merged in 2023-01, with the labels that each got.

#2286 SAML docs updates
  content/rc/security/single-sign-on/saml-sso.md
Labels: p_Cloud

#2294 K8s - release note order error
  content/kubernetes/release-notes/k8s-6-2-18-41.md
Labels: K8s

#2281 Remove outdated and redundant tanzu install DOC-1785
  content/glossary/_index.md
  content/kubernetes/architecture/operator.md
  content/kubernetes/deployment/_index.md
  content/kubernetes/deployment/quick-start.md
  content/kubernetes/deployment/tanzu.md
  content/kubernetes/deployment/tanzu/pcf/_index.md
  content/kubernetes/memory/persistent-volumes.md
  content/kubernetes/reference/cluster-options.md
Labels: K8s

#2282 DOC-1664 & DOC-1802
  content/kubernetes/deployment/quick-start.md
  content/kubernetes/re-databases/db-controller.md
Labels: K8s

#2252 Update routes.md
  content/kubernetes/re-databases/routes.md
Labels: K8s

#2299 RS: Fix link and typos
  content/rs/databases/memory-performance/memory-limit.md
Labels: p_Software

#2306 DOC-1816 - RS: Update OSS Cluster API doc
  content/rs/databases/configure/oss-cluster-api.md
  static/images/rs/oss-cluster-api-database-configuration.png
  static/images/rs/oss-cluster-api-database-create.png
Labels: p_Software

#2305 RC Private Service Connect feedback updates
  content/rc/security/private-service-connect.md
Labels: p_Cloud

#2279 K8s: Flexible deployment/multi-namespace feature DOC-529
  content/kubernetes/deployment/deployment-options.md
  content/kubernetes/re-clusters/multi-namespace.md
  static/images/platforms/k8s-deploy-cross-namespaces.png
  static/images/platforms/k8s-deploy-many-to-many.png
  static/images/platforms/k8s-deploy-multicluster-antipattern.png
  static/images/platforms/k8s-deploy-one-to-many.png
  static/images/platforms/k8s-deploy-one-to-one.png
Labels: K8s

#2309 Edit RS audit events reference tables
  content/rs/security/audit-events.md
Labels: p_Software

#2308 RS /nodes/status REST API requests
  content/rs/installing-upgrading/upgrading.md
  content/rs/references/rest-api/requests/nodes/status.md
  content/rs/release-notes/rs-6-2-18.md
Labels: p_Software

#2311 RS PEM encryption references
  content/rs/references/cli-utilities/rladmin/cluster/config.md
  content/rs/references/rest-api/objects/cluster/_index.md
Labels: p_Software

#2313 K8s product name cleanup
  changelog.md
  content/embeds/supported-platforms-embed.md
  content/glossary/_index.md
  content/kubernetes/_index.md
  content/kubernetes/architecture/_index.md
  content/kubernetes/architecture/operator.md
  content/kubernetes/deployment/_index.md
  content/kubernetes/deployment/deployment-options.md
  content/kubernetes/deployment/openshift/_index.md
  content/kubernetes/deployment/openshift/openshift-cli.md
  content/kubernetes/deployment/openshift/openshift-operatorhub.md
  content/kubernetes/deployment/quick-start.md
  content/kubernetes/deployment/using-kustomize.md
  content/kubernetes/faqs/_index.md
  content/kubernetes/memory/node-selection.md
  content/kubernetes/old-index.md
  content/kubernetes/re-clusters/connect-prometheus-operator.md
  content/kubernetes/re-databases/db-controller.md
  content/kubernetes/re-databases/set-up-ingress-controller.md
  content/kubernetes/reference/_index.md
  content/kubernetes/reference/supported_k8s_distributions.md
  content/kubernetes/release-notes/k8s-5-4-10-8-january-2020.md
  content/kubernetes/release-notes/k8s-6-0-6-6-2020-06.md
  content/kubernetes/security/_index.md
  content/kubernetes/security/manage-rec-credentials.md
  content/rs/security/access-control/ldap/cluster-based-ldap-authentication.md
Labels: K8s

#2302 RC pub/sub ACLs
  content/rc/security/database-security/passwords-users-roles.md
Labels: p_Cloud

#2307 RC Fixed subscriptions - Redis 7 preview
  content/rc/subscriptions/create-fixed-subscription.md
  static/images/rc/subscription-new-cloud-vendor-options-redis-7-preview.png
  static/images/rc/subscription-new-redis-7-preview-toggle.png
Labels: p_Cloud

#2316 Archive previous K8s release notes
  content/kubernetes/release-notes/previous-releases/_index.md
  content/kubernetes/release-notes/previous-releases/k8s-5-4-10-8.md
  content/kubernetes/release-notes/previous-releases/k8s-5-4-14-2.md
  content/kubernetes/release-notes/previous-releases/k8s-6-0-12-5.md
  content/kubernetes/release-notes/previous-releases/k8s-6-0-20-12.md
  content/kubernetes/release-notes/previous-releases/k8s-6-0-20-4.md
  content/kubernetes/release-notes/previous-releases/k8s-6-0-6-11.md
  content/kubernetes/release-notes/previous-releases/k8s-6-0-6-23.md
  content/kubernetes/release-notes/previous-releases/k8s-6-0-6-24.md
  content/kubernetes/release-notes/previous-releases/k8s-6-0-6-6.md
  content/kubernetes/release-notes/previous-releases/k8s-6-0-8-1.md
  content/kubernetes/release-notes/previous-releases/k8s-6-0-8-20.md
Labels: K8s

#2318 Ciphers update will not append to existing list but will configure the list of ciphers provided in the command
  content/rs/security/tls/ciphers.md
Labels: p_Software

#2127 Update ciphers.md
  content/rs/security/tls/ciphers.md
Labels: p_Software

#2126 Update ciphers.md
  content/rs/security/tls/ciphers.md
Labels: p_Software

#2295 Clarify deploying to existing VPC
  content/rc/subscriptions/create-flexible-subscription.md
Labels: p_Cloud

#2320 New in-page banner shortcode & partial
  layouts/_default/baseof.html
  layouts/partials/banner-article.html
  layouts/partials/flex/body-beforecontent.html
  layouts/shortcodes/banner-article.html
  static/theme-flex/style.css
Labels: infrastructure

#2283 DOC-1811 - RC: Name field updates for account & profile
  content/rc/accounts/user-profile.md
  content/rc/security/access-management.md
  static/images/rc/access-mgmt-add-user-dialog.png
  static/images/rc/access-mgmt-edit-user-dialog.png
  static/images/rc/user-profile-settings.png
Labels: p_Cloud

#2322 Redirect k8s v6.x to latest
  website.json
Labels: infrastructure, K8s

#2325 RC pub/sub ACLs - Redis 7 differences
  content/rc/security/database-security/passwords-users-roles.md
Labels: p_Cloud

#2324 Removed outdated GCP Marketplace team management section
  content/rc/security/access-management.md
Labels: p_Cloud

#2327 K8s: remove orion content from public site for namespace labels
  content/kubernetes/re-clusters/multi-namespace.md
Labels: bug, K8s

#2333 DOC-1867: RS - "Manage passwords" has broken Internal link
  content/rs/security/access-control/manage-users/manage-passwords.md
Labels: p_Software

#2330 Update rs-6-2-18.md
  content/rs/release-notes/rs-6-2-18.md
Labels: p_Software

#2331 Update mount point import
  content/rs/databases/import-export/import-data.md
Labels: p_Software

#2332 Import enhancement
  content/rs/release-notes/rs-6-2-12.md
Labels: p_Software
