Repository RedisLabs/redislabs-docs, pull requests merged in 2024-03, with the labels that each got.

#3163 warn about crdb
  content/rdi/_index.md
Labels: rdi

#3154 RC: Add information as to why throughput may vary to the create database page
  content/rc/databases/create-database.md
  content/rc/subscriptions/create-flexible-subscription.md
Labels: p_Cloud

#3160 RS: Unlock users in the Cluster Manager UI
  content/rs/security/access-control/manage-users/login-lockout.md
  static/images/rs/screenshots/access-control/users-locked-out.png
  static/images/rs/screenshots/access-control/users-reset-to-unlock.png
  static/images/rs/screenshots/access-control/users-reset-user-password-dialog.png
Labels: p_Software

#3158 RS: Updates for expired cluster license
  content/rs/clusters/configure/license-keys.md
Labels: p_Software

#3167 Rdi-prv-callout
  content/rdi/_index.md
Labels: rdi

#3141 RS: Add port 10050 to reserved ports
  content/rs/networking/port-configurations.md
Labels: p_Software

#3168 RS: Add Redis v6.x A-A modules limitation to Fuji release notes
  content/rs/release-notes/rs-7-2-4-releases/_index.md
  content/rs/release-notes/rs-7-4-2-releases/_index.md
  content/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-54.md
Labels: p_Software

#3173 Update module release notes.md
  content/stack/release-notes/redisbloom/redisbloom-2.4-release-notes.md
  content/stack/release-notes/redisbloom/redisbloom-2.6-release-notes.md
  content/stack/release-notes/redisearch/redisearch-2.6-release-notes.md
  content/stack/release-notes/redisearch/redisearch-2.8-release-notes.md
  content/stack/release-notes/redisjson/redisjson-2.4-release-notes.md
  content/stack/release-notes/redisjson/redisjson-2.6-release-notes.md
  content/stack/release-notes/redistimeseries/redistimeseries-1.10-release-notes.md
  content/stack/release-notes/redistimeseries/redistimeseries-1.8-release-notes.md
Labels: p_Modules

#3155 RS: Upgrade OS with custom directories
  content/rs/installing-upgrading/install/customize-install-directories.md
  content/rs/installing-upgrading/upgrading/upgrade-os.md
Labels: p_Software

#3175 K8s: Roosevelt maint 1
  content/kubernetes/release-notes/7-2-4-releases/7-2-4-12-03-24.md
Labels: K8s

#3162 Update _index.md
  content/rs/references/rest-api/objects/bdb/_index.md
Labels: p_Software

#3142 K8s: correct ingress controller links
  content/kubernetes/networking/ingressorroutespec.md
Labels: K8s, doc_bug

#3172 RS: Add persistent_node_removal to cluster settings REST API object
  content/rs/references/rest-api/objects/cluster_settings.md
Labels: p_Software

#3176 K8s release notes change weight
  content/kubernetes/release-notes/7-2-4-releases/7-2-4-12-03-24.md
Labels: K8s

#3177 RC: SAML formatting fixes
  content/rc/security/access-control/saml-sso/saml-integration-auth0.md
  content/rc/security/access-control/saml-sso/saml-integration-okta-generic.md
  content/rc/security/access-control/saml-sso/saml-integration-okta-org2org.md
Labels: p_Cloud

#3185 fix k8s redirects
  website.json
Labels: infrastructure

#3187 RS: Moved resolved issue RS62552 to correct release notes
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-43.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52.md
Labels: p_Software, doc_bug

#3186 RS: node_avg_latency should be in milliseconds
  content/rs/clusters/monitoring/prometheus-metrics-definitions.md
Labels: p_Software

#3191 RC: Screenshot cropping
  static/images/rc/aws-marketplace-rc-flexible-plan.png
  static/images/rc/data-access-control-menu.png
  static/images/rc/gcp-marketplace-rc-payg-plan.png
  static/images/rc/saml/ad_saml_10.png
  static/images/rc/saml/ad_saml_21.png
  static/images/rc/saml/ad_saml_22.png
  static/images/rc/saml/auth0_saml_11.png
  static/images/rc/saml/auth0_saml_14.png
  static/images/rc/saml/auth0_saml_15.png
  static/images/rc/saml/aws_iam_identity_center_saml_15.png
  static/images/rc/saml/aws_iam_identity_center_saml_16.png
  static/images/rc/saml/aws_iam_identity_center_saml_19.png
  static/images/rc/saml/aws_iam_identity_center_saml_22.png
  static/images/rc/saml/aws_iam_identity_center_saml_7.png
  static/images/rc/saml/aws_iam_identity_center_saml_8.png
  static/images/rc/saml/aws_iam_identity_center_saml_9.png
  static/images/rc/saml/google_workspace_saml_19.png
  static/images/rc/saml/google_workspace_saml_20.png
  static/images/rc/saml/google_workspace_saml_4.png
  static/images/rc/saml/google_workspace_saml_5.png
  static/images/rc/saml/okta_saml_app_int_14.png
  static/images/rc/saml/okta_saml_app_int_15.png
  static/images/rc/saml/okta_saml_app_int_16.png
  static/images/rc/saml/okta_saml_app_int_17.png
  static/images/rc/saml/okta_saml_app_int_18.png
  static/images/rc/saml/ping_identity_saml_12.png
  static/images/rc/saml/ping_identity_saml_15.png
  static/images/rc/saml/ping_identity_saml_18.png
  static/images/rc/saml/ping_identity_saml_19.png
  static/images/rc/saml/sm_saml_1.png
  static/images/rc/saml/sm_saml_11.png
  static/images/rc/saml/sm_saml_12.png
  static/images/rc/saml/sm_saml_13.png
  static/images/rc/saml/sm_saml_2.png
  static/images/rc/saml/sm_saml_3.png
  static/images/rc/saml/sm_saml_8.png
  static/images/rc/saml/sm_saml_9.png
Labels: p_Cloud

#3184 RS: Improve min_redis_pack_version & min_redis_version descriptions
  content/rs/references/rest-api/objects/module.md
Labels: p_Software

#3174 RC: Throughput section changes
  content/rc/databases/create-database.md
Labels: p_Cloud

#3195 RC: Enabling private service connection causes issues with the public endpoint
  content/rc/security/private-service-connect.md
Labels: p_Cloud

#3143 RC: CIDR whitelist and connectivity options fix
  content/embeds/rc-vpc-peering-cidr-list.md
  content/rc/security/aws-transit-gateway.md
  content/rc/security/cidr-whitelist.md
  content/rc/security/vpc-peering.md
Labels: p_Cloud, doc_bug

#3199 Update database-persistence.md
  content/rs/databases/configure/database-persistence.md
Labels: p_Software

#3165 RS: Fuji March release docs
  content/rs/clusters/configure/license-keys.md
  content/rs/release-notes/rs-7-4-2-releases/_index.md
  content/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-104.md
  content/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-54.md
  content/rs/security/access-control/manage-users/login-lockout.md
  static/images/rs/screenshots/access-control/users-locked-out.png
  static/images/rs/screenshots/access-control/users-reset-to-unlock.png
  static/images/rs/screenshots/access-control/users-reset-user-password-dialog.png
Labels: p_Software, hold-off

#3201 RC Packaging: Quick Start
  content/rc/rc-quickstart.md
  static/images/rc/quickstart-create-free-database.png
  static/images/rc/quickstart-database-list.png
  static/images/rc/quickstart-database-overview.png
Labels: p_Cloud

#3193 RS: Cluster license requirements & trial license generation
  content/rs/clusters/configure/license-keys.md
  content/rs/references/rest-api/objects/bootstrap/_index.md
  content/rs/references/rest-api/requests/bootstrap/_index.md
  content/rs/references/rest-api/requests/license/_index.md
Labels: p_Software

#3202 RS: Add view_debugging_info to REST API permissions tables
  content/rs/references/rest-api/permissions.md
Labels: p_Software

#3197 RS: /v1/proxies REST API reference
  content/rs/references/rest-api/objects/proxy.md
  content/rs/references/rest-api/requests/proxies/_index.md
Labels: p_Software

#3198 RS: syncer_state REST API references
  content/rs/references/rest-api/requests/bdbs/syncer_state/_index.md
  content/rs/references/rest-api/requests/bdbs/syncer_state/crdt.md
  content/rs/references/rest-api/requests/bdbs/syncer_state/replica.md
Labels: p_Software

#3205 RC New Packaging: Databases landing page
  content/rc/databases/_index.md
Labels: p_Cloud

#3203 RC Packaging: Split create databases into 3 and implement Essentials flow
  content/embeds/rc-create-db-first-steps.md
  content/embeds/rc-pro-use-cases-billing-units.md
  content/rc/api/_index.md
  content/rc/api/examples/update-database.md
  content/rc/cloud-integrations/aws-marketplace/aws-bedrock/set-up-redis.md
  content/rc/cloud-integrations/confluent-cloud.md
  content/rc/databases/_index.md
  content/rc/databases/configuration/advanced-capabilities.md
  content/rc/databases/configuration/clustering.md
  content/rc/databases/configuration/high-availability.md
  content/rc/databases/create-database.md
  content/rc/databases/create-database/_index.md
  content/rc/databases/create-database/create-essentials-database.md
  content/rc/databases/create-database/create-pro-database-existing.md
  content/rc/databases/create-database/create-pro-database-new.md
  content/rc/databases/view-edit-database.md
  content/rc/subscriptions/_index.md
  content/rc/subscriptions/create-fixed-subscription.md
  content/rs/clusters/optimize/oss-cluster-api.md
  static/images/rc/create-database-essentials-cloud-vendor.png
  static/images/rc/create-database-essentials-durability.png
  static/images/rc/create-database-redis-use-cases.png
  static/images/rc/create-database-subscription-essentials.png
  static/images/rc/create-database-subscription-pro-new.png
  static/images/rc/subscription-new-fixed-tiers.png
Labels: p_Cloud

#3204 RC Packaging: View and Edit databases
  content/rc/databases/view-edit-database.md
Labels: p_Cloud

#3181 RS: Cannot mix RAM-only and flash clusters in Active-Active config
  content/rs/databases/active-active/create.md
  content/rs/databases/active-active/manage.md
  content/rs/databases/active-active/planning.md
Labels: p_Software

#3206 RS: Recover cluster - removed incorrect rladmin cluster join syntax, removed expands, added reference links
  content/rs/clusters/cluster-recovery.md
Labels: p_Software

#3208 added alloydb
  content/rdi/_index.md
Labels: rdi

#3207 added alloydb
  content/rdi/_index.md
Labels: rdi

#3200 RC: Active-Passive with TLS
  content/rc/changelog/march-2024.md
  content/rc/databases/migrate-databases.md
  content/rc/subscriptions/upgrade-fixed-flexible.md
  static/images/rc/button-database-uri-add.png
  static/images/rc/database-add-account-path-list.png
  static/images/rc/icon-database-save-active-passive.png
  static/images/rc/migrate-data-active-passive-enable.png
  static/images/rc/migrate-data-add-active-passive.png
  static/images/rc/migrate-data-specify-source-uri.png
  static/images/rc/migrate-data-tls-client-cert.png
  static/images/rc/migrate-data-tls-server-cert.png
Labels: p_Cloud, hold-off

#3194 RC: Maintenance windows | update docs
  content/rc/subscriptions/maintenance/_index.md
  content/rc/subscriptions/maintenance/set-maintenance-windows.md
Labels: p_Cloud

#3212 RS: Copy RS 6.4.2-103 release notes to 6.4 version branch
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-103.md
Labels: p_Software

#3213 RS: Add supported platforms snapshot disclaimer to previous RS release notes
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-103.md
  content/rs/release-notes/rs-7-2-4-releases/_index.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-105.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-64.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-72.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-92.md
  content/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-54.md
Labels: p_Software

#3211 RC New Packaging: Remove Create Subscription pages
  content/embeds/create-subscription-next-steps.md
  content/rc/_index.md
  content/rc/changelog/august-2023.md
  content/rc/changelog/december-2023.md
  content/rc/changelog/february-2024.md
  content/rc/changelog/january-2023.md
  content/rc/changelog/june-2023.md
  content/rc/changelog/march-2023.md
  content/rc/changelog/november-2023.md
  content/rc/cloud-integrations/aws-marketplace/_index.md
  content/rc/cloud-integrations/aws-marketplace/aws-bedrock/set-up-redis.md
  content/rc/cloud-integrations/prometheus-integration.md
  content/rc/databases/active-active-redis.md
  content/rc/databases/configuration/advanced-capabilities.md
  content/rc/databases/create-database/create-active-active-database.md
  content/rc/databases/create-database/create-essentials-database.md
  content/rc/databases/create-database/create-pro-database-new.md
  content/rc/security/aws-transit-gateway.md
  content/rc/security/private-service-connect.md
  content/rc/subscriptions/_index.md
  content/rc/subscriptions/create-fixed-subscription/_index.md
  content/rc/subscriptions/create-flexible-subscription.md
  content/rc/subscriptions/upgrade-essentials-pro.md
  content/rc/subscriptions/view-essentials-subscription/_index.md
  content/rc/subscriptions/view-essentials-subscription/essentials-plan-details.md
  content/rc/subscriptions/view-pro-subscription.md
  content/rs/databases/active-active/develop/data-types/json.md
  content/stack/json/active-active.md
Labels: p_Cloud

#3215 RS: Copy supported platforms snapshot release notes disclaimer to 7.2 version branch
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-103.md
  content/rs/release-notes/rs-7-2-4-releases/_index.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-105.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-64.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-72.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-92.md
  content/rs/security/certificates/ocsp-stapling.md
Labels: p_Software

#3223 RS: Deprecation version for replica HA cluster policy should be 7.2.4, not 7.4.2
  content/rs/databases/configure/replica-ha.md
  content/rs/references/cli-utilities/rladmin/tune.md
  content/rs/references/rest-api/objects/cluster_settings.md
  content/rs/release-notes/rs-7-2-4-releases/_index.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52.md
Labels: p_Software, doc_bug

#3224 RS: Copy fixed deprecation version for replica HA cluster policy to 7.2 version branch
  content/rs/databases/configure/replica-ha.md
  content/rs/references/cli-utilities/rladmin/tune.md
  content/rs/references/rest-api/objects/cluster_settings.md
  content/rs/release-notes/rs-7-2-4-releases/_index.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52.md
Labels: p_Software, doc_bug

#3225 K8s: swordfish maint 1
  content/kubernetes/release-notes/7-4-2-releases/7-4-2-03-24.md
  content/kubernetes/release-notes/7-4-2-releases/7-4-2-2.md
  content/kubernetes/release-notes/7-4-2-releases/_index.md
Labels: K8s

#3218 RC: Throughput moving to ops/sec for search & query changelog updates
  content/rc/changelog/april-2024.md
Labels: p_Cloud
