Repository RedisLabs/redislabs-docs, pull requests merged in 2024-01, with the labels that each got.

#3054 Update memory-limit.md
  content/rs/databases/auto-tiering/_index.md
  content/rs/databases/memory-performance/memory-limit.md
Labels: p_Software

#3051 RS: Quickstart and test connection edits
  content/rs/databases/connect/_index.md
  content/rs/databases/connect/test-client-connectivity.md
  content/rs/installing-upgrading/quickstarts/docker-quickstart.md
  content/rs/installing-upgrading/quickstarts/redis-enterprise-software-quickstart.md
Labels: p_Software

#3058 Update clustering.md
  content/rc/databases/configuration/clustering.md
Labels: p_Cloud

#3048 Create v.2.40.0.md
  content/ri/release-notes/v.2.40.0.md
Labels: p_Insight

#3043 RC: Specify removing the source database in the upgrade from Fixed->Flexible docs
  content/rc/subscriptions/upgrade-fixed-flexible.md
Labels: p_Cloud

#3045 RC: Limiting the number of databases per plan to only one database
  content/embeds/rc-fixed-upgrade-limitation.md
  content/rc/changelog/january-2024.md
  content/rc/subscriptions/create-fixed-subscription.md
  content/rc/subscriptions/view-fixed-subscription.md
  static/images/rc/subscription-change-fixed-tiers.png
  static/images/rc/subscription-new-fixed-tiers.png
Labels: p_Cloud, hold-off

#3064 RC: Wait command is available on flexible subscription
  content/rs/references/compatibility/commands/generic.md
Labels: p_Cloud, doc_bug

#3063 RC: Verify which database settings can be changed and update edit database table
  content/rc/databases/view-edit-database.md
Labels: bug, p_Cloud

#3060 K8s: typo fix
  content/kubernetes/reference/supported_k8s_distributions.md
Labels: typos/format, K8s

#3047 K8s: clarify wording REAADB limitation
  content/kubernetes/active-active/_index.md
Labels: K8s

#3067 Update enterprise-capabilities.md
  content/stack/enterprise-capabilities.md
Labels: p_Modules

#3061 RC: Confluent integration
  content/rc/accounts/account-settings.md
  content/rc/cloud-integrations/aws-cloud-accounts/_index.md
  content/rc/cloud-integrations/confluent-cloud.md
  static/images/rc/account-settings-integrations-confluent.png
  static/images/rc/confluent-create-connector.png
Labels: p_Cloud

#3059 Add tags to all instances referencing the Debezium
  content/rdi/installation/debezium-server-deployment.md
  content/rdi/installation/install-k8s.md
  content/rdi/installation/pacemaker.md
Labels: rdi

#3072 RC: Remove incorrect sentence from Redis Cloud databases page
  content/rc/databases/delete-database.md
Labels: bug, p_Cloud

#3070 RS: Add CVE-2023-41056 to 7.2.4 maintenance release notes
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-64.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-72.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-92.md
Labels: p_Software

#3057 RS: Removed rack-zone awareness UI enhancement from 7.2.4
  content/rs/clusters/configure/rack-zone-awareness.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-92.md
Labels: p_Software

#3074 RS: Fix DB replication backlog link in Replica Of doc
  content/rs/databases/import-export/replica-of/_index.md
Labels: p_Software

#3081 Update resp.md
  content/rs/references/compatibility/resp.md
Labels: p_Software

#3021 RS: TLS 1.3
  content/rs/references/cli-utilities/rladmin/cluster/config.md
  content/rs/references/rest-api/objects/cluster/_index.md
  content/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-69.md
  content/rs/security/encryption/_index.md
  content/rs/security/encryption/internode-encryption.md
  content/rs/security/encryption/tls/ciphers.md
  content/rs/security/encryption/tls/tls-protocols.md
  static/images/rs/screenshots/cluster/security-tls-cipher-suites-edit.png
  static/images/rs/screenshots/cluster/security-tls-cipher-suites-view.png
  static/images/rs/screenshots/cluster/security-tls-protocols-edit.png
Labels: p_Software

#3069 RS: Bundle 2 Redis Stack feature sets
  content/rs/references/cli-utilities/rladmin/status.md
  content/rs/references/rest-api/objects/bdb/_index.md
  content/rs/references/rest-api/requests/bdbs/upgrade.md
  content/stack/install/_index.md
  content/stack/install/add-module-to-cluster.md
  content/stack/install/add-module-to-database.md
Labels: p_Software, p_Modules

#3075 Update port-configurations.md
  content/rs/networking/port-configurations.md
Labels: p_Software

#3052 RS: Supported platform updates & Amazon Linux note
  content/embeds/supported-platforms-embed.md
  content/rs/installing-upgrading/product-lifecycle.md
Labels: p_Software

#3046 RS: UI updates for Active-Active docs
  content/embeds/json-active-active-command-differences.md
  content/embeds/json-active-active-conflict-resolution.md
  content/rs/databases/active-active/causal-consistency.md
  content/rs/databases/active-active/create.md
  content/rs/databases/active-active/develop/data-types/json.md
  content/rs/databases/active-active/get-started.md
  content/rs/databases/active-active/manage.md
  content/rs/databases/configure/_index.md
  content/rs/databases/create.md
  content/rs/databases/import-export/migrate-to-active-active.md
  content/rs/databases/import-export/replica-of/create.md
  content/stack/install/add-module-to-database.md
  content/stack/json/active-active.md
  static/images/rs/buttons/delete-button.png
  static/images/rs/screenshots/cluster/setup/cluster-license-key.png
  static/images/rs/screenshots/cluster/setup/config-cluster1.png
  static/images/rs/screenshots/cluster/setup/create-cluster.png
  static/images/rs/screenshots/cluster/setup/node-settings.png
  static/images/rs/screenshots/databases/active-active-databases/create-a-a-db-json-search.png
  static/images/rs/screenshots/databases/active-active-databases/create-a-a-db-participating-clusters.png
  static/images/rs/screenshots/databases/active-active-databases/create-db-add-participating-clusters.png
  static/images/rs/screenshots/databases/active-active-databases/enable-causal-consistency.png
  static/images/rs/screenshots/databases/active-active-databases/enter-local-admin-credentials-cluster1.png
  static/images/rs/screenshots/databases/active-active-databases/enter-local-admin-credentials.png
  static/images/rs/screenshots/databases/active-active-databases/participating-clusters-add-cluster.png
  static/images/rs/screenshots/databases/active-active-databases/participating-clusters-add-cluster2.png
  static/images/rs/screenshots/databases/active-active-databases/participating-clusters-edit-delete.png
  static/images/rs/screenshots/databases/active-active-databases/quickstart-db-name-port.png
  static/images/rs/screenshots/databases/active-active-databases/quickstart-ha-turn-off-replication.png
  static/images/rs/screenshots/databases/create-db-button-drop-down.png
  static/images/rs/screenshots/databases/create-db-plus-drop-down.png
  static/images/rs/screenshots/databases/migrate-to-active-active/migrate-to-active-active-dialog-current-cluster.png
  static/images/rs/screenshots/databases/migrate-to-active-active/migrate-to-active-active-dialog-external.png
  static/images/rs/screenshots/databases/migrate-to-active-active/migrate-to-active-active-section.png
  static/images/rs/screenshots/databases/migrate-to-active-active/migrate-to-active-active-sync-stopped.png
  static/images/rs/screenshots/databases/migrate-to-active-active/migrate-to-active-active-synced.png
  static/images/rs/screenshots/databases/quick-db-capabilities.png
Labels: p_Software

#3082 RC: Change titles of the view subscription pages
  content/rc/subscriptions/view-fixed-subscription.md
  content/rc/subscriptions/view-flexible-subscription.md
Labels: p_Cloud

#3083 Database Tagging GA
  content/embeds/rc-tags-tag-module.md
  content/rc/changelog/january-2024.md
  content/rc/databases/back-up-data.md
  content/rc/databases/configuration/_index.md
  content/rc/databases/create-database.md
  content/rc/databases/delete-database.md
  content/rc/databases/flush-data.md
  content/rc/databases/import-data.md
  content/rc/databases/migrate-databases.md
  content/rc/databases/tag-database.md
  content/rc/databases/view-edit-database.md
  static/images/rc/database-details-configuration-tab-general-flexible.png
  static/images/rc/database-list-filter-selected.png
  static/images/rc/database-list-filter.png
  static/images/rc/database-new-tags.png
  static/images/rc/migrate-database-select-source.png
  static/images/rc/tags-button-add-tag.png
  static/images/rc/tags-button-manage-tags.png
  static/images/rc/tags-button-save-tags.png
  static/images/rc/tags-database-list.png
  static/images/rc/tags-database-tab.png
  static/images/rc/tags-icon-add-tags.png
  static/images/rc/tags-icon-delete.png
  static/images/rc/tags-icon-edit.png
  static/images/rc/tags-icon-manage-tags.png
  static/images/rc/tags-icon-more-actions.png
  static/images/rc/tags-new-tag.png
  static/images/rc/tags-tag-manager.png
Labels: p_Cloud, hold-off

#3073 K8s: add tkgi 1.16 1.17
  content/kubernetes/reference/supported_k8s_distributions.md
Labels: K8s

#3092 RS: Bug fix to remove default_redis_version from upgrade DB doc
  content/rs/installing-upgrading/upgrading/upgrade-database.md
Labels: p_Software, doc_bug

#3062 RS UI DB defaults: add endpoint config & remove replica HA & S3 import
  content/rs/databases/configure/db-defaults.md
  content/rs/databases/configure/replica-ha.md
  content/rs/references/cli-utilities/rladmin/tune.md
  content/rs/references/rest-api/objects/cluster_settings.md
  static/images/rs/screenshots/databases/config-replica-ha-enabled.png
  static/images/rs/screenshots/databases/db-defaults-endpoint-config-custom.png
  static/images/rs/screenshots/databases/db-defaults.png
Labels: p_Software

#3077 RS: New maintenance mode parameters
  content/rs/clusters/maintenance-mode.md
  content/rs/references/cli-utilities/rladmin/node/maintenance-mode.md
  content/rs/references/cli-utilities/rladmin/node/snapshot.md
  content/rs/references/rest-api/requests/nodes/actions.md
  content/rs/references/rest-api/requests/nodes/snapshots.md
Labels: p_Software

#3080 RS: rlcheck reference options & tests
  content/rs/references/cli-utilities/rlcheck/_index.md
Labels: p_Software

#3084 RS: IPv6 for internal traffic
  content/rs/networking/multi-ip-ipv6.md
  content/rs/references/rest-api/objects/bootstrap/node_identity.md
  content/rs/references/rest-api/objects/node.md
Labels: p_Software

#3085 RS: LDAP auth timeout setting
  content/rs/references/rest-api/objects/ldap.md
  content/rs/references/rest-api/requests/cluster/ldap.md
  content/rs/security/access-control/ldap/enable-role-based-ldap.md
  static/images/rs/screenshots/access-control/ldap-config.png
Labels: p_Software

#3086 RS: /actions/bdb/bdb_uid REST API reference
  content/rs/references/rest-api/requests/actions/_index.md
  content/rs/references/rest-api/requests/actions/bdb.md
Labels: p_Software

#3089 RS: 7.4.2 Fuji release notes draft
  content/rs/release-notes/rs-7-4-2-releases/_index.md
  content/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-tba.md
Labels: p_Software

#3087 RS: Database auto recovery
  content/rs/databases/recover.md
  content/rs/references/rest-api/objects/bdb/_index.md
  content/rs/references/rest-api/objects/cluster_settings.md
Labels: p_Software

#3076 K8s: change delete pods argument to avoid force delete
  content/kubernetes/re-clusters/cluster-recovery.md
Labels: K8s

#3041 K8s: Fix REAAD links and tlsMode example
  content/kubernetes/active-active/create-reaadb.md
  content/kubernetes/active-active/global-config.md
Labels: K8s

#3088 Transit Gateway Public Preview/GA
  content/rc/changelog/january-2024.md
  content/rc/security/aws-transit-gateway.md
  content/rc/subscriptions/view-flexible-subscription.md
  static/images/rc/aws-tgw-add-principal.png
  static/images/rc/subscription-details-connectivity-tab-flexible.png
  static/images/rc/tgw-accept-resource-shares.png
  static/images/rc/tgw-add-additional-cidrs-button.png
  static/images/rc/tgw-add-cidrs-button.png
  static/images/rc/tgw-attachment-more-actions-menu.png
  static/images/rc/tgw-create-attachment-button.png
  static/images/rc/tgw-producer-cidr-copy.png
  static/images/rc/tgw-resource-shares-button.png
  static/images/rc/tgw-share-transit-gateway.png
Labels: p_Cloud

#3097 RS: Fix broken relrefs and links in reference docs
  content/rs/references/compatibility/commands/server.md
  content/rs/references/rest-api/requests/bdbs/replica_sources-alerts.md
  content/rs/references/rest-api/requests/modules/_index.md
Labels: p_Software

#3096 RC: Update external account permissions for TransitGateway
  content/rc/cloud-integrations/aws-cloud-accounts/iam-resources/aws-console.md
  content/rc/security/aws-transit-gateway.md
Labels: p_Cloud

#3103 RC: Change the access control section in Docs to prepare for new packaging
  content/rc/security/access-control/access-management.md
Labels: p_Cloud
