Repository RedisLabs/redislabs-docs, pull requests merged in 2024-02, with the labels that each got.

#3094 Release notes for RedisInsight 2.42
  content/ri/release-notes/v.2.42.0.md
Labels: p_Insight

#3108 RS: Fix broken RHEL links
  content/rs/clusters/configure/sync-clocks.md
Labels: p_Software

#3109 RS: Add recovering_cluster state to bootstrap REST API reference
  content/rs/references/rest-api/requests/bootstrap/_index.md
Labels: p_Software

#3106 RC: Backup data: Verify region support for cloud backups
  content/rc/databases/back-up-data.md
Labels: p_Cloud, doc_bug

#3105 RC: Redis cloud compatibility and OSS Cluster API
  content/embeds/rc-rs-oss-compatibility.md
  content/rc/compatibility.md
  content/rc/databases/create-database.md
  content/rc/databases/view-edit-database.md
  content/rc/security/private-service-connect.md
  content/rs/clusters/optimize/oss-cluster-api.md
  content/rs/references/compatibility/_index.md
Labels: p_Cloud

#3100 RS 7.4 version selector updates - 6.4-build branch
  layouts/404.html
  layouts/partials/flex/body-beforecontent.html
  layouts/partials/flex/scripts.html
Labels: infrastructure, p_Software, hold-off

#3101 RS 7.4 version selector updates - 6.2-build branch
  layouts/404.html
  layouts/partials/flex/body-beforecontent.html
  layouts/partials/flex/scripts.html
Labels: infrastructure, p_Software, hold-off

#3102 RS 7.4 version selector updates - 6.0-build branch
  layouts/404.html
  layouts/partials/flex/body-beforecontent.html
  layouts/partials/flex/scripts.html
Labels: infrastructure, p_Software, hold-off

#3117 Removed a few old S3 redirects
  website.json
Labels: infrastructure

#3107 K8s: Gears cluster recovery bug
  content/kubernetes/release-notes/6-4-2-releases/6-4-2-8.md
Labels: bug, K8s

#3114 RC: Update Cloud Integrations pages
  content/rc/cloud-integrations/aws-marketplace/_index.md
  content/rc/cloud-integrations/gcp-marketplace/_index.md
  static/images/rc/aws-marketplace-map-account-dialog.png
  static/images/rc/gcp-marketplace-map-account-dialog.png
Labels: p_Cloud

#3113 RC: Add more info for CIDR overlap
  content/rc/changelog/february-2024.md
Labels: p_Cloud

#3115 RC: Fix link anchors and other typos
  content/rc/api/examples/update-database.md
  content/rc/api/get-started/enable-the-api.md
  content/rc/api/get-started/manage-tasks.md
  content/rc/cloud-integrations/aws-marketplace/aws-bedrock/create-knowledge-base.md
  content/rc/cloud-integrations/prometheus-integration.md
  content/rc/databases/create-database.md
  content/rc/databases/flush-data.md
  content/rc/databases/view-edit-database.md
  content/rc/security/access-control/data-access-control/create-roles.md
  content/rc/security/access-control/data-access-control/role-based-access-control.md
  content/rc/security/database-security/tls-ssl.md
  content/rc/subscriptions/create-active-active-subscription.md
  content/rc/subscriptions/upgrade-fixed-flexible.md
  content/rc/subscriptions/view-fixed-subscription.md
Labels: bug, p_Cloud

#3111 RC: Point to edit flow for RESP compatibility
  content/rc/compatibility.md
Labels: p_Cloud

#3093 RS 7.2.4 January maintenance release
  content/embeds/supported-platforms-embed.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-105.md
Labels: p_Software, release branch, hold-off

#3121 Copy RS 7.2.4 Feb maintenance release to 7.2-build branch
  content/embeds/supported-platforms-embed.md
  content/rs/references/rest-api/objects/ldap.md
  content/rs/references/rest-api/requests/cluster/ldap.md
  content/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-105.md
Labels: p_Software

#3124 RC: Wrong link in cloud Grafana documentation
  content/rc/cloud-integrations/prometheus-integration.md
Labels: p_Cloud

#3126 RS: Fixed typo in rladmin cluster config/join command option cnm_http_port
  content/rs/references/cli-utilities/rladmin/cluster/config.md
  content/rs/references/cli-utilities/rladmin/cluster/join.md
Labels: p_Software, doc_bug

#3129 RS: Removed OpenSSL 1.0.2 requirement for RS 7.4 on RHEL
  content/embeds/supported-platforms-embed.md
  content/rs/release-notes/rs-7-4-2-releases/_index.md
  content/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-54.md
Labels: p_Software

#3131 K8s: Swordfish release
  content/kubernetes/reference/supported_k8s_distributions.md
  content/kubernetes/release-notes/7-4-2-2.md
Labels: K8s, release branch

#3132 RS: Fixed broken relrefs
  content/rs/installing-upgrading/quickstarts/docker-quickstart.md
Labels: p_Software

#3133 K8s 7.4 version selector
  layouts/404.html
  layouts/partials/flex/body-beforecontent.html
  layouts/partials/flex/scripts.html
Labels: K8s

#3134 K8s swordfish version selector 7.2 build
  layouts/404.html
  layouts/partials/flex/body-beforecontent.html
  layouts/partials/flex/scripts.html
Labels: infrastructure, K8s

#3135 K8s Swordfish version selector 7.4 for 6.4 build
  layouts/404.html
  layouts/partials/flex/body-beforecontent.html
  layouts/partials/flex/scripts.html
Labels: infrastructure, K8s

#3139 Update node.md
  content/rs/references/rest-api/objects/node.md
Labels: p_Software

#3140 K8s: remove consumer-ns from RoleBinding
  content/kubernetes/re-clusters/multi-namespace.md
Labels: K8s, doc_bug

#3136 Remove `sanitized` from rladmin documentation
  content/rs/references/cli-utilities/rladmin/cluster/debug_info.md
Labels: p_Software

#3120 RC: Feb 25th changelog changes
  content/rc/changelog/february-2024.md
Labels: p_Cloud, hold-off

#3145 Update rs-7-4-2-54.md
  content/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-54.md
Labels: p_Software

#3144 Update action.md
  content/rs/references/rest-api/objects/action.md
Labels: p_Software

#3151 replace old image
  static/images/rdi/config-yaml-diagram.png
Labels: rdi

#3150 fixed text on image
  static/images/rdi/config-yaml-diagram.png
Labels: rdi

#3152 RS/RC INFO returns different fields than OSS Redis
  content/rs/references/compatibility/commands/server.md
Labels: p_Software, p_Cloud

#3149 RS: Clarify time zone description
  content/rs/clusters/configure/cluster-settings.md
Labels: p_Software

#3147 Release notes for RedisInsight v.2.44.0
  content/ri/release-notes/v.2.44.0.md
Labels: p_Insight

#3157 RS: Updated supported platforms & OS compatibility policy
  content/embeds/supported-platforms-embed.md
Labels: p_Software

#3153 RS: Clarify RS v5.4.2 & later use CRDB protocol version 1
  content/rs/installing-upgrading/upgrading/upgrade-active-active.md
Labels: p_Software
